// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.

import 'package:restage/restage.dart';

/// The built-in widgets and icons this package names in its
/// own Dart, plus the catalog entries its compiled surfaces
/// render, so a delivered surface can render them.
///
/// The scan covers this package's own `lib/` and not the
/// packages it depends on. An icon reached through a variable,
/// a function return, or an app-defined wrapper rather than
/// named by a compile-time constant is not seen.
const SurfaceVocabulary kRestageAppVocabulary = SurfaceVocabulary(
  widgets: RestageWidgetLibraries.fromVocabulary(
    core: {
      'Text': buildText,
    },
    material: {
      'Icon': buildIcon,
    },
  ),
  icons: RestageIconTable.fromFamilies(families: {
    'CupertinoIcons': {
      0xf81f: IconData(0xf81f,
          fontFamily: 'CupertinoIcons', fontPackage: 'cupertino_icons'),
    },
    'MaterialIcons': {
      0xe5f9: IconData(0xe5f9, fontFamily: 'MaterialIcons'),
    },
  }),
);

/// Pass to Restage.configure(registerWidgets: ...) to register
/// this package with the configured family options.
const RestageWidgetRegistration kRestageWidgetRegistration =
    _RestageWidgetRegistration();

/// Registers the currently enabled RFW widgets.
///
/// Includes both complete built-in families by default.
/// Family options omit full contributions, keeping app requirements.
void registerRestageWidgets({
  bool includeMaterial = true,
  bool includeCupertino = true,
}) {
  kRestageWidgetRegistration(
    includeMaterial: includeMaterial,
    includeCupertino: includeCupertino,
  );
}

final class _RestageWidgetRegistration implements RestageWidgetRegistration {
  const _RestageWidgetRegistration();

  @override
  void call({
    bool includeMaterial = true,
    bool includeCupertino = true,
  }) {
    InstalledWidgetLibraries.add(RestageWidgetLibraries.builtIn(
      includeMaterial: includeMaterial,
      includeCupertino: includeCupertino,
    ));
    InstalledIconTable.add(builtInIconTable(
      includeMaterial: includeMaterial,
      includeCupertino: includeCupertino,
    ));
    kRestageAppVocabulary.addToInstalled(explicitSelection: true);
  }
}

@Deprecated('Use registerRestageWidgets; removed in 3.0')
void registerRestageCustomerWidgets() => registerRestageWidgets();
