// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder map for the 'restage.cupertino' library.
// To change this map: edit lib/registry_curation.dart, then
// re-run build_runner (it regenerates the registry, the
// catalog, and this file).

import 'package:flutter/cupertino.dart';
import 'package:restage_core/restage_core.dart';
import 'package:rfw/rfw.dart' hide Switch;

/// One [LocalWidgetBuilder] per widget entry in `lib/registry.dart`,
/// keyed by widget name.
const Map<String, LocalWidgetBuilder> kCupertinoLibraryFactories =
    <String, LocalWidgetBuilder>{
  'CupertinoActivityIndicator': buildCupertinoActivityIndicator,
  'CupertinoButton': buildCupertinoButton,
  'CupertinoButtonFilled': buildCupertinoButtonFilled,
  'CupertinoListSection': buildCupertinoListSection,
  'CupertinoListSectionInsetGrouped': buildCupertinoListSectionInsetGrouped,
  'CupertinoListTile': buildCupertinoListTile,
  'CupertinoNavigationBar': buildCupertinoNavigationBar,
  'CupertinoPageScaffold': buildCupertinoPageScaffold,
  'CupertinoSwitch': buildCupertinoSwitch,
  'CupertinoTextField': buildCupertinoTextField,
  'CupertinoSlider': buildCupertinoSlider,
  'CupertinoDatePicker': buildCupertinoDatePicker,
  'CupertinoTimerPicker': buildCupertinoTimerPicker,
  'CupertinoPicker': buildCupertinoPicker,
  'CupertinoSearchTextField': buildCupertinoSearchTextField,
  'CupertinoCheckbox': buildCupertinoCheckbox,
};

/// Builds the catalog's `CupertinoActivityIndicator` widget from [source].
Widget buildCupertinoActivityIndicator(
    BuildContext context, DataSource source) {
  return CupertinoActivityIndicator(
    color: ArgumentDecoders.color(source, <Object>['color']),
    animating: source.v<bool>(const <Object>['animating']) ?? true,
    radius: source.v<double>(const <Object>['radius']) ?? 10.0,
  );
}

/// Builds the catalog's `CupertinoButton` widget from [source].
Widget buildCupertinoButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(const <Object>['disabled']) ?? false;

  return CupertinoButton(
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed:
        disabled ? null : source.voidHandler(const <Object>['onPressed']),
    child: source.child(const <Object>['child']),
  );
}

/// Builds the catalog's `CupertinoButtonFilled` widget from [source].
Widget buildCupertinoButtonFilled(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(const <Object>['disabled']) ?? false;

  return CupertinoButton.filled(
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed:
        disabled ? null : source.voidHandler(const <Object>['onPressed']),
    child: source.child(const <Object>['child']),
  );
}

/// Builds the catalog's `CupertinoListSection` widget from [source].
Widget buildCupertinoListSection(BuildContext context, DataSource source) {
  return CupertinoListSection(
    header: source.optionalChild(const <Object>['header']),
    footer: source.optionalChild(const <Object>['footer']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    children: source.isList(const <Object>['children'])
        ? source.childList(const <Object>['children'])
        : null,
  );
}

/// Builds the catalog's `CupertinoListSectionInsetGrouped` widget from [source].
Widget buildCupertinoListSectionInsetGrouped(
    BuildContext context, DataSource source) {
  return CupertinoListSection.insetGrouped(
    header: source.optionalChild(const <Object>['header']),
    footer: source.optionalChild(const <Object>['footer']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    children: source.isList(const <Object>['children'])
        ? source.childList(const <Object>['children'])
        : null,
  );
}

/// Builds the catalog's `CupertinoListTile` widget from [source].
Widget buildCupertinoListTile(BuildContext context, DataSource source) {
  return CupertinoListTile(
    title: source.child(const <Object>['title']),
    subtitle: source.optionalChild(const <Object>['subtitle']),
    leading: source.optionalChild(const <Object>['leading']),
    trailing: source.optionalChild(const <Object>['trailing']),
    onTap: source.voidHandler(const <Object>['onTap']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
  );
}

/// Builds the catalog's `CupertinoNavigationBar` widget from [source].
Widget buildCupertinoNavigationBar(BuildContext context, DataSource source) {
  return CupertinoNavigationBar(
    leading: source.optionalChild(const <Object>['leading']),
    automaticallyImplyLeading:
        source.v<bool>(const <Object>['automaticallyImplyLeading']) ?? true,
    automaticallyImplyMiddle:
        source.v<bool>(const <Object>['automaticallyImplyMiddle']) ?? true,
    previousPageTitle: source.v<String>(const <Object>['previousPageTitle']),
    middle: source.optionalChild(const <Object>['middle']),
    trailing: source.optionalChild(const <Object>['trailing']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    automaticBackgroundVisibility:
        source.v<bool>(const <Object>['automaticBackgroundVisibility']) ?? true,
    enableBackgroundFilterBlur:
        source.v<bool>(const <Object>['enableBackgroundFilterBlur']) ?? true,
    brightness: RestageDecoders.enumByName<Brightness>(
        Brightness.values, source, <Object>['brightness']),
  );
}

/// Builds the catalog's `CupertinoPageScaffold` widget from [source].
Widget buildCupertinoPageScaffold(BuildContext context, DataSource source) {
  return CupertinoPageScaffold(
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    child: source.child(const <Object>['child']),
  );
}

/// Builds the catalog's `CupertinoSwitch` widget from [source].
Widget buildCupertinoSwitch(BuildContext context, DataSource source) {
  return CupertinoSwitch(
    value: source.v<bool>(const <Object>['value']) ??
        (throw ArgumentError('CupertinoSwitch.value is required.')),
    onChanged:
        RestageDecoders.valueChanged<bool>(source, const <Object>['onChanged']),
    activeTrackColor:
        ArgumentDecoders.color(source, <Object>['activeTrackColor']),
  );
}

/// Builds the catalog's `CupertinoTextField` widget from [source].
Widget buildCupertinoTextField(BuildContext context, DataSource source) {
  return CupertinoTextField(
    placeholder: source.v<String>(const <Object>['placeholder']),
    obscureText: source.v<bool>(const <Object>['obscureText']) ?? false,
    maxLines: source.v<int>(const <Object>['maxLines']) ?? 1,
    maxLength: source.v<int>(const <Object>['maxLength']),
    onChanged: RestageDecoders.valueChanged<String>(
        source, const <Object>['onChanged']),
    onSubmitted: RestageDecoders.valueChanged<String>(
        source, const <Object>['onSubmitted']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
  );
}

/// Builds the catalog's `CupertinoSlider` widget from [source].
Widget buildCupertinoSlider(BuildContext context, DataSource source) {
  return CupertinoSlider(
    value: source.v<double>(const <Object>['value']) ??
        (throw ArgumentError('CupertinoSlider.value is required.')),
    onChanged: RestageDecoders.valueChanged<double>(
        source, const <Object>['onChanged']),
    min: source.v<double>(const <Object>['min']) ?? 0.0,
    max: source.v<double>(const <Object>['max']) ?? 1.0,
    divisions: source.v<int>(const <Object>['divisions']),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
  );
}

/// Builds the catalog's `CupertinoDatePicker` widget from [source].
Widget buildCupertinoDatePicker(BuildContext context, DataSource source) {
  return CupertinoDatePicker(
    mode: RestageDecoders.enumByName<CupertinoDatePickerMode>(
            CupertinoDatePickerMode.values, source, <Object>['mode']) ??
        CupertinoDatePickerMode.dateAndTime,
    onDateTimeChanged: RestageDecoders.valueChanged<DateTime>(
            source, const <Object>['onDateTimeChanged']) ??
        (DateTime _) {},
    minimumYear: source.v<int>(const <Object>['minimumYear']) ?? 1,
    maximumYear: source.v<int>(const <Object>['maximumYear']),
    minuteInterval: source.v<int>(const <Object>['minuteInterval']) ?? 1,
    use24hFormat: source.v<bool>(const <Object>['use24hFormat']) ?? false,
    dateOrder: RestageDecoders.enumByName<DatePickerDateOrder>(
        DatePickerDateOrder.values, source, <Object>['dateOrder']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    showDayOfWeek: source.v<bool>(const <Object>['showDayOfWeek']) ?? false,
    showTimeSeparator:
        source.v<bool>(const <Object>['showTimeSeparator']) ?? false,
    itemExtent: source.v<double>(const <Object>['itemExtent']) ?? 32.0,
    changeReportingBehavior:
        RestageDecoders.enumByName<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
  );
}

/// Builds the catalog's `CupertinoTimerPicker` widget from [source].
Widget buildCupertinoTimerPicker(BuildContext context, DataSource source) {
  return CupertinoTimerPicker(
    mode: RestageDecoders.enumByName<CupertinoTimerPickerMode>(
            CupertinoTimerPickerMode.values, source, <Object>['mode']) ??
        CupertinoTimerPickerMode.hms,
    minuteInterval: source.v<int>(const <Object>['minuteInterval']) ?? 1,
    secondInterval: source.v<int>(const <Object>['secondInterval']) ?? 1,
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    itemExtent: source.v<double>(const <Object>['itemExtent']) ?? 32.0,
    onTimerDurationChanged: RestageDecoders.valueChanged<Duration>(
            source, const <Object>['onTimerDurationChanged']) ??
        (Duration _) {},
    changeReportingBehavior:
        RestageDecoders.enumByName<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
  );
}

/// Builds the catalog's `CupertinoPicker` widget from [source].
Widget buildCupertinoPicker(BuildContext context, DataSource source) {
  return CupertinoPicker(
    diameterRatio: source.v<double>(const <Object>['diameterRatio']) ?? 1.07,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    offAxisFraction: source.v<double>(const <Object>['offAxisFraction']) ?? 0.0,
    useMagnifier: source.v<bool>(const <Object>['useMagnifier']) ?? false,
    magnification: source.v<double>(const <Object>['magnification']) ?? 1.0,
    squeeze: source.v<double>(const <Object>['squeeze']) ?? 1.45,
    changeReportingBehavior:
        RestageDecoders.enumByName<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
    itemExtent: source.v<double>(const <Object>['itemExtent']) ??
        (throw ArgumentError('CupertinoPicker.itemExtent is required.')),
    onSelectedItemChanged: RestageDecoders.valueChanged<int>(
        source, const <Object>['onSelectedItemChanged']),
    looping: source.v<bool>(const <Object>['looping']) ?? false,
    children: source.childList(const <Object>['children']),
  );
}

/// Builds the catalog's `CupertinoSearchTextField` widget from [source].
Widget buildCupertinoSearchTextField(BuildContext context, DataSource source) {
  return CupertinoSearchTextField(
    onChanged: RestageDecoders.valueChanged<String>(
        source, const <Object>['onChanged']),
    onSubmitted: RestageDecoders.valueChanged<String>(
        source, const <Object>['onSubmitted']),
    placeholder: source.v<String>(const <Object>['placeholder']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    itemSize: source.v<double>(const <Object>['itemSize']) ?? 20.0,
  );
}

/// Builds the catalog's `CupertinoCheckbox` widget from [source].
Widget buildCupertinoCheckbox(BuildContext context, DataSource source) {
  return CupertinoCheckbox(
    value: source.v<bool>(const <Object>['value']) ??
        (throw ArgumentError('CupertinoCheckbox.value is required.')),
    tristate: source.v<bool>(const <Object>['tristate']) ?? false,
    onChanged: RestageDecoders.valueChanged<bool?>(
        source, const <Object>['onChanged']),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
    checkColor: ArgumentDecoders.color(source, <Object>['checkColor']),
    semanticLabel: source.v<String>(const <Object>['semanticLabel']),
  );
}
