// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder map for the 'restage.cupertino' library.
// To change this map: edit lib/registry_curation.dart, then
// re-run build_runner (it regenerates the registry, the
// catalog, and this file).

import 'package:flutter/cupertino.dart';
import 'package:rfw/rfw.dart' hide Switch;

/// One [LocalWidgetBuilder] per widget entry in `lib/registry.dart`,
/// keyed by widget name.
const Map<String, LocalWidgetBuilder> kCupertinoLibraryFactories =
    <String, LocalWidgetBuilder>{
  'CupertinoActivityIndicator': _buildCupertinoActivityIndicator,
  'CupertinoButton': _buildCupertinoButton,
  'CupertinoButtonFilled': _buildCupertinoButtonFilled,
  'CupertinoListSection': _buildCupertinoListSection,
  'CupertinoListSectionInsetGrouped': _buildCupertinoListSectionInsetGrouped,
  'CupertinoListTile': _buildCupertinoListTile,
  'CupertinoNavigationBar': _buildCupertinoNavigationBar,
  'CupertinoPageScaffold': _buildCupertinoPageScaffold,
  'CupertinoSwitch': _buildCupertinoSwitch,
  'CupertinoTextField': _buildCupertinoTextField,
  'CupertinoSlider': _buildCupertinoSlider,
  'CupertinoDatePicker': _buildCupertinoDatePicker,
  'CupertinoTimerPicker': _buildCupertinoTimerPicker,
  'CupertinoPicker': _buildCupertinoPicker,
  'CupertinoSearchTextField': _buildCupertinoSearchTextField,
  'CupertinoCheckbox': _buildCupertinoCheckbox,
};

Widget _buildCupertinoActivityIndicator(
    BuildContext context, DataSource source) {
  return CupertinoActivityIndicator(
    color: ArgumentDecoders.color(source, <Object>['color']),
    animating: source.v<bool>(<Object>['animating']) ?? true,
    radius: source.v<double>(<Object>['radius']) ?? 10.0,
  );
}

Widget _buildCupertinoButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return CupertinoButton(
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildCupertinoButtonFilled(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return CupertinoButton.filled(
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildCupertinoListSection(BuildContext context, DataSource source) {
  return CupertinoListSection(
    header: source.optionalChild(<Object>['header']),
    footer: source.optionalChild(<Object>['footer']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildCupertinoListSectionInsetGrouped(
    BuildContext context, DataSource source) {
  return CupertinoListSection.insetGrouped(
    header: source.optionalChild(<Object>['header']),
    footer: source.optionalChild(<Object>['footer']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildCupertinoListTile(BuildContext context, DataSource source) {
  return CupertinoListTile(
    title: source.child(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    leading: source.optionalChild(<Object>['leading']),
    trailing: source.optionalChild(<Object>['trailing']),
    onTap: source.voidHandler(<Object>['onTap']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
  );
}

Widget _buildCupertinoNavigationBar(BuildContext context, DataSource source) {
  return CupertinoNavigationBar(
    leading: source.optionalChild(<Object>['leading']),
    middle: source.optionalChild(<Object>['middle']),
    trailing: source.optionalChild(<Object>['trailing']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
  );
}

Widget _buildCupertinoPageScaffold(BuildContext context, DataSource source) {
  return CupertinoPageScaffold(
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildCupertinoSwitch(BuildContext context, DataSource source) {
  return CupertinoSwitch(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('CupertinoSwitch.value is required.')),
    onChanged: source.handler<ValueChanged<bool>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (bool value) => trigger(<String, Object?>{'value': value})),
    activeTrackColor:
        ArgumentDecoders.color(source, <Object>['activeTrackColor']),
  );
}

Widget _buildCupertinoTextField(BuildContext context, DataSource source) {
  return CupertinoTextField(
    placeholder: source.v<String>(<Object>['placeholder']),
    obscureText: source.v<bool>(<Object>['obscureText']) ?? false,
    maxLines: source.v<int>(<Object>['maxLines']) ?? 1,
    maxLength: source.v<int>(<Object>['maxLength']),
    onChanged: source.handler<ValueChanged<String>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    onSubmitted: source.handler<ValueChanged<String>>(
        <Object>['onSubmitted'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
  );
}

Widget _buildCupertinoSlider(BuildContext context, DataSource source) {
  return CupertinoSlider(
    value: source.v<double>(<Object>['value']) ??
        (throw ArgumentError('CupertinoSlider.value is required.')),
    onChanged: source.handler<ValueChanged<double>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (double value) => trigger(<String, Object?>{'value': value})),
    min: source.v<double>(<Object>['min']) ?? 0.0,
    max: source.v<double>(<Object>['max']) ?? 1.0,
    divisions: source.v<int>(<Object>['divisions']),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
  );
}

Widget _buildCupertinoDatePicker(BuildContext context, DataSource source) {
  return CupertinoDatePicker(
    mode: ArgumentDecoders.enumValue<CupertinoDatePickerMode>(
            CupertinoDatePickerMode.values, source, <Object>['mode']) ??
        CupertinoDatePickerMode.dateAndTime,
    onDateTimeChanged: source.handler<ValueChanged<DateTime>>(
            <Object>['onDateTimeChanged'],
            (HandlerTrigger trigger) => (DateTime value) =>
                trigger(<String, Object?>{'value': value})) ??
        (DateTime _) {},
    minimumYear: source.v<int>(<Object>['minimumYear']) ?? 1,
    maximumYear: source.v<int>(<Object>['maximumYear']),
    minuteInterval: source.v<int>(<Object>['minuteInterval']) ?? 1,
    use24hFormat: source.v<bool>(<Object>['use24hFormat']) ?? false,
    dateOrder: ArgumentDecoders.enumValue<DatePickerDateOrder>(
        DatePickerDateOrder.values, source, <Object>['dateOrder']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    showDayOfWeek: source.v<bool>(<Object>['showDayOfWeek']) ?? false,
    showTimeSeparator: source.v<bool>(<Object>['showTimeSeparator']) ?? false,
    itemExtent: source.v<double>(<Object>['itemExtent']) ?? 32.0,
    changeReportingBehavior:
        ArgumentDecoders.enumValue<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
  );
}

Widget _buildCupertinoTimerPicker(BuildContext context, DataSource source) {
  return CupertinoTimerPicker(
    mode: ArgumentDecoders.enumValue<CupertinoTimerPickerMode>(
            CupertinoTimerPickerMode.values, source, <Object>['mode']) ??
        CupertinoTimerPickerMode.hms,
    minuteInterval: source.v<int>(<Object>['minuteInterval']) ?? 1,
    secondInterval: source.v<int>(<Object>['secondInterval']) ?? 1,
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    itemExtent: source.v<double>(<Object>['itemExtent']) ?? 32.0,
    onTimerDurationChanged: source.handler<ValueChanged<Duration>>(
            <Object>['onTimerDurationChanged'],
            (HandlerTrigger trigger) => (Duration value) =>
                trigger(<String, Object?>{'value': value})) ??
        (Duration _) {},
    changeReportingBehavior:
        ArgumentDecoders.enumValue<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
  );
}

Widget _buildCupertinoPicker(BuildContext context, DataSource source) {
  return CupertinoPicker(
    diameterRatio: source.v<double>(<Object>['diameterRatio']) ?? 1.07,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    offAxisFraction: source.v<double>(<Object>['offAxisFraction']) ?? 0.0,
    useMagnifier: source.v<bool>(<Object>['useMagnifier']) ?? false,
    magnification: source.v<double>(<Object>['magnification']) ?? 1.0,
    squeeze: source.v<double>(<Object>['squeeze']) ?? 1.45,
    changeReportingBehavior:
        ArgumentDecoders.enumValue<ChangeReportingBehavior>(
                ChangeReportingBehavior.values,
                source,
                <Object>['changeReportingBehavior']) ??
            ChangeReportingBehavior.onScrollUpdate,
    itemExtent: source.v<double>(<Object>['itemExtent']) ??
        (throw ArgumentError('CupertinoPicker.itemExtent is required.')),
    onSelectedItemChanged: source.handler<ValueChanged<int>>(
            <Object>['onSelectedItemChanged'],
            (HandlerTrigger trigger) =>
                (int value) => trigger(<String, Object?>{'value': value})) ??
        (int _) {},
    looping: source.v<bool>(<Object>['looping']) ?? false,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildCupertinoSearchTextField(BuildContext context, DataSource source) {
  return CupertinoSearchTextField(
    onChanged: source.handler<ValueChanged<String>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    onSubmitted: source.handler<ValueChanged<String>>(
        <Object>['onSubmitted'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    placeholder: source.v<String>(<Object>['placeholder']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    itemSize: source.v<double>(<Object>['itemSize']) ?? 20.0,
  );
}

Widget _buildCupertinoCheckbox(BuildContext context, DataSource source) {
  return CupertinoCheckbox(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('CupertinoCheckbox.value is required.')),
    tristate: source.v<bool>(<Object>['tristate']) ?? false,
    onChanged: source.handler<ValueChanged<bool?>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (bool? value) => trigger(<String, Object?>{'value': value})),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
    checkColor: ArgumentDecoders.color(source, <Object>['checkColor']),
    semanticLabel: source.v<String>(<Object>['semanticLabel']),
  );
}
