// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.

import 'package:rfw_catalog_schema/rfw_catalog_schema.dart';

final Catalog kUserCatalog = Catalog(
  schemaVersion: 4,
  generatedAt: '1970-01-01T00:00:00Z',
  libraries: {
    WidgetLibrary.custom('restage_example.widgets'):
        const LibraryInfo(version: '0.0.0', capabilityVersion: 3),
  },
  widgets: [
    WidgetEntry(
      wireId: WireId('w0001'),
      name: 'AcmeBorder',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.layout,
      description: 'Wraps a single child in a colored border.',
      flutterType:
          'package:restage_example/widgets/acme_border.dart#AcmeBorder',
      childrenSlot: ChildrenSlot.single,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0001'),
          name: 'child',
          type: PropertyType.widget,
          description: 'Wrapped child widget.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0002'),
          name: 'color',
          type: PropertyType.color,
          description: 'Border color. Defaults to the primary container.',
          defaultBrandToken: 'primary',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0002'),
      name: 'AcmeStack',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.layout,
      description: 'Overlays a list of children in z-order.',
      flutterType: 'package:restage_example/widgets/acme_stack.dart#AcmeStack',
      childrenSlot: ChildrenSlot.list,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0003'),
          name: 'children',
          type: PropertyType.widgetList,
          description: 'Overlay children, top-most last.',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0016'),
      name: 'PlanBoard',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description:
          'Renders plans keyed by slug plus a highlighted plan per billing tier (map-of-data-class properties).',
      flutterType: 'package:restage_example/widgets/plan_board.dart#PlanBoard',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0045'),
          name: 'plans',
          type: PropertyType.unknown,
          description: 'The plans to render, keyed by slug.',
          required: true,
          valueShape: ScalarShape(
              propertyType: PropertyType.unknown,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'Map')),
        ),
        PropertyEntry(
          wireId: WireId('p0046'),
          name: 'highlights',
          type: PropertyType.unknown,
          description: 'The highlighted plan for each billing tier.',
          required: true,
          valueShape: ScalarShape(
              propertyType: PropertyType.unknown,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'Map')),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0010'),
      name: 'PricingCard',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description:
          'Renders a subscription plan (a nested data-class property).',
      flutterType:
          'package:restage_example/widgets/pricing_card.dart#PricingCard',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0024'),
          name: 'plan',
          type: PropertyType.structured,
          description: 'The plan to render.',
          required: true,
          structuredRef: WireIdRef(
              library: 'restage_example.widgets', wireId: WireId('s0001')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_example.widgets', wireId: WireId('s0001'))),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0013'),
      name: 'PricingTable',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description:
          'Renders a list of subscription plans (a list-of-data-class property).',
      flutterType:
          'package:restage_example/widgets/pricing_table.dart#PricingTable',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0035'),
          name: 'plans',
          type: PropertyType.unknown,
          description: 'The plans to render, in order.',
          required: true,
          valueShape: ListShape(
              propertyType: PropertyType.unknown,
              itemShape: StructuredShape(
                  propertyType: PropertyType.structured,
                  structuredRef: WireIdRef(
                      library: 'restage_example.widgets',
                      wireId: WireId('s0001')))),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0003'),
      name: 'PromoBadge',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.action,
      description: 'Pill-shaped promotional label.',
      flutterType:
          'package:restage_example/widgets/promo_badge.dart#PromoBadge',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0004'),
          name: 'label',
          type: PropertyType.string,
          description: 'Visible label.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0005'),
          name: 'color',
          type: PropertyType.color,
          description: 'Background color. Defaults to the primary container.',
          defaultBrandToken: 'primary',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0012'),
      name: 'PulseBadge',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'A badge that pulses, driven by an AnimationController.',
      flutterType:
          'package:restage_example/widgets/pulse_badge.dart#PulseBadge',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0033'),
          name: 'label',
          type: PropertyType.string,
          description: 'Caption text.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0034'),
          name: 'count',
          type: PropertyType.integer,
          description: 'Count shown after the caption.',
          required: true,
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0015'),
      name: 'SectionHeader',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'Introduces a section with heading and entry metadata.',
      flutterType:
          'package:restage_example/widgets/section_header.dart#SectionHeader',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0041'),
          name: 'heading',
          type: PropertyType.unknown,
          description: 'The section title, step, and visual tone.',
          required: true,
          valueShape: ScalarShape(
              propertyType: PropertyType.unknown,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'Record')),
        ),
        PropertyEntry(
          wireId: WireId('p0042'),
          name: 'entry',
          type: PropertyType.structured,
          description: 'The section entry and its ordering metadata.',
          required: true,
          structuredRef: WireIdRef(
              library: 'restage_example.widgets', wireId: WireId('s0005')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_example.widgets', wireId: WireId('s0005'))),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0009'),
      name: 'StatBadge',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'A labelled value pill, e.g. "Streak · 7 days".',
      flutterType:
          'package:restage_example/widgets/minimal_custom_widget.dart#StatBadge',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0021'),
          name: 'label',
          type: PropertyType.string,
          description: 'Caption text.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0022'),
          name: 'value',
          type: PropertyType.string,
          description: 'Value text.',
          required: true,
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0011'),
      name: 'StreakBadge',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'A pill showing a streak count, its fill deepening with it.',
      flutterType:
          'package:restage_example/widgets/streak_badge.dart#StreakBadge',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0031'),
          name: 'label',
          type: PropertyType.string,
          description: 'Caption text.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0032'),
          name: 'count',
          type: PropertyType.integer,
          description: 'Streak count.',
          required: true,
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0014'),
      name: 'TierBoard',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.decoration,
      description:
          'Renders a list of pricing tiers, each with a nested feature list.',
      flutterType: 'package:restage_example/widgets/tier_board.dart#TierBoard',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0036'),
          name: 'tiers',
          type: PropertyType.unknown,
          description: 'The tiers to render.',
          required: true,
          valueShape: ListShape(
              propertyType: PropertyType.unknown,
              itemShape: StructuredShape(
                  propertyType: PropertyType.structured,
                  structuredRef: WireIdRef(
                      library: 'restage_example.widgets',
                      wireId: WireId('s0003')))),
        ),
        PropertyEntry(
          wireId: WireId('p0037'),
          name: 'bonusTiers',
          type: PropertyType.unknown,
          description: 'Optional bonus tiers.',
          valueShape: ListShape(
              propertyType: PropertyType.unknown,
              itemShape: StructuredShape(
                  propertyType: PropertyType.structured,
                  structuredRef: WireIdRef(
                      library: 'restage_example.widgets',
                      wireId: WireId('s0003')))),
        ),
      ],
    ),
  ],
  structuredTypes: [
    StructuredEntry(
      wireId: WireId('s0001'),
      name: 'Plan',
      library: WidgetLibrary.custom('restage_example.widgets'),
      description:
          'A subscription plan rendered inside a [PricingCard] — a customer data class with a nested [Price], an optional badge, and an enum tier.',
      sourceType: 'package:restage_example/widgets/pricing_card.dart#Plan',
      fields: [
        StructuredField(
          wireId: WireId('p0025'),
          name: 'name',
          type: PropertyType.string,
          description: 'The plan\'s display name.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
        StructuredField(
          wireId: WireId('p0026'),
          name: 'price',
          type: PropertyType.structured,
          description:
              'The plan\'s price (a nested data class — a two-level structured graph).',
          structuredRef: WireIdRef(
              library: 'restage_example.widgets', wireId: WireId('s0002')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_example.widgets', wireId: WireId('s0002'))),
        ),
        StructuredField(
          wireId: WireId('p0027'),
          name: 'badge',
          type: PropertyType.string,
          description:
              'An optional highlight badge (e.g. `\'Most popular\'`); `null` when the wire omits it.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
        StructuredField(
          wireId: WireId('p0028'),
          name: 'tier',
          type: PropertyType.enumValue,
          description:
              'The billing tier. Defaults to [PlanTier.starter] when the wire omits it.',
          valueShape: EnumShape(
              propertyType: PropertyType.enumValue,
              enumRef: DartTypeRef(
                  libraryUri:
                      'package:restage_example/widgets/pricing_card.dart',
                  symbolName: 'PlanTier')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0001'),
          argMappings: {
            'badge': ArgMapping(targetFields: [WireId('p0027')]),
            'name': ArgMapping(targetFields: [WireId('p0025')]),
            'price': ArgMapping(targetFields: [WireId('p0026')]),
            'tier': ArgMapping(targetFields: [WireId('p0028')]),
          },
          description: 'Creates a plan.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0002'),
      name: 'Price',
      library: WidgetLibrary.custom('restage_example.widgets'),
      description:
          'A price: an integer [amount] in the currency\'s minor units plus the ISO currency code.',
      sourceType: 'package:restage_example/widgets/pricing_card.dart#Price',
      fields: [
        StructuredField(
          wireId: WireId('p0029'),
          name: 'amount',
          type: PropertyType.integer,
          description:
              'The amount in the currency\'s minor units (e.g. cents).',
          valueShape: ScalarShape(
              propertyType: PropertyType.integer,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'int')),
        ),
        StructuredField(
          wireId: WireId('p0030'),
          name: 'currency',
          type: PropertyType.string,
          description:
              'The ISO-4217 currency code. Defaults to `\'USD\'` when the wire omits it.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0002'),
          argMappings: {
            'amount': ArgMapping(targetFields: [WireId('p0029')]),
            'currency': ArgMapping(targetFields: [WireId('p0030')]),
          },
          description: 'Creates a price.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0005'),
      name: 'SectionEntry',
      library: WidgetLibrary.custom('restage_example.widgets'),
      description: 'A section entry that itself carries a record field.',
      sourceType:
          'package:restage_example/widgets/section_header.dart#SectionEntry',
      fields: [
        StructuredField(
          wireId: WireId('p0043'),
          name: 'label',
          type: PropertyType.string,
          description: 'The entry\'s display label.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
        StructuredField(
          wireId: WireId('p0044'),
          name: 'meta',
          type: PropertyType.unknown,
          description: 'The entry\'s ordering and pinned state.',
          valueShape: ScalarShape(
              propertyType: PropertyType.unknown,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'Record')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0005'),
          argMappings: {
            'label': ArgMapping(targetFields: [WireId('p0043')]),
            'meta': ArgMapping(targetFields: [WireId('p0044')]),
          },
          description: 'Creates a section entry.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0003'),
      name: 'Tier',
      library: WidgetLibrary.custom('restage_example.widgets'),
      description:
          'A pricing tier: a name plus a list of the features it includes — a customer data class that itself carries a `List<Feature>`, so a `List<Tier>` is a two-level nested list of objects.',
      sourceType: 'package:restage_example/widgets/tier_board.dart#Tier',
      fields: [
        StructuredField(
          wireId: WireId('p0038'),
          name: 'name',
          type: PropertyType.string,
          description: 'The tier\'s display name.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
        StructuredField(
          wireId: WireId('p0039'),
          name: 'features',
          type: PropertyType.unknown,
          description:
              'The features this tier includes (a nested list of data classes).',
          valueShape: ListShape(
              propertyType: PropertyType.unknown,
              itemShape: StructuredShape(
                  propertyType: PropertyType.structured,
                  structuredRef: WireIdRef(
                      library: 'restage_example.widgets',
                      wireId: WireId('s0004')))),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0003'),
          argMappings: {
            'features': ArgMapping(targetFields: [WireId('p0039')]),
            'name': ArgMapping(targetFields: [WireId('p0038')]),
          },
          description: 'Creates a tier.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0004'),
      name: 'Feature',
      library: WidgetLibrary.custom('restage_example.widgets'),
      description: 'A single feature line within a [Tier].',
      sourceType: 'package:restage_example/widgets/tier_board.dart#Feature',
      fields: [
        StructuredField(
          wireId: WireId('p0040'),
          name: 'label',
          type: PropertyType.string,
          description: 'The feature\'s display label.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0004'),
          argMappings: {
            'label': ArgMapping(targetFields: [WireId('p0040')]),
          },
          description: 'Creates a feature.',
        ),
      ],
    ),
  ],
);
