// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder closures for every @RestageWidget-
// annotated class in this package, plus a one-call helper
// that registers them with Restage at startup.
//
// To change this file: edit the @RestageWidget /
// @RestageProperty annotations on the underlying classes,
// then re-run build_runner.

import 'package:flutter/widgets.dart';
import 'package:restage/restage.dart';
import 'package:restage_example/widgets/acme_border.dart';
import 'package:restage_example/widgets/acme_stack.dart';
import 'package:restage_example/widgets/promo_badge.dart';

/// Registers every emittable @RestageWidget-annotated class
/// in this package with Restage. Call once at the app's
/// startup, before any `RestagePaywall` mounts. Idempotent
/// after `Restage.debugReset`, so test setUps may call it
/// again between cases.
void registerRestageCustomerWidgets() {
  Restage.registerWidgetLibrary(
    WidgetLibrary.custom('restage_example.widgets'),
    widgets: const <RestageWidgetFactory>[
      RestageWidgetFactory(name: 'AcmeBorder', builder: _buildAcmeBorder),
      RestageWidgetFactory(name: 'AcmeStack', builder: _buildAcmeStack),
      RestageWidgetFactory(name: 'PromoBadge', builder: _buildPromoBadge),
    ],
  );
}

Widget _buildAcmeBorder(BuildContext context, DataSource source) {
  return AcmeBorder(
    color: ArgumentDecoders.color(source, <Object>['color']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildAcmeStack(BuildContext context, DataSource source) {
  return AcmeStack(
    children: source.childList(<Object>['children']),
  );
}

Widget _buildPromoBadge(BuildContext context, DataSource source) {
  return PromoBadge(
    label: source.v<String>(<Object>['label']) ??
        (throw ArgumentError('PromoBadge.label is required.')),
    color: ArgumentDecoders.color(source, <Object>['color']),
  );
}
