// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder closures for every admitted
// @RestageWidget class in this package, plus a one-call helper
// that registers them with Restage at startup.
//
// Inputs come from public unnamed generative constructors;
// edit the ordinary Flutter constructor, fields, Dartdoc, or
// optional Restage overlays, then re-run build_runner.

import 'package:flutter/widgets.dart';
import 'package:restage_example/widgets/acme_border.dart' as s0;
import 'package:restage_example/widgets/acme_stack.dart' as s1;
import 'package:restage_example/widgets/minimal_custom_widget.dart' as s2;
import 'package:restage_example/widgets/plan_board.dart' as s3;
import 'package:restage_example/widgets/pricing_card.dart' as s4;
import 'package:restage_example/widgets/pricing_table.dart' as s5;
import 'package:restage_example/widgets/promo_badge.dart' as s6;
import 'package:restage_example/widgets/pulse_badge.dart' as s7;
import 'package:restage_example/widgets/section_header.dart' as s8;
import 'package:restage_example/widgets/streak_badge.dart' as s9;
import 'package:restage_example/widgets/tier_board.dart' as s10;
import 'package:restage/restage.dart';

/// Registers every emittable @RestageWidget-annotated class
/// in this package with Restage. Call once at the app's
/// startup, before any `RestagePaywall` mounts. Idempotent
/// after `Restage.debugReset`, so test setUps may call it
/// again between cases.
void registerRestageCustomerWidgets() {
  Restage.registerWidgetLibrary(
    WidgetLibrary.custom('restage_example.widgets'),
    capabilityVersion: 3,
    widgets: const <RestageWidgetFactory>[
      RestageWidgetFactory(name: 'AcmeBorder', builder: _buildAcmeBorder),
      RestageWidgetFactory(name: 'AcmeStack', builder: _buildAcmeStack),
      RestageWidgetFactory(name: 'PlanBoard', builder: _buildPlanBoard),
      RestageWidgetFactory(name: 'PricingCard', builder: _buildPricingCard),
      RestageWidgetFactory(name: 'PricingTable', builder: _buildPricingTable),
      RestageWidgetFactory(name: 'PromoBadge', builder: _buildPromoBadge),
      RestageWidgetFactory(name: 'PulseBadge', builder: _buildPulseBadge),
      RestageWidgetFactory(name: 'SectionHeader', builder: _buildSectionHeader),
      RestageWidgetFactory(name: 'StatBadge', builder: _buildStatBadge),
      RestageWidgetFactory(name: 'StreakBadge', builder: _buildStreakBadge),
      RestageWidgetFactory(name: 'TierBoard', builder: _buildTierBoard),
    ],
  );
}

Widget _buildAcmeBorder(BuildContext context, DataSource source) {
  return s0.AcmeBorder(
    child: source.child(<Object>['child']),
    color: ArgumentDecoders.color(source, <Object>['color']),
  );
}

Widget _buildAcmeStack(BuildContext context, DataSource source) {
  return s1.AcmeStack(
    children: source.childList(<Object>['children']),
  );
}

Widget _buildPlanBoard(BuildContext context, DataSource source) {
  return s3.PlanBoard(
    plans: source.isList(<Object>['plans'])
        ? () {
            final m0 = <String, s4.Plan>{};
            final n0 = source.length(<Object>['plans']);
            for (var i0 = 0; i0 < n0; i0++) {
              if (!source.isMap(<Object>['plans', i0])) {
                throw ArgumentError('PlanBoard.plans entry must be an object.');
              }
              final k0 = source.v<String>(<Object>['plans', i0, 'key']) ??
                  (throw ArgumentError(
                      'PlanBoard.plans entry key is required.'));
              if (m0.containsKey(k0)) {
                throw ArgumentError('PlanBoard.plans has a duplicate key.');
              }
              m0[k0] = source.isMap(<Object>['plans', i0, 'value'])
                  ? s4.Plan(
                      name:
                          source.v<String>(<Object>['plans', i0, 'value', 'name']) ??
                              (throw ArgumentError('Plan.name is required.')),
                      price: source.isMap(<Object>['plans', i0, 'value', 'price'])
                          ? s4.Price(source.v<int>(<Object>['plans', i0, 'value', 'price', 'amount']) ?? (throw ArgumentError('Price.amount is required.')),
                              currency:
                                  source.v<String>(<Object>['plans', i0, 'value', 'price', 'currency']) ??
                                      'USD')
                          : (throw ArgumentError('Plan.price is required.')),
                      badge: source
                          .v<String>(<Object>['plans', i0, 'value', 'badge']),
                      tier: RestageDecoders.enumByName<s4.PlanTier>(
                              s4.PlanTier.values,
                              source,
                              <Object>['plans', i0, 'value', 'tier']) ??
                          s4.PlanTier.starter)
                  : (throw ArgumentError('PlanBoard.plans entry value is required.'));
            }
            return m0;
          }()
        : (throw ArgumentError('PlanBoard.plans is required.')),
    highlights: source.isList(<Object>['highlights'])
        ? () {
            final m0 = <s4.PlanTier, s4.Plan>{};
            final n0 = source.length(<Object>['highlights']);
            for (var i0 = 0; i0 < n0; i0++) {
              if (!source.isMap(<Object>['highlights', i0])) {
                throw ArgumentError(
                    'PlanBoard.highlights entry must be an object.');
              }
              final k0 = RestageDecoders.enumByName<s4.PlanTier>(
                      s4.PlanTier.values,
                      source,
                      <Object>['highlights', i0, 'key']) ??
                  (throw ArgumentError(
                      'PlanBoard.highlights entry key is not a known member.'));
              if (m0.containsKey(k0)) {
                throw ArgumentError(
                    'PlanBoard.highlights has a duplicate key.');
              }
              m0[k0] = source.isMap(<Object>['highlights', i0, 'value'])
                  ? s4.Plan(
                      name: source.v<String>(<Object>['highlights', i0, 'value', 'name']) ??
                          (throw ArgumentError('Plan.name is required.')),
                      price: source.isMap(<Object>['highlights', i0, 'value', 'price'])
                          ? s4.Price(source.v<int>(<Object>['highlights', i0, 'value', 'price', 'amount']) ?? (throw ArgumentError('Price.amount is required.')),
                              currency: source.v<String>(<Object>['highlights', i0, 'value', 'price', 'currency']) ??
                                  'USD')
                          : (throw ArgumentError('Plan.price is required.')),
                      badge: source.v<String>(
                          <Object>['highlights', i0, 'value', 'badge']),
                      tier: RestageDecoders.enumByName<s4.PlanTier>(
                              s4.PlanTier.values,
                              source,
                              <Object>['highlights', i0, 'value', 'tier']) ??
                          s4.PlanTier.starter)
                  : (throw ArgumentError('PlanBoard.highlights entry value is required.'));
            }
            return m0;
          }()
        : (throw ArgumentError('PlanBoard.highlights is required.')),
  );
}

Widget _buildPricingCard(BuildContext context, DataSource source) {
  return s4.PricingCard(
    plan: source.isMap(<Object>['plan'])
        ? s4.Plan(
            name: source.v<String>(<Object>['plan', 'name']) ??
                (throw ArgumentError('Plan.name is required.')),
            price: source.isMap(<Object>['plan', 'price'])
                ? s4.Price(
                    source.v<int>(<Object>['plan', 'price', 'amount']) ??
                        (throw ArgumentError('Price.amount is required.')),
                    currency: source
                            .v<String>(<Object>['plan', 'price', 'currency']) ??
                        'USD')
                : (throw ArgumentError('Plan.price is required.')),
            badge: source.v<String>(<Object>['plan', 'badge']),
            tier: RestageDecoders.enumByName<s4.PlanTier>(
                    s4.PlanTier.values, source, <Object>['plan', 'tier']) ??
                s4.PlanTier.starter)
        : (throw ArgumentError('PricingCard.plan is required.')),
  );
}

Widget _buildPricingTable(BuildContext context, DataSource source) {
  return s5.PricingTable(
    plans: source.isList(<Object>['plans'])
        ? [
            for (var i0 = 0, n0 = source.length(<Object>['plans']); i0 < n0; i0++)
              source.isMap(<Object>['plans', i0])
                  ? s4.Plan(
                      name: source.v<String>(<Object>['plans', i0, 'name']) ??
                          (throw ArgumentError('Plan.name is required.')),
                      price: source.isMap(<Object>['plans', i0, 'price'])
                          ? s4.Price(
                              source.v<int>(<Object>['plans', i0, 'price', 'amount']) ??
                                  (throw ArgumentError(
                                      'Price.amount is required.')),
                              currency: source.v<String>(<Object>['plans', i0, 'price', 'currency']) ??
                                  'USD')
                          : (throw ArgumentError('Plan.price is required.')),
                      badge: source.v<String>(<Object>['plans', i0, 'badge']),
                      tier: RestageDecoders.enumByName<s4.PlanTier>(
                              s4.PlanTier.values,
                              source,
                              <Object>['plans', i0, 'tier']) ??
                          s4.PlanTier.starter)
                  : (throw ArgumentError('PricingTable.plans element must be an object.'))
          ]
        : (throw ArgumentError('PricingTable.plans is required.')),
  );
}

Widget _buildPromoBadge(BuildContext context, DataSource source) {
  return s6.PromoBadge(
    label: source.v<String>(<Object>['label']) ??
        (throw ArgumentError('PromoBadge.label is required.')),
    color: ArgumentDecoders.color(source, <Object>['color']),
  );
}

Widget _buildPulseBadge(BuildContext context, DataSource source) {
  return s7.PulseBadge(
    label: source.v<String>(<Object>['label']) ??
        (throw ArgumentError('PulseBadge.label is required.')),
    count: source.v<int>(<Object>['count']) ??
        (throw ArgumentError('PulseBadge.count is required.')),
  );
}

Widget _buildSectionHeader(BuildContext context, DataSource source) {
  return s8.SectionHeader(
    heading: source.isMap(<Object>['heading'])
        ? (
            step: source.v<int>(<Object>['heading', 'step']) ??
                (throw ArgumentError(
                    'SectionHeader.heading.step is required.')),
            title: source.v<String>(<Object>['heading', 'title']) ??
                (throw ArgumentError(
                    'SectionHeader.heading.title is required.')),
            tone: RestageDecoders.enumByName<s8.HeaderTone>(
                    s8.HeaderTone.values,
                    source,
                    <Object>['heading', 'tone']) ??
                (throw ArgumentError(
                    'SectionHeader.heading.tone is required.')),
          )
        : (throw ArgumentError('SectionHeader.heading is required.')),
    entry: source.isMap(<Object>['entry'])
        ? s8.SectionEntry(
            label: source.v<String>(<Object>['entry', 'label']) ??
                (throw ArgumentError('SectionEntry.label is required.')),
            meta: source.isMap(<Object>['entry', 'meta'])
                ? (
                    order: source.v<int>(<Object>['entry', 'meta', 'order']) ??
                        (throw ArgumentError(
                            'SectionEntry.meta.order is required.')),
                    pinned:
                        source.v<bool>(<Object>['entry', 'meta', 'pinned']) ??
                            (throw ArgumentError(
                                'SectionEntry.meta.pinned is required.')),
                  )
                : (throw ArgumentError('SectionEntry.meta is required.')))
        : (throw ArgumentError('SectionHeader.entry is required.')),
  );
}

Widget _buildStatBadge(BuildContext context, DataSource source) {
  return s2.StatBadge(
    label: source.v<String>(<Object>['label']) ??
        (throw ArgumentError('StatBadge.label is required.')),
    value: source.v<String>(<Object>['value']) ??
        (throw ArgumentError('StatBadge.value is required.')),
  );
}

Widget _buildStreakBadge(BuildContext context, DataSource source) {
  return s9.StreakBadge(
    label: source.v<String>(<Object>['label']) ??
        (throw ArgumentError('StreakBadge.label is required.')),
    count: source.v<int>(<Object>['count']) ??
        (throw ArgumentError('StreakBadge.count is required.')),
  );
}

Widget _buildTierBoard(BuildContext context, DataSource source) {
  return s10.TierBoard(
    tiers: source.isList(<Object>['tiers'])
        ? [
            for (var i0 = 0, n0 = source.length(<Object>['tiers']);
                i0 < n0;
                i0++)
              source.isMap(<Object>['tiers', i0])
                  ? s10.Tier(
                      name: source.v<String>(<Object>['tiers', i0, 'name']) ??
                          (throw ArgumentError('Tier.name is required.')),
                      features: source.isList(<Object>['tiers', i0, 'features'])
                          ? [
                              for (var i1 = 0,
                                      n1 = source.length(
                                          <Object>['tiers', i0, 'features']);
                                  i1 < n1;
                                  i1++)
                                source.isMap(
                                        <Object>['tiers', i0, 'features', i1])
                                    ? s10.Feature(
                                        label: source.v<String>(<Object>[
                                              'tiers',
                                              i0,
                                              'features',
                                              i1,
                                              'label'
                                            ]) ??
                                            (throw ArgumentError(
                                                'Feature.label is required.')))
                                    : (throw ArgumentError(
                                        'Tier.features element must be an object.'))
                            ]
                          : (throw ArgumentError('Tier.features is required.')))
                  : (throw ArgumentError(
                      'TierBoard.tiers element must be an object.'))
          ]
        : (throw ArgumentError('TierBoard.tiers is required.')),
    bonusTiers: source.isList(<Object>['bonusTiers'])
        ? [
            for (var i0 = 0, n0 = source.length(<Object>['bonusTiers']);
                i0 < n0;
                i0++)
              source.isMap(<Object>['bonusTiers', i0])
                  ? s10.Tier(
                      name: source
                              .v<String>(<Object>['bonusTiers', i0, 'name']) ??
                          (throw ArgumentError('Tier.name is required.')),
                      features: source
                              .isList(<Object>['bonusTiers', i0, 'features'])
                          ? [
                              for (var i1 = 0,
                                      n1 = source.length(<Object>[
                                'bonusTiers',
                                i0,
                                'features'
                              ]);
                                  i1 < n1;
                                  i1++)
                                source.isMap(<Object>[
                                  'bonusTiers',
                                  i0,
                                  'features',
                                  i1
                                ])
                                    ? s10.Feature(
                                        label: source.v<String>(<Object>[
                                              'bonusTiers',
                                              i0,
                                              'features',
                                              i1,
                                              'label'
                                            ]) ??
                                            (throw ArgumentError(
                                                'Feature.label is required.')))
                                    : (throw ArgumentError(
                                        'Tier.features element must be an object.'))
                            ]
                          : (throw ArgumentError('Tier.features is required.')))
                  : (throw ArgumentError(
                      'TierBoard.bonusTiers element must be an object.'))
          ]
        : null,
  );
}
