// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.

import 'package:rfw_catalog_schema/rfw_catalog_schema.dart';

final Catalog kUserCatalog = Catalog(
  schemaVersion: 4,
  generatedAt: '1970-01-01T00:00:00Z',
  libraries: {
    WidgetLibrary.custom('restage_example.widgets'):
        const LibraryInfo(version: '0.0.0'),
  },
  widgets: [
    WidgetEntry(
      wireId: WireId('w0001'),
      name: 'AcmeBorder',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.layout,
      description: 'Wraps a single child in a colored border.',
      flutterType:
          'package:restage_example/widgets/acme_border.dart#AcmeBorder',
      childrenSlot: ChildrenSlot.single,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0001'),
          name: 'child',
          type: PropertyType.widget,
          description: 'Wrapped child widget.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0002'),
          name: 'color',
          type: PropertyType.color,
          description: 'Border color. Defaults to the primary container.',
          defaultBrandToken: 'primary',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0002'),
      name: 'AcmeStack',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.layout,
      description: 'Overlays a list of children in z-order.',
      flutterType: 'package:restage_example/widgets/acme_stack.dart#AcmeStack',
      childrenSlot: ChildrenSlot.list,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0003'),
          name: 'children',
          type: PropertyType.widgetList,
          description: 'Overlay children, top-most last.',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0003'),
      name: 'PromoBadge',
      library: WidgetLibrary.custom('restage_example.widgets'),
      category: WidgetCategory.action,
      description: 'Pill-shaped promotional label.',
      flutterType:
          'package:restage_example/widgets/promo_badge.dart#PromoBadge',
      childrenSlot: ChildrenSlot.none,
      fires: [],
      properties: [
        PropertyEntry(
          wireId: WireId('p0004'),
          name: 'label',
          type: PropertyType.string,
          description: 'Visible label.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0005'),
          name: 'color',
          type: PropertyType.color,
          description: 'Background color. Defaults to the primary container.',
          defaultBrandToken: 'primary',
        ),
      ],
    ),
  ],
);
