/// The screen-id / filename prefix the code generator assigns to a paywall's
/// flow-screen adapter artifact (`paywall_<id>`). It is reserved for
/// paywall-owned flow screens, so it also serves as the ownership signal when a
/// flow embeds a paywall screen alongside its own screens.
const String kPaywallScreenIdPrefix = 'paywall_';

/// Canonical bundle directory for paywall flow-screen adapter blobs and their
/// capability sidecars.
const String kPaywallScreensAssetDir = 'assets/paywalls/screens';

/// The directory paywall flow-screen blobs were emitted to by earlier SDK
/// versions. Retained ONLY as a read-time compatibility fallback so an app with
/// assets generated by an earlier version keeps rendering after an SDK upgrade.
/// Never emit here.
const String kLegacyPaywallScreensAssetDir = 'assets/onboarding/screens';

/// Whether [artifactFilename] (e.g. `paywall_pro.rfw`) is a paywall-owned
/// flow-screen adapter and therefore resolves from [kPaywallScreensAssetDir]
/// (with [kLegacyPaywallScreensAssetDir] as the compatibility fallback),
/// regardless of which flow surface embeds it.
bool isPaywallScreenArtifact(String artifactFilename) =>
    artifactFilename.startsWith(kPaywallScreenIdPrefix);
