// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder map for the 'restage.material' library.
// To change this map: edit lib/registry_curation.dart, then
// re-run build_runner (it regenerates the registry, the
// catalog, and this file).

import 'package:flutter/material.dart';
import 'package:restage_material/src/widgets/restage_draggable_sheet.dart';
import 'package:restage_material/src/widgets/restage_dropdown.dart';
import 'package:restage_material/src/widgets/restage_modal_sheet.dart';
import 'package:restage_material/src/widgets/restage_pager.dart';
import 'package:restage_material/src/widgets/restage_radio_group.dart';
import 'package:restage_material/src/widgets/restage_segmented_button.dart';
import 'package:restage_material/src/widgets/restage_toggle_buttons.dart';
import 'package:restage_core/restage_core.dart';
import 'package:rfw/rfw.dart' hide Switch;

/// One [LocalWidgetBuilder] per widget entry in `lib/registry.dart`,
/// keyed by widget name.
const Map<String, LocalWidgetBuilder> kMaterialLibraryFactories =
    <String, LocalWidgetBuilder>{
  'ActionChip': buildActionChip,
  'AppBar': buildAppBar,
  'Badge': buildBadge,
  'Card': buildCard,
  'CardFilled': buildCardFilled,
  'CardOutlined': buildCardOutlined,
  'Checkbox': buildCheckbox,
  'CheckboxListTile': buildCheckboxListTile,
  'Chip': buildChip,
  'ChoiceChip': buildChoiceChip,
  'CircularProgressIndicator': buildCircularProgressIndicator,
  'Divider': buildDivider,
  'ElevatedButton': buildElevatedButton,
  'ExpansionTile': buildExpansionTile,
  'FilledButton': buildFilledButton,
  'FilledButtonTonal': buildFilledButtonTonal,
  'FilterChip': buildFilterChip,
  'FloatingActionButton': buildFloatingActionButton,
  'Icon': buildIcon,
  'IconButton': buildIconButton,
  'InkWell': buildInkWell,
  'LinearProgressIndicator': buildLinearProgressIndicator,
  'ListTile': buildListTile,
  'MaterialApp': buildMaterialApp,
  'RestageModalSheet': buildRestageModalSheet,
  'RestagePager': buildRestagePager,
  'RestageRadioGroupString': buildRestageRadioGroupString,
  'RestageDropdownString': buildRestageDropdownString,
  'RestageToggleButtons': buildRestageToggleButtons,
  'RestageSegmentedButtonString': buildRestageSegmentedButtonString,
  'RestageDraggableSheet': buildRestageDraggableSheet,
  'OutlinedButton': buildOutlinedButton,
  'OutlinedButtonIcon': buildOutlinedButtonIcon,
  'Scaffold': buildScaffold,
  'Scrollbar': buildScrollbar,
  'Slider': buildSlider,
  'Switch': buildSwitch,
  'SwitchListTile': buildSwitchListTile,
  'TextButton': buildTextButton,
  'TextButtonIcon': buildTextButtonIcon,
  'PreferredSize': buildPreferredSize,
  'DefaultTabController': buildDefaultTabController,
  'TabBar': buildTabBar,
  'Tab': buildTab,
  'TextField': buildTextField,
  'Tooltip': buildTooltip,
};

/// Builds the catalog's `ActionChip` widget from [source].
Widget buildActionChip(BuildContext context, DataSource source) {
  return ActionChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
  );
}

/// Builds the catalog's `AppBar` widget from [source].
Widget buildAppBar(BuildContext context, DataSource source) {
  return AppBar(
    leading: source.optionalChild(<Object>['leading']),
    automaticallyImplyLeading:
        source.v<bool>(<Object>['automaticallyImplyLeading']) ?? true,
    title: source.optionalChild(<Object>['title']),
    actions: source.isList(<Object>['actions'])
        ? source.childList(<Object>['actions'])
        : null,
    bottom: RestageDecoders.optionalPreferredSize(
        source.optionalChild(<Object>['bottom']),
        source.v<double>(<Object>['bottomHeight'])),
    elevation: source.v<double>(<Object>['elevation']),
    scrolledUnderElevation:
        source.v<double>(<Object>['scrolledUnderElevation']),
    shadowColor: ArgumentDecoders.color(source, <Object>['shadowColor']),
    surfaceTintColor:
        ArgumentDecoders.color(source, <Object>['surfaceTintColor']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    foregroundColor:
        ArgumentDecoders.color(source, <Object>['foregroundColor']),
    primary: source.v<bool>(<Object>['primary']) ?? true,
    centerTitle: source.v<bool>(<Object>['centerTitle']) ?? true,
    titleSpacing: source.v<double>(<Object>['titleSpacing']),
    toolbarHeight: source.v<double>(<Object>['toolbarHeight']),
    leadingWidth: source.v<double>(<Object>['leadingWidth']),
    forceMaterialTransparency:
        source.v<bool>(<Object>['forceMaterialTransparency']) ?? false,
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    actionsPadding:
        RestageDecoders.edgeInsets(source, <Object>['actionsPadding']),
  );
}

/// Builds the catalog's `Badge` widget from [source].
Widget buildBadge(BuildContext context, DataSource source) {
  return Badge(
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    textColor: ArgumentDecoders.color(source, <Object>['textColor']),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']),
    offset: RestageDecoders.offset(source, <Object>['offset']),
    label: source.optionalChild(<Object>['label']),
    isLabelVisible: source.v<bool>(<Object>['isLabelVisible']) ?? true,
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `Card` widget from [source].
Widget buildCard(BuildContext context, DataSource source) {
  return Card(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 1.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: RestageDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `CardFilled` widget from [source].
Widget buildCardFilled(BuildContext context, DataSource source) {
  return Card.filled(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: RestageDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `CardOutlined` widget from [source].
Widget buildCardOutlined(BuildContext context, DataSource source) {
  return Card.outlined(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: RestageDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `Checkbox` widget from [source].
Widget buildCheckbox(BuildContext context, DataSource source) {
  return Checkbox(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('Checkbox.value is required.')),
    onChanged: source.handler<ValueChanged<bool?>>(
        <Object>['onChanged'],
        (trigger) =>
            (bool? value) => trigger(<String, Object?>{'value': value})),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
  );
}

/// Builds the catalog's `CheckboxListTile` widget from [source].
Widget buildCheckboxListTile(BuildContext context, DataSource source) {
  return CheckboxListTile(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('CheckboxListTile.value is required.')),
    onChanged: source.handler<ValueChanged<bool?>>(
        <Object>['onChanged'],
        (trigger) =>
            (bool? value) => trigger(<String, Object?>{'value': value})),
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    secondary: source.optionalChild(<Object>['secondary']),
    selected: source.v<bool>(<Object>['selected']) ?? false,
  );
}

/// Builds the catalog's `Chip` widget from [source].
Widget buildChip(BuildContext context, DataSource source) {
  return Chip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
  );
}

/// Builds the catalog's `ChoiceChip` widget from [source].
Widget buildChoiceChip(BuildContext context, DataSource source) {
  return ChoiceChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    onSelected: source.handler<ValueChanged<bool>>(<Object>[
      'onSelected'
    ], (trigger) => (bool value) => trigger(<String, Object?>{'value': value})),
    selected: source.v<bool>(<Object>['selected']) ??
        (throw ArgumentError('ChoiceChip.selected is required.')),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    avatarBorder:
        RestageDecoders.shapeBorder(source, <Object>['avatarBorder']) ??
            const CircleBorder(),
  );
}

/// Builds the catalog's `CircularProgressIndicator` widget from [source].
Widget buildCircularProgressIndicator(BuildContext context, DataSource source) {
  return CircularProgressIndicator(
    value: source.v<double>(<Object>['value']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    strokeWidth: source.v<double>(<Object>['strokeWidth']) ?? 4.0,
  );
}

/// Builds the catalog's `Divider` widget from [source].
Widget buildDivider(BuildContext context, DataSource source) {
  return Divider(
    height: source.v<double>(<Object>['height']) ?? 16.0,
    thickness: source.v<double>(<Object>['thickness']) ?? 1.0,
    color: ArgumentDecoders.color(source, <Object>['color']),
  );
}

/// Builds the catalog's `ElevatedButton` widget from [source].
Widget buildElevatedButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return ElevatedButton(
    style: ElevatedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        elevation: source.v<double>(<Object>['elevation']) ?? 1.0,
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `ExpansionTile` widget from [source].
Widget buildExpansionTile(BuildContext context, DataSource source) {
  return ExpansionTile(
    leading: source.optionalChild(<Object>['leading']),
    title: source.child(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    onExpansionChanged: source.handler<ValueChanged<bool>>(<Object>[
      'onExpansionChanged'
    ], (trigger) => (bool value) => trigger(<String, Object?>{'value': value})),
    trailing: source.optionalChild(<Object>['trailing']),
    initiallyExpanded: source.v<bool>(<Object>['initiallyExpanded']) ?? false,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    collapsedShape:
        RestageDecoders.shapeBorder(source, <Object>['collapsedShape']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    children: source.childList(<Object>['children']),
  );
}

/// Builds the catalog's `FilledButton` widget from [source].
Widget buildFilledButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return FilledButton(
    style: FilledButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `FilledButtonTonal` widget from [source].
Widget buildFilledButtonTonal(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return FilledButton.tonal(
    style: FilledButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `FilterChip` widget from [source].
Widget buildFilterChip(BuildContext context, DataSource source) {
  return FilterChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    selected: source.v<bool>(<Object>['selected']) ?? false,
    onSelected: source.handler<ValueChanged<bool>>(<Object>[
      'onSelected'
    ], (trigger) => (bool value) => trigger(<String, Object?>{'value': value})),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    avatarBorder:
        RestageDecoders.shapeBorder(source, <Object>['avatarBorder']) ??
            const CircleBorder(),
  );
}

/// Builds the catalog's `FloatingActionButton` widget from [source].
Widget buildFloatingActionButton(BuildContext context, DataSource source) {
  return FloatingActionButton(
    tooltip: source.v<String>(<Object>['tooltip']),
    foregroundColor:
        ArgumentDecoders.color(source, <Object>['foregroundColor']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    elevation: source.v<double>(<Object>['elevation']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    mini: source.v<bool>(<Object>['mini']) ?? false,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `Icon` widget from [source].
Widget buildIcon(BuildContext context, DataSource source) {
  return Icon(
    resolveInstalledIcon(
        source.v<int>(<Object>['iconCodepoint']) ??
            (throw ArgumentError('Icon.iconCodepoint is required.')),
        fontFamily:
            source.v<String>(<Object>['iconFontFamily']) ?? 'MaterialIcons',
        matchTextDirection:
            source.v<bool>(<Object>['iconMatchTextDirection']) ?? false),
    size: source.v<double>(<Object>['size']) ??
        resolveThemeBinding(context, path: 'iconTheme.size') as double?,
    color: ArgumentDecoders.color(source, <Object>['color']) ??
        resolveThemeBinding(context, path: 'iconTheme.color') as Color?,
  );
}

/// Builds the catalog's `IconButton` widget from [source].
Widget buildIconButton(BuildContext context, DataSource source) {
  return IconButton(
    iconSize: source.v<double>(<Object>['iconSize']) ?? 24.0,
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    tooltip: source.v<String>(<Object>['tooltip']),
    icon: source.child(<Object>['icon']),
  );
}

/// Builds the catalog's `InkWell` widget from [source].
Widget buildInkWell(BuildContext context, DataSource source) {
  return InkWell(
    onTap: source.voidHandler(<Object>['onTap']),
    customBorder: RestageDecoders.shapeBorder(source, <Object>['customBorder']),
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `LinearProgressIndicator` widget from [source].
Widget buildLinearProgressIndicator(BuildContext context, DataSource source) {
  return LinearProgressIndicator(
    value: source.v<double>(<Object>['value']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    minHeight: source.v<double>(<Object>['minHeight']),
  );
}

/// Builds the catalog's `ListTile` widget from [source].
Widget buildListTile(BuildContext context, DataSource source) {
  return ListTile(
    leading: source.optionalChild(<Object>['leading']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    trailing: source.optionalChild(<Object>['trailing']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    onTap: source.voidHandler(<Object>['onTap']),
  );
}

/// Builds the catalog's `MaterialApp` widget from [source].
Widget buildMaterialApp(BuildContext context, DataSource source) {
  return MaterialApp(
    home: source.optionalChild(<Object>['home']),
    title: source.v<String>(<Object>['title']) ?? '',
  );
}

/// Builds the catalog's `RestageModalSheet` widget from [source].
Widget buildRestageModalSheet(BuildContext context, DataSource source) {
  return RestageModalSheet(
    open: source.v<bool>(<Object>['open']) ??
        (throw ArgumentError('RestageModalSheet.open is required.')),
    isDismissible: source.v<bool>(<Object>['isDismissible']) ?? true,
    enableDrag: source.v<bool>(<Object>['enableDrag']) ?? true,
    showDragHandle: source.v<bool>(<Object>['showDragHandle']),
    dragHandleColor:
        ArgumentDecoders.color(source, <Object>['dragHandleColor']),
    isScrollControlled: source.v<bool>(<Object>['isScrollControlled']) ?? false,
    scrollControlDisabledMaxHeightRatio:
        source.v<double>(<Object>['scrollControlDisabledMaxHeightRatio']) ??
            0.5625,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    elevation: source.v<double>(<Object>['elevation']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    useSafeArea: source.v<bool>(<Object>['useSafeArea']) ?? false,
    barrierColor: ArgumentDecoders.color(source, <Object>['barrierColor']),
    barrierLabel: source.v<String>(<Object>['barrierLabel']),
    anchorPoint: RestageDecoders.offset(source, <Object>['anchorPoint']),
    enterDuration: RestageDecoders.duration(source, <Object>['enterDuration']),
    exitDuration: RestageDecoders.duration(source, <Object>['exitDuration']),
    enterCurve: RestageDecoders.curve(source, <Object>['enterCurve']),
    exitCurve: RestageDecoders.curve(source, <Object>['exitCurve']),
    presentation: RestageDecoders.enumByName<RestageSheetPresentation>(
            RestageSheetPresentation.values,
            source,
            <Object>['presentation']) ??
        RestageSheetPresentation.adaptive,
    underlay: source.optionalChild(<Object>['underlay']),
    onSheetDismissed: source.voidHandler(<Object>['onSheetDismissed']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `RestagePager` widget from [source].
Widget buildRestagePager(BuildContext context, DataSource source) {
  return RestagePager(
    initialPage: source.v<int>(<Object>['initialPage']) ?? 0,
    viewportFraction: source.v<double>(<Object>['viewportFraction']) ?? 1.0,
    scrollDirection: RestageDecoders.enumByName<Axis>(
            Axis.values, source, <Object>['scrollDirection']) ??
        Axis.horizontal,
    pageSnapping: source.v<bool>(<Object>['pageSnapping']) ?? true,
    onPageChanged: source.handler<ValueChanged<int>>(<Object>['onPageChanged'],
        (trigger) => (int value) => trigger(<String, Object?>{'value': value})),
    children: source.childList(<Object>['children']),
  );
}

/// Builds the catalog's `RestageRadioGroupString` widget from [source].
Widget buildRestageRadioGroupString(BuildContext context, DataSource source) {
  return RestageRadioGroup<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError('RestageRadioGroupString.items is required.')),
    selected: source.v<String>(<Object>['selected']),
    onChanged: source.handler<ValueChanged<String?>>(
        <Object>['onChanged'],
        (trigger) =>
            (String? value) => trigger(<String, Object?>{'value': value})),
  );
}

/// Builds the catalog's `RestageDropdownString` widget from [source].
Widget buildRestageDropdownString(BuildContext context, DataSource source) {
  return RestageDropdown<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError('RestageDropdownString.items is required.')),
    selected: source.v<String>(<Object>['selected']),
    onChanged: source.handler<ValueChanged<String?>>(
        <Object>['onChanged'],
        (trigger) =>
            (String? value) => trigger(<String, Object?>{'value': value})),
  );
}

/// Builds the catalog's `RestageToggleButtons` widget from [source].
Widget buildRestageToggleButtons(BuildContext context, DataSource source) {
  return RestageToggleButtons(
    isSelected: RestageDecoders.booleanList(source, <Object>['isSelected']) ??
        (throw ArgumentError('RestageToggleButtons.isSelected is required.')),
    onPressed: source.handler<ValueChanged<int>>(<Object>['onPressed'],
        (trigger) => (int value) => trigger(<String, Object?>{'value': value})),
    children: source.childList(<Object>['children']),
  );
}

/// Builds the catalog's `RestageSegmentedButtonString` widget from [source].
Widget buildRestageSegmentedButtonString(
    BuildContext context, DataSource source) {
  return RestageSegmentedButton<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError(
            'RestageSegmentedButtonString.items is required.')),
    selected: RestageDecoders.stringList(source, <Object>['selected']),
    onChanged: source.handler<ValueChanged<List<String>>>(
        <Object>['onChanged'],
        (trigger) =>
            (List<String> value) => trigger(<String, Object?>{'value': value})),
    multiSelectionEnabled:
        source.v<bool>(<Object>['multiSelectionEnabled']) ?? false,
    emptySelectionAllowed:
        source.v<bool>(<Object>['emptySelectionAllowed']) ?? false,
    showSelectedIcon: source.v<bool>(<Object>['showSelectedIcon']) ?? true,
  );
}

/// Builds the catalog's `RestageDraggableSheet` widget from [source].
Widget buildRestageDraggableSheet(BuildContext context, DataSource source) {
  return RestageDraggableSheet(
    initialChildSize: source.v<double>(<Object>['initialChildSize']) ?? 0.5,
    minChildSize: source.v<double>(<Object>['minChildSize']) ?? 0.25,
    maxChildSize: source.v<double>(<Object>['maxChildSize']) ?? 1.0,
    expand: source.v<bool>(<Object>['expand']) ?? true,
    snap: source.v<bool>(<Object>['snap']) ?? false,
    snapAnimationDuration:
        RestageDecoders.duration(source, <Object>['snapAnimationDuration']),
    expanded: source.v<bool>(<Object>['expanded']) ?? false,
    expandDuration:
        RestageDecoders.duration(source, <Object>['expandDuration']),
    expandCurve: RestageDecoders.curve(source, <Object>['expandCurve']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `OutlinedButton` widget from [source].
Widget buildOutlinedButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return OutlinedButton(
    style: OutlinedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `OutlinedButtonIcon` widget from [source].
Widget buildOutlinedButtonIcon(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return OutlinedButton.icon(
    style: OutlinedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    icon: source.child(<Object>['icon']),
    label: source.child(<Object>['label']),
  );
}

/// Builds the catalog's `Scaffold` widget from [source].
Widget buildScaffold(BuildContext context, DataSource source) {
  return Scaffold(
    appBar: RestageDecoders.optionalPreferredSize(
        source.optionalChild(<Object>['appBar']),
        source.v<double>(<Object>['appBarHeight'])),
    body: source.optionalChild(<Object>['body']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
  );
}

/// Builds the catalog's `Scrollbar` widget from [source].
Widget buildScrollbar(BuildContext context, DataSource source) {
  return Scrollbar(
    thumbVisibility: source.v<bool>(<Object>['thumbVisibility']),
    trackVisibility: source.v<bool>(<Object>['trackVisibility']),
    thickness: source.v<double>(<Object>['thickness']),
    interactive: source.v<bool>(<Object>['interactive']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `Slider` widget from [source].
Widget buildSlider(BuildContext context, DataSource source) {
  return Slider(
    value: source.v<double>(<Object>['value']) ??
        (throw ArgumentError('Slider.value is required.')),
    secondaryTrackValue: source.v<double>(<Object>['secondaryTrackValue']),
    onChanged: source.handler<ValueChanged<double>>(
        <Object>['onChanged'],
        (trigger) =>
            (double value) => trigger(<String, Object?>{'value': value})),
    min: source.v<double>(<Object>['min']) ?? 0.0,
    max: source.v<double>(<Object>['max']) ?? 1.0,
    divisions: source.v<int>(<Object>['divisions']),
    label: source.v<String>(<Object>['label']),
  );
}

/// Builds the catalog's `Switch` widget from [source].
Widget buildSwitch(BuildContext context, DataSource source) {
  return Switch(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('Switch.value is required.')),
    onChanged: source.handler<ValueChanged<bool>>(<Object>[
      'onChanged'
    ], (trigger) => (bool value) => trigger(<String, Object?>{'value': value})),
    activeThumbColor:
        ArgumentDecoders.color(source, <Object>['activeThumbColor']),
  );
}

/// Builds the catalog's `SwitchListTile` widget from [source].
Widget buildSwitchListTile(BuildContext context, DataSource source) {
  return SwitchListTile(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('SwitchListTile.value is required.')),
    onChanged: source.handler<ValueChanged<bool>>(<Object>[
      'onChanged'
    ], (trigger) => (bool value) => trigger(<String, Object?>{'value': value})),
    activeThumbColor:
        ArgumentDecoders.color(source, <Object>['activeThumbColor']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    secondary: source.optionalChild(<Object>['secondary']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
  );
}

/// Builds the catalog's `TextButton` widget from [source].
Widget buildTextButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return TextButton(
    style: TextButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `TextButtonIcon` widget from [source].
Widget buildTextButtonIcon(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return TextButton.icon(
    style: TextButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: RestageDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    icon: source.child(<Object>['icon']),
    label: source.child(<Object>['label']),
  );
}

/// Builds the catalog's `PreferredSize` widget from [source].
Widget buildPreferredSize(BuildContext context, DataSource source) {
  return PreferredSize(
    preferredSize: Size.fromHeight(
        source.v<double>(<Object>['preferredSize']) ??
            (throw ArgumentError('PreferredSize.preferredSize is required.'))),
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `DefaultTabController` widget from [source].
Widget buildDefaultTabController(BuildContext context, DataSource source) {
  return DefaultTabController(
    length: source.v<int>(<Object>['length']) ??
        (throw ArgumentError('DefaultTabController.length is required.')),
    initialIndex: source.v<int>(<Object>['initialIndex']) ?? 0,
    child: source.child(<Object>['child']),
  );
}

/// Builds the catalog's `TabBar` widget from [source].
Widget buildTabBar(BuildContext context, DataSource source) {
  return TabBar(
    tabs: source.childList(<Object>['tabs']),
    isScrollable: source.v<bool>(<Object>['isScrollable']) ?? false,
    indicatorColor: ArgumentDecoders.color(source, <Object>['indicatorColor']),
    labelColor: ArgumentDecoders.color(source, <Object>['labelColor']),
    unselectedLabelColor:
        ArgumentDecoders.color(source, <Object>['unselectedLabelColor']),
    onTap: source.handler<ValueChanged<int>>(<Object>['onTap'],
        (trigger) => (int value) => trigger(<String, Object?>{'value': value})),
  );
}

/// Builds the catalog's `Tab` widget from [source].
Widget buildTab(BuildContext context, DataSource source) {
  return Tab(
    text: source.v<String>(<Object>['text']),
    icon: source.optionalChild(<Object>['icon']),
    iconMargin: RestageDecoders.edgeInsets(source, <Object>['iconMargin']),
    height: source.v<double>(<Object>['height']),
    child: source.optionalChild(<Object>['child']),
  );
}

/// Builds the catalog's `TextField` widget from [source].
Widget buildTextField(BuildContext context, DataSource source) {
  return TextField(
    obscureText: source.v<bool>(<Object>['obscureText']) ?? false,
    maxLines: source.v<int>(<Object>['maxLines']) ?? 1,
    maxLength: source.v<int>(<Object>['maxLength']),
    onChanged: source.handler<ValueChanged<String>>(
        <Object>['onChanged'],
        (trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    onSubmitted: source.handler<ValueChanged<String>>(
        <Object>['onSubmitted'],
        (trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    clipBehavior: RestageDecoders.enumByName<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
  );
}

/// Builds the catalog's `Tooltip` widget from [source].
Widget buildTooltip(BuildContext context, DataSource source) {
  return Tooltip(
    message: source.v<String>(<Object>['message']) ??
        (throw ArgumentError('Tooltip.message is required.')),
    padding: RestageDecoders.edgeInsets(source, <Object>['padding']),
    margin: RestageDecoders.edgeInsets(source, <Object>['margin']),
    preferBelow: source.v<bool>(<Object>['preferBelow']),
    child: source.optionalChild(<Object>['child']),
  );
}
