import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:restage_shared/restage_shared.dart';

import '_support/bundled_artifacts.dart';

/// Pins capability and topology rejection independently on real Stride documents.
void main() {
  // v1 predates stride_goals. Capture generated bytes before a new structural
  // change when advancing this pair; never hand-edit the historical fixture.
  final v1 = FlowDocumentCodec.decodeJson(
    File('test/fixtures/stride_first_run.v1.flow.json').readAsStringSync(),
  );
  final v2 = FlowDocumentCodec.decodeJson(
    readDeliveryText('assets/onboarding/flows/stride_first_run.flow.json'),
  );

  test('the fixtures are the intended general v1 and v2 documents', () {
    expect(v1.deliveryMode, FlowDeliveryMode.general);
    expect(v2.deliveryMode, FlowDeliveryMode.general);
    expect(v1.version, 1);
    expect(v2.version, 2);
    expect(v1.minClient, 1);
    expect(v2.minClient, 6);
    expect(v1.screenArtifacts.containsKey('stride_goals'), isFalse);
    expect(v2.screenArtifacts.containsKey('stride_goals'), isTrue);
  });

  test('the typed active-render gate REJECTS the real v1→v2 raised floor', () {
    final verdict = FlowActiveRenderGate.evaluate(client: v1, active: v2);

    expect(verdict.accepted, isFalse);
    expect(verdict, isA<FlowActiveRenderRejected>());
    expect(
      (verdict as FlowActiveRenderRejected).reason,
      FlowActiveRenderRejectionReason.capabilityFloorRaised,
    );
  });

  test('the typed gate REJECTS the topology at an aligned client floor', () {
    final client = v1.copyWith(minClient: v2.minClient);
    expect(
      FlowDocumentCodec.encodeCanonicalJson(
        client.copyWith(minClient: v1.minClient),
      ),
      FlowDocumentCodec.encodeCanonicalJson(v1),
    );
    final verdict = FlowActiveRenderGate.evaluate(client: client, active: v2);

    expect(verdict.accepted, isFalse);
    expect(verdict, isA<FlowActiveRenderRejected>());
    expect(
      (verdict as FlowActiveRenderRejected).reason,
      FlowActiveRenderRejectionReason.contractSurfaceExpanded,
    );
    expect(
      verdict.blockingChanges.map((change) => (change.code, change.path)),
      containsAll([
        ('screenArtifactAdded', r'$.screenArtifacts.stride_goals'),
        ('stateAdded', r'$.states.stride_goals'),
      ]),
    );
  });

  test('the general render gate ACCEPTS the same structural delta', () {
    // General delivery performs capability admission downstream of this gate.
    final verdict = GeneralFlowRenderGate.evaluate(client: v1, active: v2);

    expect(verdict.accepted, isTrue);
    expect(verdict, isA<FlowActiveRenderAccepted>());
  });
}
