// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
// ignore_for_file: unused_element

import 'package:flutter/widgets.dart';
import 'package:restage_a2ui_example/widgets/cta_button.dart' as p0;
import 'package:restage_a2ui_example/widgets/lessons/callout.dart' as p1;
import 'package:restage_a2ui_example/widgets/lessons/comparison_panel.dart'
    as p2;
import 'package:restage_a2ui_example/widgets/lessons/quiz_check.dart' as p3;
import 'package:restage_a2ui_example/widgets/lessons/section_header.dart' as p4;
import 'package:restage_a2ui_example/widgets/product_card.dart' as p5;
import 'package:restage_a2ui_example/widgets/rating_picker.dart' as p6;
import 'package:genui/genui.dart';
import 'package:json_schema_builder/json_schema_builder.dart';

List<CatalogItem> buildRestageCatalogItems() {
  return <CatalogItem>[
    CatalogItem(
      name: 'Callout',
      dataSchema: S.object(
        description: 'A message callout that wraps an optional child.',
        properties: {
          'message': S.string(
            description: 'The callout message.',
          ),
          'child': S.string(
            description: 'The wrapped child content.',
          )
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['message'],
          builder: (context, message) => p1.Callout(
            message: message ?? '',
            child: _restageA2uiBuildChild(itemContext, data['child']),
          ),
        );
      },
    ),
    CatalogItem(
      name: 'ComparisonPanel',
      dataSchema: S.object(
        description: 'A headed panel that lays out a list of child widgets.',
        properties: {
          'heading': S.string(
            description: 'The panel heading.',
          ),
          'children': S.list(
              description: 'The compared child widgets.', items: S.string())
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['heading'],
          builder: (context, heading) => p2.ComparisonPanel(
            heading: heading ?? '',
            children: _restageA2uiBuildChildren(itemContext, data['children']),
          ),
        );
      },
    ),
    CatalogItem(
      name: 'QuizCheck',
      dataSchema: S.object(
        description:
            'A prompt with a checkable answer bound to a boolean value.',
        properties: {
          'prompt': S.string(
            description: 'The quiz prompt.',
          ),
          'selected': S
              .combined(description: 'Whether the answer is selected.', oneOf: [
            S.boolean(),
            S.object(
                properties: {'path': S.string()}, required: <String>['path']),
            S.object(properties: {
              'call': S.string(),
              'args': S.object(additionalProperties: true)
            }, required: <String>[
              'call'
            ])
          ])
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        final _restageA2uiRef_selected = data['selected'];
        final _restageA2uiPath_selected = (_restageA2uiRef_selected is Map &&
                _restageA2uiRef_selected.containsKey('path'))
            ? _restageA2uiRef_selected['path'] as String
            : '${itemContext.id}.selected';
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['prompt'],
          builder: (context, prompt) => BoundBool(
            dataContext: itemContext.dataContext,
            value: {'path': _restageA2uiPath_selected},
            builder: (context, selected) => p3.QuizCheck(
              prompt: prompt ?? '',
              selected: selected ?? false,
              onSelected: (_restageA2uiNext) => itemContext.dataContext.update(
                  DataPath(_restageA2uiPath_selected), _restageA2uiNext),
            ),
          ),
        );
      },
    ),
    CatalogItem(
      name: 'SectionHeader',
      dataSchema: S.object(
        description: 'A titled section header.',
        properties: {
          'title': S.string(
            description: 'The header title.',
          )
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['title'],
          builder: (context, title) => p4.SectionHeader(
            title: title ?? '',
          ),
        );
      },
    ),
    CatalogItem(
      name: 'CtaButton',
      dataSchema: S.object(
        description: 'A call-to-action button that dispatches a tap event.',
        properties: {
          'label': S.string(
            description: 'The button caption.',
          )
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['label'],
          builder: (context, label) => p0.CtaButton(
            label: label ?? '',
            onPressed: () => itemContext.dispatchEvent(UserActionEvent(
                name: 'onPressed', sourceComponentId: itemContext.id)),
          ),
        );
      },
    ),
    CatalogItem(
      name: 'ProductCard',
      dataSchema: S.object(
        description:
            'Renders a structured product (nested price, tags, features, attributes, size).',
        properties: {
          'product': S.object(
            description: 'The product to display.',
            properties: {
              'name': S.string(),
              'price': S.object(
                properties: {'amount': S.number(), 'currency': S.string()},
                required: <String>['amount', 'currency'],
              ),
              'tags': S.list(items: S.string()),
              'features': S.list(
                  items: S.object(
                properties: {'label': S.string(), 'included': S.boolean()},
                required: <String>['label', 'included'],
              )),
              'attributes': S.object(additionalProperties: S.string()),
              'size': S.object(
                properties: {'height': S.number(), 'width': S.number()},
                required: <String>['height', 'width'],
              )
            },
            required: <String>[
              'name',
              'price',
              'tags',
              'features',
              'attributes',
              'size'
            ],
          )
        },
        required: <String>['product'],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        final _restageA2uiArg_product =
            _restageA2uiBuild_Product(data['product'], 0);
        if (_restageA2uiArg_product == null) return const SizedBox.shrink();
        return p5.ProductCard(
          product: _restageA2uiArg_product,
        );
      },
    ),
    CatalogItem(
      name: 'RatingPicker',
      dataSchema: S.object(
        description: 'A 1–5 star rating control bound to an integer value.',
        properties: {
          'rating': S.combined(
              description: 'The selected rating, 1 through 5.',
              oneOf: [
                S.number(),
                S.object(
                    properties: {'path': S.string()},
                    required: <String>['path']),
                S.object(properties: {
                  'call': S.string(),
                  'args': S.object(additionalProperties: true)
                }, required: <String>[
                  'call'
                ])
              ])
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        final _restageA2uiRef_rating = data['rating'];
        final _restageA2uiPath_rating = (_restageA2uiRef_rating is Map &&
                _restageA2uiRef_rating.containsKey('path'))
            ? _restageA2uiRef_rating['path'] as String
            : '${itemContext.id}.rating';
        return BoundNumber(
          dataContext: itemContext.dataContext,
          value: {'path': _restageA2uiPath_rating},
          builder: (context, rating) => p6.RatingPicker(
            rating: (rating ?? 0).toInt(),
            onRatingChanged: (_restageA2uiNext) => itemContext.dataContext
                .update(DataPath(_restageA2uiPath_rating), _restageA2uiNext),
          ),
        );
      },
    ),
  ];
}

const List<String> _restageA2uiSystemPromptFragments = <String>[
  'Callout: Use for a short highlighted aside around optional content.',
  'ComparisonPanel: A headed panel that lays out a list of child widgets.',
  'QuizCheck: A prompt with a checkable answer bound to a boolean value.',
  'SectionHeader: A titled section header.',
  'CtaButton: A call-to-action button that dispatches a tap event.',
  'ProductCard: Renders a structured product (nested price, tags, features, attributes, size).',
  'RatingPicker: A 1–5 star rating control bound to an integer value.',
];

/// The fully-assembled genui catalog: the generated items
/// plus the system-prompt fragments composed from each
/// widget's usage note (falling back to its description).
Catalog buildRestageCatalog() => Catalog(
      buildRestageCatalogItems(),
      systemPromptFragments: _restageA2uiSystemPromptFragments,
    );

Widget? _restageA2uiBuildChild(
    CatalogItemContext itemContext, Object? childId) {
  if (childId is! String || childId.isEmpty) return null;
  return itemContext.buildChild(childId);
}

List<Widget> _restageA2uiBuildChildren(
    CatalogItemContext itemContext, Object? childIds) {
  if (childIds is! List<Object?>) return const <Widget>[];
  return <Widget>[
    for (final childId in childIds)
      if (_restageA2uiBuildChild(itemContext, childId) != null)
        _restageA2uiBuildChild(itemContext, childId)!,
  ];
}

Color? _restageA2uiColor(String? value) {
  if (value == null || value.isEmpty) return null;
  final normalized = value.startsWith('#')
      ? value.substring(1)
      : value.startsWith(
          '0x',
        )
          ? value.substring(2)
          : value;
  final parsed = int.tryParse(normalized, radix: 16);
  if (parsed == null) return null;
  if (normalized.length <= 6) return Color(0xFF000000 | parsed);
  return Color(parsed);
}

FontWeight _restageA2uiFontWeight(
  num? value,
  FontWeight fallback,
) {
  if (value == null) return fallback;
  final index = value.toInt();
  if (index < 0 || index >= FontWeight.values.length) {
    return fallback;
  }
  return FontWeight.values[index];
}

T? _restageA2uiAs<T>(Object? v) => v is T ? v : null;

Map<String, V>? _restageA2uiMap<V>(Object? raw, V? Function(Object?) coerce) {
  if (raw is! Map) return null;
  final result = <String, V>{};
  for (final entry in raw.entries) {
    final key = entry.key;
    if (key is! String) continue;
    final value = coerce(entry.value);
    if (value == null) continue;
    result[key] = value;
  }
  return result;
}

const int _kA2uiMaxBuildDepth = 64;

p5.Feature? _restageA2uiBuild_Feature(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final label = _restageA2uiAs<String>(_raw['label']);
  if (label == null) return null;
  final included = _restageA2uiAs<bool>(_raw['included']);
  if (included == null) return null;
  return p5.Feature(label: label, included: included);
}

p5.Money? _restageA2uiBuild_Money(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final amount = _restageA2uiAs<num>(_raw['amount'])?.toDouble();
  if (amount == null) return null;
  final currency = _restageA2uiAs<String>(_raw['currency']);
  if (currency == null) return null;
  return p5.Money(amount: amount, currency: currency);
}

p5.Product? _restageA2uiBuild_Product(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final name = _restageA2uiAs<String>(_raw['name']);
  if (name == null) return null;
  final price = _restageA2uiBuild_Money(_raw['price'], _depth + 1);
  if (price == null) return null;
  final tags = _restageA2uiAs<List<Object?>>(_raw['tags'])
      ?.map((e) => _restageA2uiAs<String>(e))
      .whereType<String>()
      .toList();
  if (tags == null) return null;
  final features = _restageA2uiAs<List<Object?>>(_raw['features'])
      ?.map((e) => _restageA2uiBuild_Feature(e, _depth + 1))
      .whereType<p5.Feature>()
      .toList();
  if (features == null) return null;
  final attributes = _restageA2uiMap<String>(
      _raw['attributes'], (v) => _restageA2uiAs<String>(v));
  if (attributes == null) return null;
  final size = _restageA2uiAs<Map<String, Object?>>(_raw['size']) == null
      ? null
      : (
          height: _restageA2uiAs<num>(_restageA2uiAs<Map<String, Object?>>(
                      _raw['size'])?['height'])
                  ?.toDouble() ??
              0.0,
          width: _restageA2uiAs<num>(_restageA2uiAs<Map<String, Object?>>(
                      _raw['size'])?['width'])
                  ?.toDouble() ??
              0.0
        );
  if (size == null) return null;
  return p5.Product(
      name: name,
      price: price,
      tags: tags,
      features: features,
      attributes: attributes,
      size: size);
}
