// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.

import 'package:flutter/widgets.dart';
import 'package:restage_a2ui_example/widgets/cta_button.dart' as p0;
import 'package:restage_a2ui_example/widgets/product_card.dart' as p1;
import 'package:restage_a2ui_example/widgets/rating_picker.dart' as p2;
import 'package:genui/genui.dart';
import 'package:json_schema_builder/json_schema_builder.dart';

List<CatalogItem> buildRestageCatalogItems() {
  return <CatalogItem>[
    CatalogItem(
      name: 'CtaButton',
      dataSchema: S.object(
        properties: {'label': S.string()},
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        return BoundString(
          dataContext: itemContext.dataContext,
          value: data['label'],
          builder: (context, label) => p0.CtaButton(
            label: label ?? '',
            onPressed: () => itemContext.dispatchEvent(UserActionEvent(
                name: 'onPressed', sourceComponentId: itemContext.id)),
          ),
        );
      },
    ),
    CatalogItem(
      name: 'ProductCard',
      dataSchema: S.object(
        properties: {
          'product': S.object(
            properties: {
              'name': S.string(),
              'price': S.object(
                properties: {'amount': S.number(), 'currency': S.string()},
                required: <String>['amount', 'currency'],
              ),
              'tags': S.list(items: S.string()),
              'features': S.list(
                  items: S.object(
                properties: {'label': S.string(), 'included': S.boolean()},
                required: <String>['label', 'included'],
              )),
              'attributes': S.object(additionalProperties: S.string()),
              'size': S.object(
                properties: {'height': S.number(), 'width': S.number()},
                required: <String>['height', 'width'],
              )
            },
            required: <String>[
              'name',
              'price',
              'tags',
              'features',
              'attributes',
              'size'
            ],
          )
        },
        required: <String>['product'],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        final _restageA2uiArg_product =
            _restageA2uiBuild_Product(data['product'], 0);
        if (_restageA2uiArg_product == null) return const SizedBox.shrink();
        return p1.ProductCard(
          product: _restageA2uiArg_product,
        );
      },
    ),
    CatalogItem(
      name: 'RatingPicker',
      dataSchema: S.object(
        properties: {
          'rating': S.combined(oneOf: [
            S.number(),
            S.object(
                properties: {'path': S.string()}, required: <String>['path']),
            S.object(properties: {
              'call': S.string(),
              'args': S.object(additionalProperties: true)
            }, required: <String>[
              'call'
            ])
          ])
        },
        required: <String>[],
      ),
      widgetBuilder: (itemContext) {
        final data = itemContext.data as Map<String, Object?>;
        final _restageA2uiRef_rating = data['rating'];
        final _restageA2uiPath_rating = (_restageA2uiRef_rating is Map &&
                _restageA2uiRef_rating.containsKey('path'))
            ? _restageA2uiRef_rating['path'] as String
            : '${itemContext.id}.rating';
        return BoundNumber(
          dataContext: itemContext.dataContext,
          value: {'path': _restageA2uiPath_rating},
          builder: (context, rating) => p2.RatingPicker(
            rating: (rating ?? 0).toInt(),
            onRatingChanged: (_restageA2uiNext) => itemContext.dataContext
                .update(DataPath(_restageA2uiPath_rating), _restageA2uiNext),
          ),
        );
      },
    ),
  ];
}

Widget? _restageA2uiBuildChild(
    CatalogItemContext itemContext, Object? childId) {
  if (childId is! String || childId.isEmpty) return null;
  return itemContext.buildChild(childId);
}

List<Widget> _restageA2uiBuildChildren(
    CatalogItemContext itemContext, Object? childIds) {
  if (childIds is! List<Object?>) return const <Widget>[];
  return <Widget>[
    for (final childId in childIds)
      if (_restageA2uiBuildChild(itemContext, childId) != null)
        _restageA2uiBuildChild(itemContext, childId)!,
  ];
}

Color? _restageA2uiColor(String? value) {
  if (value == null || value.isEmpty) return null;
  final normalized = value.startsWith('#')
      ? value.substring(1)
      : value.startsWith(
          '0x',
        )
          ? value.substring(2)
          : value;
  final parsed = int.tryParse(normalized, radix: 16);
  if (parsed == null) return null;
  if (normalized.length <= 6) return Color(0xFF000000 | parsed);
  return Color(parsed);
}

FontWeight _restageA2uiFontWeight(
  num? value,
  FontWeight fallback,
) {
  if (value == null) return fallback;
  final index = value.toInt();
  if (index < 0 || index >= FontWeight.values.length) {
    return fallback;
  }
  return FontWeight.values[index];
}

T? _restageA2uiAs<T>(Object? v) => v is T ? v : null;

Map<String, V>? _restageA2uiMap<V>(Object? raw, V? Function(Object?) coerce) {
  if (raw is! Map) return null;
  final result = <String, V>{};
  for (final entry in raw.entries) {
    final key = entry.key;
    if (key is! String) continue;
    final value = coerce(entry.value);
    if (value == null) continue;
    result[key] = value;
  }
  return result;
}

const int _kA2uiMaxBuildDepth = 64;

p1.Feature? _restageA2uiBuild_Feature(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final label = _restageA2uiAs<String>(_raw['label']);
  if (label == null) return null;
  final included = _restageA2uiAs<bool>(_raw['included']);
  if (included == null) return null;
  return p1.Feature(label: label, included: included);
}

p1.Money? _restageA2uiBuild_Money(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final amount = _restageA2uiAs<num>(_raw['amount'])?.toDouble();
  if (amount == null) return null;
  final currency = _restageA2uiAs<String>(_raw['currency']);
  if (currency == null) return null;
  return p1.Money(amount: amount, currency: currency);
}

p1.Product? _restageA2uiBuild_Product(Object? _raw, int _depth) {
  if (_depth > _kA2uiMaxBuildDepth) return null;
  if (_raw is! Map<String, Object?>) return null;
  final name = _restageA2uiAs<String>(_raw['name']);
  if (name == null) return null;
  final price = _restageA2uiBuild_Money(_raw['price'], _depth + 1);
  if (price == null) return null;
  final tags = _restageA2uiAs<List<Object?>>(_raw['tags'])
      ?.map((e) => _restageA2uiAs<String>(e))
      .whereType<String>()
      .toList();
  if (tags == null) return null;
  final features = _restageA2uiAs<List<Object?>>(_raw['features'])
      ?.map((e) => _restageA2uiBuild_Feature(e, _depth + 1))
      .whereType<p1.Feature>()
      .toList();
  if (features == null) return null;
  final attributes = _restageA2uiMap<String>(
      _raw['attributes'], (v) => _restageA2uiAs<String>(v));
  if (attributes == null) return null;
  final size = _restageA2uiAs<Map<String, Object?>>(_raw['size']) == null
      ? null
      : (
          height: _restageA2uiAs<num>(_restageA2uiAs<Map<String, Object?>>(
                      _raw['size'])?['height'])
                  ?.toDouble() ??
              0.0,
          width: _restageA2uiAs<num>(_restageA2uiAs<Map<String, Object?>>(
                      _raw['size'])?['width'])
                  ?.toDouble() ??
              0.0
        );
  if (size == null) return null;
  return p1.Product(
      name: name,
      price: price,
      tags: tags,
      features: features,
      attributes: attributes,
      size: size);
}
