import 'dart:convert';

import 'package:dart_style/dart_style.dart';
import 'package:rfw_catalog_schema/rfw_catalog_schema.dart';

// One formatter per process. Constructing `DartFormatter` is non-trivial
// and the formatter is stateless across calls.
//
// `latestShortStyleLanguageVersion` pins the formatter to the pre-3.7
// "short" style. Generated files land in packages whose pubspec floors
// (`sdk: ^3.5.0`) predate the tall-style cutover, so the workspace
// `dart format` CLI uses the short style for them; matching here keeps
// regenerated output byte-stable against `dart format --set-exit-if-changed`.
final DartFormatter _formatter = DartFormatter(
  languageVersion: DartFormatter.latestShortStyleLanguageVersion,
);

/// Formats [source] with `dart format` rules so emitted code passes
/// `dart format --set-exit-if-changed` byte-stably across runs.
String formatGeneratedDart(String source) => _formatter.format(source);

/// Writes the standard generated-file banner: a `// GENERATED CODE`
/// marker followed by attribution to `restage_codegen`. Callers append
/// any per-emitter comment block, then the imports / declarations.
void writeGeneratedHeader(StringBuffer buf) {
  buf
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by restage_codegen.');
}

/// Appends a stable, machine-readable report of constructor inputs omitted by
/// an emit target.
///
/// The report lives in the generated Dart artifact because A2UI and Widgetbook
/// do not otherwise carry the shared catalog's [PropertyExclusion] sidecar.
/// Empty reports emit nothing, preserving existing generated output byte-for-
/// byte when every constructor input is represented.
void writePropertyExclusionReport(
  StringBuffer buf,
  Iterable<PropertyExclusion> exclusions, {
  String symbolName = r'$RestageExclusions',
}) {
  final sorted = exclusions.toList()
    ..sort((left, right) {
      for (final comparison in [
        left.target.compareTo(right.target),
        left.widget.compareTo(right.widget),
        left.property.compareTo(right.property),
        left.location.compareTo(right.location),
        left.reason.compareTo(right.reason),
      ]) {
        if (comparison != 0) return comparison;
      }
      return 0;
    });
  if (sorted.isEmpty) return;

  buf
    ..writeln()
    ..writeln(
      'const List<Map<String, String>> $symbolName = [',
    );
  for (final exclusion in sorted) {
    buf
      ..writeln('  {')
      ..writeln('    "widget": ${_jsonDartString(exclusion.widget)},')
      ..writeln('    "property": ${_jsonDartString(exclusion.property)},')
      ..writeln('    "target": ${_jsonDartString(exclusion.target)},')
      ..writeln('    "reason": ${_jsonDartString(exclusion.reason)},')
      ..writeln('    "location": ${_jsonDartString(exclusion.location)},')
      ..writeln('  },');
  }
  buf.writeln('];');
}

String _jsonDartString(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');

/// Appends `.0` to a bare integer-literal string so it decodes through rfw's
/// `source.v<double>(...)` strict cast. Handles a leading minus sign; passes
/// through anything that already contains a decimal point or doesn't parse
/// as an integer (data refs, expressions, sentinels). Without this coercion,
/// an author-written `int` literal flowing into a length-typed slot is
/// silently nulled at decode time and the slot falls back to whatever
/// default the decoder supplies — dropping the author's explicit value.
String asDoubleLiteral(String literal) {
  if (literal.contains('.')) return literal;
  final body = literal.startsWith('-') ? literal.substring(1) : literal;
  if (body.isEmpty || int.tryParse(body) == null) return literal;
  return '$literal.0';
}
