// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder map for the 'restage.core' library.
// To change this map: edit lib/registry_curation.dart, then
// re-run build_runner (it regenerates the registry, the
// catalog, and this file).

import 'package:flutter/widgets.dart';
import 'package:restage_core/restage_core.dart';
import 'dart:ui' show ImageFilter;
import 'package:rfw/rfw.dart' hide Switch;

/// One [LocalWidgetBuilder] per widget entry in `lib/registry.dart`,
/// keyed by widget name.
const Map<String, LocalWidgetBuilder> kCoreLibraryFactories =
    <String, LocalWidgetBuilder>{
  'Align': _buildAlign,
  'AnimatedAlign': _buildAnimatedAlign,
  'AnimatedContainer': _buildAnimatedContainer,
  'AnimatedDefaultTextStyle': _buildAnimatedDefaultTextStyle,
  'AnimatedOpacity': _buildAnimatedOpacity,
  'AnimatedPadding': _buildAnimatedPadding,
  'AnimatedPositioned': _buildAnimatedPositioned,
  'AnimatedRotation': _buildAnimatedRotation,
  'AnimatedScale': _buildAnimatedScale,
  'AnimatedSize': _buildAnimatedSize,
  'AnimatedSlide': _buildAnimatedSlide,
  'AspectRatio': _buildAspectRatio,
  'BackdropFilter': _buildBackdropFilter,
  'Center': _buildCenter,
  'ClipOval': _buildClipOval,
  'ClipRRect': _buildClipRRect,
  'ClipRect': _buildClipRect,
  'Column': _buildColumn,
  'Container': _buildContainer,
  'DecoratedBox': _buildDecoratedBox,
  'DefaultTextStyle': _buildDefaultTextStyle,
  'Expanded': _buildExpanded,
  'FadeInImageAssetNetwork': _buildFadeInImageAssetNetwork,
  'FittedBox': _buildFittedBox,
  'Flexible': _buildFlexible,
  'FractionallySizedBox': _buildFractionallySizedBox,
  'GestureDetector': _buildGestureDetector,
  'Image': _buildImage,
  'ImageAsset': _buildImageAsset,
  'IntrinsicHeight': _buildIntrinsicHeight,
  'IntrinsicWidth': _buildIntrinsicWidth,
  'LimitedBox': _buildLimitedBox,
  'ListView': _buildListView,
  'RestageFadeIn': _buildRestageFadeIn,
  'RestageFormattedNumber': _buildRestageFormattedNumber,
  'RestageMotion': _buildRestageMotion,
  'RestagePrice': _buildRestagePrice,
  'RestagePulse': _buildRestagePulse,
  'RestageStagger': _buildRestageStagger,
  'Opacity': _buildOpacity,
  'Padding': _buildPadding,
  'Positioned': _buildPositioned,
  'Row': _buildRow,
  'RotatedBox': _buildRotatedBox,
  'SafeArea': _buildSafeArea,
  'SingleChildScrollView': _buildSingleChildScrollView,
  'SizedBox': _buildSizedBox,
  'Spacer': _buildSpacer,
  'Stack': _buildStack,
  'Text': _buildText,
  'TextRich': _buildTextRich,
  'TransformRotate': _buildTransformRotate,
  'Visibility': _buildVisibility,
  'Wrap': _buildWrap,
};

Widget _buildAlign(BuildContext context, DataSource source) {
  return Align(
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    widthFactor: source.v<double>(<Object>['widthFactor']),
    heightFactor: source.v<double>(<Object>['heightFactor']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedAlign(BuildContext context, DataSource source) {
  return AnimatedAlign(
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    heightFactor: source.v<double>(<Object>['heightFactor']),
    widthFactor: source.v<double>(<Object>['widthFactor']),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedAlign.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedContainer(BuildContext context, DataSource source) {
  return AnimatedContainer(
    decoration: BoxDecoration(
        color: ArgumentDecoders.color(source, <Object>['color']),
        image: RestageDecoders.decorationImage(
            source, <Object>['decorationImage']),
        border: ArgumentDecoders.border(source, <Object>['border']),
        borderRadius: (source.v<double>(<Object>['borderRadiusTopLeft']) ??
                    source.v<double>(<Object>['borderRadiusTopRight']) ??
                    source.v<double>(<Object>['borderRadiusBottomLeft']) ??
                    source.v<double>(<Object>['borderRadiusBottomRight'])) !=
                null
            ? BorderRadius.only(
                topLeft: Radius.circular(
                    source.v<double>(<Object>['borderRadiusTopLeft']) ?? 0.0),
                topRight: Radius.circular(
                    source.v<double>(<Object>['borderRadiusTopRight']) ?? 0.0),
                bottomLeft: Radius.circular(
                    source.v<double>(<Object>['borderRadiusBottomLeft']) ??
                        0.0),
                bottomRight: Radius.circular(source.v<double>(<Object>['borderRadiusBottomRight']) ?? 0.0))
            : (source.v<double>(<Object>['borderRadius']) == null ? null : BorderRadius.circular(source.v<double>(<Object>['borderRadius'])!)),
        boxShadow: ArgumentDecoders.list<BoxShadow>(source, <Object>['boxShadow'], ArgumentDecoders.boxShadow),
        gradient: ArgumentDecoders.gradient(source, <Object>['gradient']),
        shape: ArgumentDecoders.enumValue<BoxShape>(BoxShape.values, source, <Object>['shape']) ?? BoxShape.rectangle),
    constraints: BoxConstraints(
        minWidth: source.v<double>(<Object>['minWidth']) ?? 0.0,
        maxWidth: source.v<double>(<Object>['maxWidth']) ?? double.infinity,
        minHeight: source.v<double>(<Object>['minHeight']) ?? 0.0,
        maxHeight: source.v<double>(<Object>['maxHeight']) ?? double.infinity),
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedContainer.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedDefaultTextStyle(BuildContext context, DataSource source) {
  return AnimatedDefaultTextStyle(
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']),
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
            FontWeight.values, source, <Object>['fontWeight']),
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures:
            RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations:
            RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration:
            RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor:
            ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow']) ?? TextOverflow.clip),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    softWrap: source.v<bool>(<Object>['softWrap']) ?? true,
    maxLines: source.v<int>(<Object>['maxLines']),
    textWidthBasis: ArgumentDecoders.enumValue<TextWidthBasis>(
            TextWidthBasis.values, source, <Object>['textWidthBasis']) ??
        TextWidthBasis.parent,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedDefaultTextStyle.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildAnimatedOpacity(BuildContext context, DataSource source) {
  return AnimatedOpacity(
    opacity: source.v<double>(<Object>['opacity']) ??
        (throw ArgumentError('AnimatedOpacity.opacity is required.')),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedOpacity.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    alwaysIncludeSemantics:
        source.v<bool>(<Object>['alwaysIncludeSemantics']) ?? false,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedPadding(BuildContext context, DataSource source) {
  return AnimatedPadding(
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
        (throw ArgumentError('AnimatedPadding.padding is required.')),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedPadding.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedPositioned(BuildContext context, DataSource source) {
  return AnimatedPositioned(
    left: source.v<double>(<Object>['left']),
    top: source.v<double>(<Object>['top']),
    right: source.v<double>(<Object>['right']),
    bottom: source.v<double>(<Object>['bottom']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedPositioned.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildAnimatedRotation(BuildContext context, DataSource source) {
  return AnimatedRotation(
    turns: source.v<double>(<Object>['turns']) ??
        (throw ArgumentError('AnimatedRotation.turns is required.')),
    alignment: RestageDecoders.alignmentXY(source, <Object>['alignment']) ??
        Alignment.center,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedRotation.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedScale(BuildContext context, DataSource source) {
  return AnimatedScale(
    scale: source.v<double>(<Object>['scale']) ??
        (throw ArgumentError('AnimatedScale.scale is required.')),
    alignment: RestageDecoders.alignmentXY(source, <Object>['alignment']) ??
        Alignment.center,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedScale.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedSize(BuildContext context, DataSource source) {
  return AnimatedSize(
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedSize.duration is required.')),
    reverseDuration:
        RestageDecoders.duration(source, <Object>['reverseDuration']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAnimatedSlide(BuildContext context, DataSource source) {
  return AnimatedSlide(
    offset: RestageDecoders.offset(source, <Object>['offset']) ?? Offset.zero,
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.linear,
    duration: RestageDecoders.duration(source, <Object>['duration']) ??
        (throw ArgumentError('AnimatedSlide.duration is required.')),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildAspectRatio(BuildContext context, DataSource source) {
  return AspectRatio(
    aspectRatio: source.v<double>(<Object>['aspectRatio']) ??
        (throw ArgumentError('AspectRatio.aspectRatio is required.')),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildBackdropFilter(BuildContext context, DataSource source) {
  return BackdropFilter(
    filter: ImageFilter.blur(
        sigmaX: (source.v<double>(<Object>['blurSigmaX']) ?? 0.0),
        sigmaY: (source.v<double>(<Object>['blurSigmaY']) ?? 0.0)),
    blendMode: ArgumentDecoders.enumValue<BlendMode>(
            BlendMode.values, source, <Object>['blendMode']) ??
        BlendMode.srcOver,
    enabled: source.v<bool>(<Object>['enabled']) ?? true,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildCenter(BuildContext context, DataSource source) {
  return Center(
    widthFactor: source.v<double>(<Object>['widthFactor']),
    heightFactor: source.v<double>(<Object>['heightFactor']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildClipOval(BuildContext context, DataSource source) {
  return ClipOval(
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.antiAlias,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildClipRRect(BuildContext context, DataSource source) {
  return ClipRRect(
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.antiAlias,
    borderRadius: (source.v<double>(<Object>['borderRadiusTopLeft']) ??
                source.v<double>(<Object>['borderRadiusTopRight']) ??
                source.v<double>(<Object>['borderRadiusBottomLeft']) ??
                source.v<double>(<Object>['borderRadiusBottomRight'])) !=
            null
        ? BorderRadius.only(
            topLeft: Radius.circular(
                source.v<double>(<Object>['borderRadiusTopLeft']) ?? 0.0),
            topRight: Radius.circular(
                source.v<double>(<Object>['borderRadiusTopRight']) ?? 0.0),
            bottomLeft: Radius.circular(
                source.v<double>(<Object>['borderRadiusBottomLeft']) ?? 0.0),
            bottomRight: Radius.circular(
                source.v<double>(<Object>['borderRadiusBottomRight']) ?? 0.0))
        : (BorderRadius.circular(
            source.v<double>(<Object>['borderRadius']) ?? 0.0)),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildClipRect(BuildContext context, DataSource source) {
  return ClipRect(
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildColumn(BuildContext context, DataSource source) {
  return Column(
    mainAxisAlignment: ArgumentDecoders.enumValue<MainAxisAlignment>(
            MainAxisAlignment.values, source, <Object>['mainAxisAlignment']) ??
        MainAxisAlignment.start,
    mainAxisSize: ArgumentDecoders.enumValue<MainAxisSize>(
            MainAxisSize.values, source, <Object>['mainAxisSize']) ??
        MainAxisSize.max,
    crossAxisAlignment: ArgumentDecoders.enumValue<CrossAxisAlignment>(
            CrossAxisAlignment.values,
            source,
            <Object>['crossAxisAlignment']) ??
        CrossAxisAlignment.center,
    spacing: source.v<double>(<Object>['spacing']) ?? 0.0,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildContainer(BuildContext context, DataSource source) {
  return Container(
    decoration: BoxDecoration(
        color: ArgumentDecoders.color(source, <Object>['color']),
        image: RestageDecoders.decorationImage(
            source, <Object>['decorationImage']),
        border: ArgumentDecoders.border(source, <Object>['border']),
        borderRadius: (source.v<double>(<Object>['borderRadiusTopLeft']) ??
                    source.v<double>(<Object>['borderRadiusTopRight']) ??
                    source.v<double>(<Object>['borderRadiusBottomLeft']) ??
                    source.v<double>(<Object>['borderRadiusBottomRight'])) !=
                null
            ? BorderRadius.only(
                topLeft: Radius.circular(
                    source.v<double>(<Object>['borderRadiusTopLeft']) ?? 0.0),
                topRight: Radius.circular(
                    source.v<double>(<Object>['borderRadiusTopRight']) ?? 0.0),
                bottomLeft: Radius.circular(
                    source.v<double>(<Object>['borderRadiusBottomLeft']) ??
                        0.0),
                bottomRight: Radius.circular(source.v<double>(<Object>['borderRadiusBottomRight']) ?? 0.0))
            : (source.v<double>(<Object>['borderRadius']) == null ? null : BorderRadius.circular(source.v<double>(<Object>['borderRadius'])!)),
        boxShadow: ArgumentDecoders.list<BoxShadow>(source, <Object>['boxShadow'], ArgumentDecoders.boxShadow),
        gradient: ArgumentDecoders.gradient(source, <Object>['gradient']),
        shape: ArgumentDecoders.enumValue<BoxShape>(BoxShape.values, source, <Object>['shape']) ?? BoxShape.rectangle),
    constraints: BoxConstraints(
        minWidth: source.v<double>(<Object>['minWidth']) ?? 0.0,
        maxWidth: source.v<double>(<Object>['maxWidth']) ?? double.infinity,
        minHeight: source.v<double>(<Object>['minHeight']) ?? 0.0,
        maxHeight: source.v<double>(<Object>['maxHeight']) ?? double.infinity),
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildDecoratedBox(BuildContext context, DataSource source) {
  return DecoratedBox(
    decoration:
        BoxDecoration(color: ArgumentDecoders.color(source, <Object>['color'])),
    position: ArgumentDecoders.enumValue<DecorationPosition>(
            DecorationPosition.values, source, <Object>['position']) ??
        DecorationPosition.background,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildDefaultTextStyle(BuildContext context, DataSource source) {
  return DefaultTextStyle(
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']),
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
            FontWeight.values, source, <Object>['fontWeight']),
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures:
            RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations:
            RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration:
            RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor:
            ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow']) ?? TextOverflow.clip),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    softWrap: source.v<bool>(<Object>['softWrap']) ?? true,
    maxLines: source.v<int>(<Object>['maxLines']),
    textWidthBasis: ArgumentDecoders.enumValue<TextWidthBasis>(
            TextWidthBasis.values, source, <Object>['textWidthBasis']) ??
        TextWidthBasis.parent,
    child: source.child(<Object>['child']),
  );
}

Widget _buildExpanded(BuildContext context, DataSource source) {
  return Expanded(
    flex: source.v<int>(<Object>['flex']) ?? 1,
    child: source.child(<Object>['child']),
  );
}

Widget _buildFadeInImageAssetNetwork(BuildContext context, DataSource source) {
  return FadeInImage.assetNetwork(
    placeholder: source.v<String>(<Object>['placeholder']) ??
        (throw ArgumentError(
            'FadeInImageAssetNetwork.placeholder is required.')),
    image: source.v<String>(<Object>['image']) ??
        (throw ArgumentError('FadeInImageAssetNetwork.image is required.')),
    imageScale: source.v<double>(<Object>['imageScale']) ?? 1.0,
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    fit: ArgumentDecoders.enumValue<BoxFit>(
        BoxFit.values, source, <Object>['fit']),
    placeholderFit: ArgumentDecoders.enumValue<BoxFit>(
        BoxFit.values, source, <Object>['placeholderFit']),
    placeholderFilterQuality: ArgumentDecoders.enumValue<FilterQuality>(
        FilterQuality.values, source, <Object>['placeholderFilterQuality']),
  );
}

Widget _buildFittedBox(BuildContext context, DataSource source) {
  return FittedBox(
    fit: ArgumentDecoders.enumValue<BoxFit>(
            BoxFit.values, source, <Object>['fit']) ??
        BoxFit.contain,
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildFlexible(BuildContext context, DataSource source) {
  return Flexible(
    flex: source.v<int>(<Object>['flex']) ?? 1,
    fit: ArgumentDecoders.enumValue<FlexFit>(
            FlexFit.values, source, <Object>['fit']) ??
        FlexFit.loose,
    child: source.child(<Object>['child']),
  );
}

Widget _buildFractionallySizedBox(BuildContext context, DataSource source) {
  return FractionallySizedBox(
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    widthFactor: source.v<double>(<Object>['widthFactor']),
    heightFactor: source.v<double>(<Object>['heightFactor']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildGestureDetector(BuildContext context, DataSource source) {
  return GestureDetector(
    onTap: source.voidHandler(<Object>['onTap']),
    onDoubleTap: source.voidHandler(<Object>['onDoubleTap']),
    onLongPress: source.voidHandler(<Object>['onLongPress']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildImage(BuildContext context, DataSource source) {
  return Image.network(
    source.v<String>(<Object>['url']) ??
        (throw ArgumentError('Image.url is required.')),
    semanticLabel: source.v<String>(<Object>['semanticLabel']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    colorBlendMode: ArgumentDecoders.enumValue<BlendMode>(
        BlendMode.values, source, <Object>['colorBlendMode']),
    fit: ArgumentDecoders.enumValue<BoxFit>(
        BoxFit.values, source, <Object>['fit']),
    alignment: RestageDecoders.alignmentXY(source, <Object>['alignment']) ??
        Alignment.center,
    repeat: ArgumentDecoders.enumValue<ImageRepeat>(
            ImageRepeat.values, source, <Object>['repeat']) ??
        ImageRepeat.noRepeat,
    filterQuality: ArgumentDecoders.enumValue<FilterQuality>(
            FilterQuality.values, source, <Object>['filterQuality']) ??
        FilterQuality.medium,
  );
}

Widget _buildImageAsset(BuildContext context, DataSource source) {
  return Image.asset(
    source.v<String>(<Object>['name']) ??
        (throw ArgumentError('ImageAsset.name is required.')),
    semanticLabel: source.v<String>(<Object>['semanticLabel']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    colorBlendMode: ArgumentDecoders.enumValue<BlendMode>(
        BlendMode.values, source, <Object>['colorBlendMode']),
    fit: ArgumentDecoders.enumValue<BoxFit>(
        BoxFit.values, source, <Object>['fit']),
    alignment: RestageDecoders.alignmentXY(source, <Object>['alignment']) ??
        Alignment.center,
    repeat: ArgumentDecoders.enumValue<ImageRepeat>(
            ImageRepeat.values, source, <Object>['repeat']) ??
        ImageRepeat.noRepeat,
    filterQuality: ArgumentDecoders.enumValue<FilterQuality>(
            FilterQuality.values, source, <Object>['filterQuality']) ??
        FilterQuality.medium,
  );
}

Widget _buildIntrinsicHeight(BuildContext context, DataSource source) {
  return IntrinsicHeight(
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildIntrinsicWidth(BuildContext context, DataSource source) {
  return IntrinsicWidth(
    stepWidth: source.v<double>(<Object>['stepWidth']),
    stepHeight: source.v<double>(<Object>['stepHeight']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildLimitedBox(BuildContext context, DataSource source) {
  return LimitedBox(
    maxWidth: source.v<double>(<Object>['maxWidth']) ??
        (throw ArgumentError('LimitedBox.maxWidth is required.')),
    maxHeight: source.v<double>(<Object>['maxHeight']) ??
        (throw ArgumentError('LimitedBox.maxHeight is required.')),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildListView(BuildContext context, DataSource source) {
  return ListView(
    scrollDirection: ArgumentDecoders.enumValue<Axis>(
            Axis.values, source, <Object>['scrollDirection']) ??
        Axis.vertical,
    reverse: source.v<bool>(<Object>['reverse']) ?? false,
    shrinkWrap: source.v<bool>(<Object>['shrinkWrap']) ?? false,
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    keyboardDismissBehavior:
        ArgumentDecoders.enumValue<ScrollViewKeyboardDismissBehavior>(
            ScrollViewKeyboardDismissBehavior.values,
            source,
            <Object>['keyboardDismissBehavior']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildRestageFadeIn(BuildContext context, DataSource source) {
  return RestageFadeIn(
    duration: RestageDecoders.duration(source, <Object>['duration']),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.easeOut,
    fromOpacity: source.v<double>(<Object>['fromOpacity']) ?? 0.0,
    fromOffset:
        RestageDecoders.offset(source, <Object>['fromOffset']) ?? Offset.zero,
    delay: RestageDecoders.duration(source, <Object>['delay']),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildRestageFormattedNumber(BuildContext context, DataSource source) {
  return RestageFormattedNumber(
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']),
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
            FontWeight.values, source, <Object>['fontWeight']),
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures:
            RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations:
            RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration:
            RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor:
            ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow'])),
    value: source.v<double>(<Object>['value']),
    numberLocale: source.v<String>(<Object>['numberLocale']),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    maxLines: source.v<int>(<Object>['maxLines']),
  );
}

Widget _buildRestageMotion(BuildContext context, DataSource source) {
  return RestageMotion(
    spring: ArgumentDecoders.enumValue<RestageSpring>(
            RestageSpring.values, source, <Object>['spring']) ??
        RestageSpring.smooth,
    duration: RestageDecoders.duration(source, <Object>['duration']),
    bounce: source.v<double>(<Object>['bounce']),
    fromScale: source.v<double>(<Object>['fromScale']) ?? 1.0,
    fromOpacity: source.v<double>(<Object>['fromOpacity']) ?? 1.0,
    fromOffset:
        RestageDecoders.offset(source, <Object>['fromOffset']) ?? Offset.zero,
    delay: RestageDecoders.duration(source, <Object>['delay']),
    onEnd: source.voidHandler(<Object>['onEnd']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildRestagePrice(BuildContext context, DataSource source) {
  return RestagePrice(
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']),
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
            FontWeight.values, source, <Object>['fontWeight']),
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures:
            RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations:
            RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration:
            RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor:
            ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow'])),
    value: source.v<double>(<Object>['value']),
    numberLocale: source.v<String>(<Object>['numberLocale']),
    symbol: source.v<String>(<Object>['symbol']),
    decimalDigits: source.v<int>(<Object>['decimalDigits']),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    maxLines: source.v<int>(<Object>['maxLines']),
  );
}

Widget _buildRestagePulse(BuildContext context, DataSource source) {
  return RestagePulse(
    minScale: source.v<double>(<Object>['minScale']) ?? 0.97,
    maxScale: source.v<double>(<Object>['maxScale']) ?? 1.03,
    period: RestageDecoders.duration(source, <Object>['period']),
    curve: RestageDecoders.curve(source, <Object>['curve']) ?? Curves.easeInOut,
    child: source.child(<Object>['child']),
  );
}

Widget _buildRestageStagger(BuildContext context, DataSource source) {
  return RestageStagger(
    delayBetween: RestageDecoders.duration(source, <Object>['delayBetween']),
    spring: ArgumentDecoders.enumValue<RestageSpring>(
            RestageSpring.values, source, <Object>['spring']) ??
        RestageSpring.smooth,
    fromOffset:
        RestageDecoders.offset(source, <Object>['fromOffset']) ?? Offset.zero,
    fromOpacity: source.v<double>(<Object>['fromOpacity']) ?? 0.0,
    fromScale: source.v<double>(<Object>['fromScale']) ?? 1.0,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildOpacity(BuildContext context, DataSource source) {
  return Opacity(
    opacity: source.v<double>(<Object>['opacity']) ??
        (throw ArgumentError('Opacity.opacity is required.')),
    alwaysIncludeSemantics:
        source.v<bool>(<Object>['alwaysIncludeSemantics']) ?? false,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildPadding(BuildContext context, DataSource source) {
  return Padding(
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
        (throw ArgumentError('Padding.padding is required.')),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildPositioned(BuildContext context, DataSource source) {
  return Positioned(
    left: source.v<double>(<Object>['left']),
    top: source.v<double>(<Object>['top']),
    right: source.v<double>(<Object>['right']),
    bottom: source.v<double>(<Object>['bottom']),
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildRow(BuildContext context, DataSource source) {
  return Row(
    mainAxisAlignment: ArgumentDecoders.enumValue<MainAxisAlignment>(
            MainAxisAlignment.values, source, <Object>['mainAxisAlignment']) ??
        MainAxisAlignment.start,
    mainAxisSize: ArgumentDecoders.enumValue<MainAxisSize>(
            MainAxisSize.values, source, <Object>['mainAxisSize']) ??
        MainAxisSize.max,
    crossAxisAlignment: ArgumentDecoders.enumValue<CrossAxisAlignment>(
            CrossAxisAlignment.values,
            source,
            <Object>['crossAxisAlignment']) ??
        CrossAxisAlignment.center,
    spacing: source.v<double>(<Object>['spacing']) ?? 0.0,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildRotatedBox(BuildContext context, DataSource source) {
  return RotatedBox(
    quarterTurns: source.v<int>(<Object>['quarterTurns']) ??
        (throw ArgumentError('RotatedBox.quarterTurns is required.')),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildSafeArea(BuildContext context, DataSource source) {
  return SafeArea(
    left: source.v<bool>(<Object>['left']) ?? true,
    top: source.v<bool>(<Object>['top']) ?? true,
    right: source.v<bool>(<Object>['right']) ?? true,
    bottom: source.v<bool>(<Object>['bottom']) ?? true,
    maintainBottomViewPadding:
        source.v<bool>(<Object>['maintainBottomViewPadding']) ?? false,
    child: source.child(<Object>['child']),
  );
}

Widget _buildSingleChildScrollView(BuildContext context, DataSource source) {
  return SingleChildScrollView(
    scrollDirection: ArgumentDecoders.enumValue<Axis>(
            Axis.values, source, <Object>['scrollDirection']) ??
        Axis.vertical,
    reverse: source.v<bool>(<Object>['reverse']) ?? false,
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    keyboardDismissBehavior:
        ArgumentDecoders.enumValue<ScrollViewKeyboardDismissBehavior>(
            ScrollViewKeyboardDismissBehavior.values,
            source,
            <Object>['keyboardDismissBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildSizedBox(BuildContext context, DataSource source) {
  return SizedBox(
    width: source.v<double>(<Object>['width']),
    height: source.v<double>(<Object>['height']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildSpacer(BuildContext context, DataSource source) {
  return Spacer(
    flex: source.v<int>(<Object>['flex']) ?? 1,
  );
}

Widget _buildStack(BuildContext context, DataSource source) {
  return Stack(
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.topStart,
    fit: ArgumentDecoders.enumValue<StackFit>(
            StackFit.values, source, <Object>['fit']) ??
        StackFit.loose,
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
    children: source.childList(<Object>['children']),
  );
}

Widget _buildText(BuildContext context, DataSource source) {
  return Text(
    source.v<String>(<Object>['text']) ??
        (throw ArgumentError('Text.text is required.')),
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']) ??
            resolveThemeBinding(context, path: 'defaultTextStyle.fontSize')
                as double?,
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
                FontWeight.values, source, <Object>['fontWeight']) ??
            resolveThemeBinding(context, path: 'defaultTextStyle.fontWeight')
                as FontWeight?,
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures: RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations: RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration: RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor: ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow'])),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    softWrap: source.v<bool>(<Object>['softWrap']),
    maxLines: source.v<int>(<Object>['maxLines']),
    semanticsLabel: source.v<String>(<Object>['semanticsLabel']),
    textWidthBasis: ArgumentDecoders.enumValue<TextWidthBasis>(
        TextWidthBasis.values, source, <Object>['textWidthBasis']),
  );
}

Widget _buildTextRich(BuildContext context, DataSource source) {
  return Text.rich(
    RestageDecoders.inlineSpan(source, <Object>['textSpan']) ??
        (throw ArgumentError('TextRich.textSpan is required.')),
    style: TextStyle(
        inherit: source.v<bool>(<Object>['inherit']) ?? true,
        color: ArgumentDecoders.color(source, <Object>['color']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        fontSize: source.v<double>(<Object>['fontSize']) ??
            resolveThemeBinding(context, path: 'defaultTextStyle.fontSize')
                as double?,
        fontWeight: ArgumentDecoders.enumValue<FontWeight>(
                FontWeight.values, source, <Object>['fontWeight']) ??
            resolveThemeBinding(context, path: 'defaultTextStyle.fontWeight')
                as FontWeight?,
        fontStyle: ArgumentDecoders.enumValue<FontStyle>(
            FontStyle.values, source, <Object>['fontStyle']),
        letterSpacing: source.v<double>(<Object>['letterSpacing']),
        wordSpacing: source.v<double>(<Object>['wordSpacing']),
        textBaseline: ArgumentDecoders.enumValue<TextBaseline>(
            TextBaseline.values, source, <Object>['textBaseline']),
        height: source.v<double>(<Object>['height']),
        leadingDistribution: ArgumentDecoders.enumValue<TextLeadingDistribution>(
            TextLeadingDistribution.values,
            source,
            <Object>['leadingDistribution']),
        locale: ArgumentDecoders.locale(source, <Object>['locale']),
        foreground: ArgumentDecoders.paint(source, <Object>['foreground']),
        background: ArgumentDecoders.paint(source, <Object>['background']),
        shadows: RestageDecoders.shadows(source, <Object>['shadows']),
        fontFeatures: RestageDecoders.fontFeatures(source, <Object>['fontFeatures']),
        fontVariations: RestageDecoders.fontVariations(source, <Object>['fontVariations']),
        decoration: RestageDecoders.textDecoration(source, <Object>['decoration']),
        decorationColor: ArgumentDecoders.color(source, <Object>['decorationColor']),
        decorationStyle: ArgumentDecoders.enumValue<TextDecorationStyle>(TextDecorationStyle.values, source, <Object>['decorationStyle']),
        decorationThickness: source.v<double>(<Object>['decorationThickness']),
        debugLabel: source.v<String>(<Object>['debugLabel']),
        fontFamily: source.v<String>(<Object>['fontFamily']),
        fontFamilyFallback: RestageDecoders.stringList(source, <Object>['fontFamilyFallback']),
        package: source.v<String>(<Object>['fontPackage']),
        overflow: ArgumentDecoders.enumValue<TextOverflow>(TextOverflow.values, source, <Object>['overflow'])),
    textAlign: ArgumentDecoders.enumValue<TextAlign>(
        TextAlign.values, source, <Object>['textAlign']),
    softWrap: source.v<bool>(<Object>['softWrap']),
    maxLines: source.v<int>(<Object>['maxLines']),
    semanticsLabel: source.v<String>(<Object>['semanticsLabel']),
    textWidthBasis: ArgumentDecoders.enumValue<TextWidthBasis>(
        TextWidthBasis.values, source, <Object>['textWidthBasis']),
  );
}

Widget _buildTransformRotate(BuildContext context, DataSource source) {
  return Transform.rotate(
    angle: source.v<double>(<Object>['angle']) ??
        (throw ArgumentError('TransformRotate.angle is required.')),
    origin: RestageDecoders.offset(source, <Object>['origin']),
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']) ??
        AlignmentDirectional.center,
    transformHitTests: source.v<bool>(<Object>['transformHitTests']) ?? true,
    filterQuality: ArgumentDecoders.enumValue<FilterQuality>(
        FilterQuality.values, source, <Object>['filterQuality']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildVisibility(BuildContext context, DataSource source) {
  return Visibility(
    visible: source.v<bool>(<Object>['visible']) ?? true,
    maintainFocusability:
        source.v<bool>(<Object>['maintainFocusability']) ?? false,
    child: source.child(<Object>['child']),
  );
}

Widget _buildWrap(BuildContext context, DataSource source) {
  return Wrap(
    direction: ArgumentDecoders.enumValue<Axis>(
            Axis.values, source, <Object>['direction']) ??
        Axis.horizontal,
    alignment: ArgumentDecoders.enumValue<WrapAlignment>(
            WrapAlignment.values, source, <Object>['alignment']) ??
        WrapAlignment.start,
    spacing: source.v<double>(<Object>['spacing']) ?? 0.0,
    runAlignment: ArgumentDecoders.enumValue<WrapAlignment>(
            WrapAlignment.values, source, <Object>['runAlignment']) ??
        WrapAlignment.start,
    runSpacing: source.v<double>(<Object>['runSpacing']) ?? 0.0,
    crossAxisAlignment: ArgumentDecoders.enumValue<WrapCrossAlignment>(
            WrapCrossAlignment.values,
            source,
            <Object>['crossAxisAlignment']) ??
        WrapCrossAlignment.start,
    textDirection: ArgumentDecoders.enumValue<TextDirection>(
        TextDirection.values, source, <Object>['textDirection']),
    verticalDirection: ArgumentDecoders.enumValue<VerticalDirection>(
            VerticalDirection.values, source, <Object>['verticalDirection']) ??
        VerticalDirection.down,
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    children: source.childList(<Object>['children']),
  );
}
