// GENERATED CODE - DO NOT MODIFY BY HAND

// dart format off
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_import, prefer_relative_imports, directives_ordering, unused_element, strict_raw_type
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:widgetbook/widgetbook.dart' as _widgetbook;
import 'package:restage_widgetbook_example/onboarding/screens/restage.generated/opaque_screen_proof.stories.dart' as _restage_widgetbook_example_onboarding_screens_restage_generated_opaque_screen_proof_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/bare_catalog_card.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_bare_catalog_card_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/catalog_showcase.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_catalog_showcase_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/constructor_fidelity_corpus.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_constructor_fidelity_corpus_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/constructor_fidelity_proof.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_constructor_fidelity_proof_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/constructor_positional_corpus.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_constructor_positional_corpus_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/feature_panel.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_feature_panel_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/feature_row.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_feature_row_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/price_badge.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_price_badge_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/required_nullable_widget_proof.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_required_nullable_widget_proof_stories;
import 'package:restage_widgetbook_example/widgets/restage.generated/stat_tile.stories.dart' as _restage_widgetbook_example_widgets_restage_generated_stat_tile_stories;

final components = <_widgetbook.Component>[
  _restage_widgetbook_example_onboarding_screens_restage_generated_opaque_screen_proof_stories.OpaqueScreenProofComponent,
  _restage_widgetbook_example_widgets_restage_generated_bare_catalog_card_stories.BareCatalogCardComponent,
  _restage_widgetbook_example_widgets_restage_generated_catalog_showcase_stories.CatalogShowcaseComponent,
  _restage_widgetbook_example_widgets_restage_generated_constructor_fidelity_corpus_stories.ConstructorFidelityCorpusComponent,
  _restage_widgetbook_example_widgets_restage_generated_constructor_fidelity_proof_stories.ConstructorFidelityProofComponent,
  _restage_widgetbook_example_widgets_restage_generated_constructor_positional_corpus_stories.ConstructorPositionalCorpusComponent,
  _restage_widgetbook_example_widgets_restage_generated_feature_panel_stories.FeaturePanelComponent,
  _restage_widgetbook_example_widgets_restage_generated_feature_row_stories.FeatureRowComponent,
  _restage_widgetbook_example_widgets_restage_generated_price_badge_stories.PriceBadgeComponent,
  _restage_widgetbook_example_widgets_restage_generated_required_nullable_widget_proof_stories.RequiredNullableWidgetProofComponent,
  _restage_widgetbook_example_widgets_restage_generated_stat_tile_stories.StatTileComponent,
];
