// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.

import 'package:rfw_catalog_schema/rfw_catalog_schema.dart';

final Catalog kUserCatalog = Catalog(
  schemaVersion: 5,
  generatedAt: '1970-01-01T00:00:00Z',
  libraries: {
    WidgetLibrary.custom('restage_widgetbook_example.widgets'):
        const LibraryInfo(version: '0.0.0', capabilityVersion: 2),
  },
  widgets: [
    WidgetEntry(
      wireId: WireId('w0009'),
      name: 'BareCatalogCard',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: null,
      description:
          'A root-level customer card using only the ordinary Restage marker.',
      flutterType:
          'package:restage_widgetbook_example/widgets/bare_catalog_card.dart#BareCatalogCard',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0042'),
          name: 'label',
          type: PropertyType.string,
          description: 'Visible card label.',
          defaultSource: LiteralDefault('Bare catalog card'),
          constructorDefault: DartConstScalar('Bare catalog card'),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0005'),
      name: 'CatalogShowcase',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.input,
      description:
          'A customer catalog widget proving one source can feed every enabled target. It combines ordinary scalar state, an enum, callback write-back, native child-bearing inputs, and customer-owned structured data. The independently named `hero`, `details`, and `footer` inputs require no slot annotation.\n\nThe second paragraph is retained in generated property metadata so multi-paragraph Dart documentation is never reduced to its first line.',
      flutterType:
          'package:restage_widgetbook_example/widgets/catalog_showcase.dart#CatalogShowcase',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0009'),
          name: 'title',
          type: PropertyType.string,
          description: 'Visible customer title.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0010'),
          name: 'enabled',
          type: PropertyType.boolean,
          description: 'Whether the customer control is enabled.',
          defaultSource: LiteralDefault(true),
          constructorDefault: DartConstScalar(true),
        ),
        PropertyEntry(
          wireId: WireId('p0011'),
          name: 'status',
          type: PropertyType.enumValue,
          description: 'Current customer state.',
          required: true,
          enumType: 'CatalogShowcaseStatus',
          valueShape: EnumShape(
              propertyType: PropertyType.enumValue,
              enumRef: DartTypeRef(
                  libraryUri:
                      'package:restage_widgetbook_example/widgets/catalog_showcase.dart',
                  symbolName: 'CatalogShowcaseStatus')),
        ),
        PropertyEntry(
          wireId: WireId('p0012'),
          name: 'onChanged',
          type: PropertyType.event,
          description: 'Reports changes to [enabled].',
          required: true,
          callbackSignature: 'ValueChanged<bool>',
        ),
        PropertyEntry(
          wireId: WireId('p0043'),
          name: 'hero',
          type: PropertyType.widget,
          description: 'Customer widget shown before the detail list.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0044'),
          name: 'details',
          type: PropertyType.widgetList,
          description: 'Customer detail widgets shown in source order.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0045'),
          name: 'footer',
          type: PropertyType.widget,
          description: 'Optional customer widget shown after the detail list.',
          constructorNullable: true,
        ),
        PropertyEntry(
          wireId: WireId('p0015'),
          name: 'data',
          type: PropertyType.structured,
          description: 'Customer-owned structured information.',
          required: true,
          structuredRef: WireIdRef(
              library: 'restage_widgetbook_example.widgets',
              wireId: WireId('s0001')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_widgetbook_example.widgets',
                  wireId: WireId('s0001'))),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0008'),
      name: 'ConstructorFidelityCorpus',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.input,
      description:
          'Broad reusable fixture for accepted named constructor shapes.',
      flutterType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart#ConstructorFidelityCorpus',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0025'),
          name: 'value',
          type: PropertyType.string,
          description:
              'Generic value inherited by the concrete customer widget.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0026'),
          name: 'ordinaryLabel',
          type: PropertyType.string,
          description: 'Ordinary one-to-one constructor binding.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0027'),
          name: 'requiredNamed',
          type: PropertyType.string,
          description: 'Required named field formal.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0028'),
          name: 'nullableText',
          type: PropertyType.string,
          description: 'Explicit nullable null default.',
          constructorNullable: true,
          constructorDefault: DartConstNull(),
        ),
        PropertyEntry(
          wireId: WireId('p0029'),
          name: 'nullableSeed',
          type: PropertyType.string,
          description: 'Nullable input with a non-null constructor default.',
          defaultSource: LiteralDefault('nullable-default'),
          constructorNullable: true,
          constructorDefault: DartConstScalar('nullable-default'),
        ),
        PropertyEntry(
          wireId: WireId('p0030'),
          name: 'enabled',
          type: PropertyType.boolean,
          description: 'Scalar constructor default and write-back candidate.',
          defaultSource: LiteralDefault(true),
          constructorDefault: DartConstScalar(true),
        ),
        PropertyEntry(
          wireId: WireId('p0031'),
          name: 'count',
          type: PropertyType.integer,
          description:
              'Integer constructor default and second write-back candidate.',
          defaultSource: LiteralDefault(7),
          constructorDefault: DartConstScalar(7),
        ),
        PropertyEntry(
          wireId: WireId('p0032'),
          name: 'mode',
          type: PropertyType.enumValue,
          description: 'Enum constructor default.',
          enumType: 'ConstructorCorpusMode',
          defaultSource: LiteralDefault('ready'),
          constructorDefault: DartConstReference(
              libraryUri:
                  'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart',
              owner: 'ConstructorCorpusMode',
              member: 'ready'),
          valueShape: EnumShape(
              propertyType: PropertyType.enumValue,
              enumRef: DartTypeRef(
                  libraryUri:
                      'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart',
                  symbolName: 'ConstructorCorpusMode')),
        ),
        PropertyEntry(
          wireId: WireId('p0033'),
          name: 'directColor',
          type: PropertyType.color,
          description: 'Direct const invocation default.',
          constructorDefault: DartConstInvocation(
              type:
                  DartTypeIdentity(libraryUri: 'dart:ui', symbolName: 'Color'),
              constructorName: 'new',
              positional: [DartConstScalar(4279312947)],
              named: []),
        ),
        PropertyEntry(
          wireId: WireId('p0034'),
          name: 'publicColor',
          type: PropertyType.color,
          description: 'Public static constant reference default.',
          constructorDefault: DartConstReference(
              libraryUri:
                  'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart',
              owner: 'ConstructorCorpusDefaults',
              member: 'publicColor'),
        ),
        PropertyEntry(
          wireId: WireId('p0035'),
          name: 'data',
          type: PropertyType.structured,
          description: 'Nested customer-structured default.',
          constructorDefault: DartConstReference(
              libraryUri:
                  'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart',
              owner: 'ConstructorCorpusDefaults',
              member: 'publicData'),
          structuredRef: WireIdRef(
              library: 'restage_widgetbook_example.widgets',
              wireId: WireId('s0002')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_widgetbook_example.widgets',
                  wireId: WireId('s0002'))),
        ),
        PropertyEntry(
          wireId: WireId('p0036'),
          name: 'resetProof',
          type: PropertyType.event,
          description: 'Arbitrarily named zero-argument callback.',
          required: true,
        ),
        PropertyEntry(
          wireId: WireId('p0037'),
          name: 'whenEnabledChanges',
          type: PropertyType.event,
          description: 'Arbitrarily named one-argument boolean callback.',
          required: true,
          callbackSignature: 'ValueChanged<bool>',
        ),
        PropertyEntry(
          wireId: WireId('p0038'),
          name: 'reportCount',
          type: PropertyType.event,
          description: 'Arbitrarily named one-argument integer callback.',
          required: true,
          callbackSignature: 'ValueChanged<int>',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0006'),
      name: 'ConstructorFidelityProof',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.input,
      description:
          'A compact executable proof that all generated targets invoke Dart\'s constructor contract rather than merely emitting source bytes.',
      flutterType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_proof.dart#ConstructorFidelityProof',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0018'),
          name: 'label',
          type: PropertyType.string,
          description: 'Required positional label.',
          required: true,
          positional: true,
        ),
        PropertyEntry(
          wireId: WireId('p0019'),
          name: 'enabled',
          type: PropertyType.boolean,
          description:
              'Optional named value whose omission preserves the Dart default.',
          defaultSource: LiteralDefault(true),
          constructorDefault: DartConstScalar(true),
        ),
        PropertyEntry(
          wireId: WireId('p0020'),
          name: 'optionalText',
          type: PropertyType.string,
          description:
              'Optional text used to distinguish authored values from defaults.',
          defaultSource: LiteralDefault('constructor-default'),
          constructorDefault: DartConstScalar('constructor-default'),
        ),
        PropertyEntry(
          wireId: WireId('p0021'),
          name: 'onChanged',
          type: PropertyType.event,
          description:
              'Arbitrarily named one-argument callback paired with [enabled].',
          required: true,
          callbackSignature: 'ValueChanged<bool>',
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0007'),
      name: 'ConstructorPositionalCorpus',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.layout,
      description: 'Reusable positional-hole fixture.',
      flutterType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart#ConstructorPositionalCorpus',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0022'),
          name: 'requiredLabel',
          type: PropertyType.string,
          description: 'Required positional value.',
          required: true,
          positional: true,
        ),
        PropertyEntry(
          wireId: WireId('p0023'),
          name: 'leading',
          type: PropertyType.string,
          description: 'Earlier optional positional value.',
          positional: true,
          defaultSource: LiteralDefault('leading-default'),
          constructorDefault: DartConstScalar('leading-default'),
        ),
        PropertyEntry(
          wireId: WireId('p0024'),
          name: 'trailing',
          type: PropertyType.string,
          description:
              'Later optional positional value used to prove hole preservation.',
          positional: true,
          defaultSource: LiteralDefault('trailing-default'),
          constructorDefault: DartConstScalar('trailing-default'),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0004'),
      name: 'FeaturePanel',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.layout,
      description:
          'A panel with a customer header and customer content widgets.',
      flutterType:
          'package:restage_widgetbook_example/widgets/feature_panel.dart#FeaturePanel',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0007'),
          name: 'header',
          type: PropertyType.widget,
          description: 'Customer widget shown as the panel header.',
          required: true,
          constructorNullable: true,
        ),
        PropertyEntry(
          wireId: WireId('p0008'),
          name: 'children',
          type: PropertyType.widgetList,
          description: 'Customer widgets shown in the panel body.',
          required: true,
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0001'),
      name: 'FeatureRow',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.layout,
      description: 'A feature-list row: check icon, title, and subtitle.',
      flutterType:
          'package:restage_widgetbook_example/widgets/feature_row.dart#FeatureRow',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0001'),
          name: 'title',
          type: PropertyType.string,
          description: 'Feature title.',
          required: true,
          defaultSource: LiteralDefault('Unlimited projects'),
        ),
        PropertyEntry(
          wireId: WireId('p0002'),
          name: 'subtitle',
          type: PropertyType.string,
          description: 'Supporting line under the title.',
          required: true,
          defaultSource: LiteralDefault('No caps on what you ship.'),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0002'),
      name: 'PriceBadge',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'A compact price pill, e.g. "\$9.99 / mo".',
      flutterType:
          'package:restage_widgetbook_example/widgets/price_badge.dart#PriceBadge',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0003'),
          name: 'price',
          type: PropertyType.string,
          description: 'Formatted price, e.g. "\$9.99".',
          required: true,
          defaultSource: LiteralDefault('\$9.99'),
        ),
        PropertyEntry(
          wireId: WireId('p0004'),
          name: 'period',
          type: PropertyType.string,
          description: 'Billing period suffix, e.g. "mo".',
          required: true,
          defaultSource: LiteralDefault('mo'),
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0010'),
      name: 'RequiredNullableWidgetProof',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.layout,
      description:
          'Executable RFW proof for required nullable and non-nullable widget inputs.',
      flutterType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart#RequiredNullableWidgetProof',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0046'),
          name: 'positionalNullable',
          type: PropertyType.widget,
          description: 'Required positional input that may explicitly be null.',
          required: true,
          positional: true,
          constructorNullable: true,
        ),
        PropertyEntry(
          wireId: WireId('p0047'),
          name: 'positionalControl',
          type: PropertyType.widget,
          description: 'Required non-nullable positional control.',
          required: true,
          positional: true,
        ),
        PropertyEntry(
          wireId: WireId('p0048'),
          name: 'namedNullable',
          type: PropertyType.widget,
          description: 'Required named input that may explicitly be null.',
          required: true,
          constructorNullable: true,
        ),
        PropertyEntry(
          wireId: WireId('p0049'),
          name: 'namedControl',
          type: PropertyType.widget,
          description: 'Required non-nullable named control.',
          required: true,
        ),
      ],
    ),
    WidgetEntry(
      wireId: WireId('w0003'),
      name: 'StatTile',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      category: WidgetCategory.decoration,
      description: 'A labelled value tile, e.g. "Active users" over "1,204".',
      flutterType:
          'package:restage_widgetbook_example/widgets/stat_tile.dart#StatTile',
      childrenSlot: ChildrenSlot.none,
      properties: [
        PropertyEntry(
          wireId: WireId('p0005'),
          name: 'label',
          type: PropertyType.string,
          description: 'Caption text.',
          required: true,
          defaultSource: LiteralDefault('Active users'),
        ),
        PropertyEntry(
          wireId: WireId('p0006'),
          name: 'value',
          type: PropertyType.string,
          description: 'Value text.',
          required: true,
          defaultSource: LiteralDefault('1,204'),
        ),
      ],
    ),
  ],
  structuredTypes: [
    StructuredEntry(
      wireId: WireId('s0001'),
      name: 'CatalogShowcaseData',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      description:
          'Customer-owned structured information displayed by a [CatalogShowcase].',
      sourceType:
          'package:restage_widgetbook_example/widgets/catalog_showcase.dart#CatalogShowcaseData',
      fields: [
        StructuredField(
          wireId: WireId('p0016'),
          name: 'note',
          type: PropertyType.string,
          description: 'Supporting customer text.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
        StructuredField(
          wireId: WireId('p0017'),
          name: 'count',
          type: PropertyType.integer,
          description: 'Customer-owned count.',
          valueShape: ScalarShape(
              propertyType: PropertyType.integer,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'int')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0001'),
          argMappings: {
            'count': ArgMapping(targetFields: [WireId('p0017')]),
            'note': ArgMapping(targetFields: [WireId('p0016')]),
          },
          description: 'Creates customer-owned showcase information.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0002'),
      name: 'ConstructorCorpusData',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      description: 'Customer-owned structured data with one nested object.',
      sourceType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart#ConstructorCorpusData',
      fields: [
        StructuredField(
          wireId: WireId('p0039'),
          name: 'nested',
          type: PropertyType.structured,
          description: 'Nested customer object.',
          structuredRef: WireIdRef(
              library: 'restage_widgetbook_example.widgets',
              wireId: WireId('s0003')),
          valueShape: StructuredShape(
              propertyType: PropertyType.structured,
              structuredRef: WireIdRef(
                  library: 'restage_widgetbook_example.widgets',
                  wireId: WireId('s0003'))),
        ),
        StructuredField(
          wireId: WireId('p0040'),
          name: 'count',
          type: PropertyType.integer,
          description: 'Customer-owned scalar nested beside the object.',
          valueShape: ScalarShape(
              propertyType: PropertyType.integer,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'int')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0002'),
          argMappings: {
            'count': ArgMapping(targetFields: [WireId('p0040')]),
            'nested': ArgMapping(targetFields: [WireId('p0039')]),
          },
          description: 'Creates structured corpus data.',
        ),
      ],
    ),
    StructuredEntry(
      wireId: WireId('s0003'),
      name: 'ConstructorCorpusNestedData',
      library: WidgetLibrary.custom('restage_widgetbook_example.widgets'),
      description: 'Nested customer-owned immutable data.',
      sourceType:
          'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart#ConstructorCorpusNestedData',
      fields: [
        StructuredField(
          wireId: WireId('p0041'),
          name: 'label',
          type: PropertyType.string,
          description: 'Nested label.',
          valueShape: ScalarShape(
              propertyType: PropertyType.string,
              dartTypeRef:
                  DartTypeRef(libraryUri: 'dart:core', symbolName: 'String')),
        ),
      ],
      variants: [
        ConstructorVariant(
          wireId: WireId('v0003'),
          argMappings: {
            'label': ArgMapping(targetFields: [WireId('p0041')]),
          },
          description: 'Creates nested corpus data.',
        ),
      ],
    ),
  ],
  exclusions: [
    PropertyExclusion(
      widget: 'ConstructorFidelityCorpus',
      property: 'focusNode',
      target: 'rfw',
      reason:
          'Unsupported property type FocusNode? on ConstructorFidelityCorpus.focusNode. Supported types: Widget, List<Widget>, Color, EdgeInsets(Geometry|Directional), Alignment(Geometry|Directional), FontWeight, bool, int, double, String, VoidCallback (and similar function types), and any Dart enum. Target: rfw.',
      location:
          'lib/widgets/constructor_fidelity_corpus.dart#ConstructorFidelityCorpus.focusNode',
    ),
  ],
);
