// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder closures for every admitted
// @RestageWidget class in this package, plus a one-call helper
// that registers them with Restage at startup.
//
// Inputs come from public unnamed generative constructors;
// edit the ordinary Flutter constructor, fields, Dartdoc, or
// optional Restage overlays, then re-run build_runner.

import 'package:flutter/widgets.dart';
import 'package:restage_widgetbook_example/widgets/bare_catalog_card.dart'
    as s0;
import 'package:restage_widgetbook_example/widgets/catalog_showcase.dart' as s1;
import 'package:restage_widgetbook_example/widgets/constructor_fidelity_corpus.dart'
    as s2;
import 'package:restage_widgetbook_example/widgets/constructor_fidelity_proof.dart'
    as s3;
import 'package:restage_widgetbook_example/widgets/feature_panel.dart' as s4;
import 'package:restage_widgetbook_example/widgets/feature_row.dart' as s5;
import 'package:restage_widgetbook_example/widgets/price_badge.dart' as s6;
import 'package:restage_widgetbook_example/widgets/stat_tile.dart' as s7;
import 'package:restage/restage.dart';

/// Registers every emittable @RestageWidget-annotated class
/// in this package with Restage. Call once at the app's
/// startup, before any `RestagePaywall` mounts. Idempotent
/// after `Restage.debugReset`, so test setUps may call it
/// again between cases.
void registerRestageCustomerWidgets() {
  Restage.registerWidgetLibrary(
    WidgetLibrary.custom('restage_widgetbook_example.widgets'),
    capabilityVersion: 2,
    widgets: const <RestageWidgetFactory>[
      RestageWidgetFactory(
          name: 'BareCatalogCard', builder: _buildBareCatalogCard),
      RestageWidgetFactory(
          name: 'CatalogShowcase', builder: _buildCatalogShowcase),
      RestageWidgetFactory(
          name: 'ConstructorFidelityCorpus',
          builder: _buildConstructorFidelityCorpus),
      RestageWidgetFactory(
          name: 'ConstructorFidelityProof',
          builder: _buildConstructorFidelityProof),
      RestageWidgetFactory(
          name: 'ConstructorPositionalCorpus',
          builder: _buildConstructorPositionalCorpus),
      RestageWidgetFactory(name: 'FeaturePanel', builder: _buildFeaturePanel),
      RestageWidgetFactory(name: 'FeatureRow', builder: _buildFeatureRow),
      RestageWidgetFactory(name: 'PriceBadge', builder: _buildPriceBadge),
      RestageWidgetFactory(
          name: 'RequiredNullableWidgetProof',
          builder: _buildRequiredNullableWidgetProof),
      RestageWidgetFactory(name: 'StatTile', builder: _buildStatTile),
    ],
  );
}

Widget _buildBareCatalogCard(BuildContext context, DataSource source) {
  final _restagePresenceLabel = RestageRfwConstructorPresence.read(
    source,
    <Object>['label'],
  );

  return Function.apply(
    s0.BareCatalogCard.new,
    <Object?>[],
    <Symbol, Object?>{
      if (_restagePresenceLabel.supplied)
        #label: source.v<String>(_restagePresenceLabel.valuePath),
    },
  ) as Widget;
}

Widget _buildCatalogShowcase(BuildContext context, DataSource source) {
  final _restagePresenceEnabled = RestageRfwConstructorPresence.read(
    source,
    <Object>['enabled'],
  );

  return Function.apply(
    s1.CatalogShowcase.new,
    <Object?>[],
    <Symbol, Object?>{
      #title: source.v<String>(<Object>['title']) ??
          (throw ArgumentError('CatalogShowcase.title is required.')),
      if (_restagePresenceEnabled.supplied)
        #enabled: source.v<bool>(_restagePresenceEnabled.valuePath),
      #status: RestageDecoders.enumByName<s1.CatalogShowcaseStatus>(
              s1.CatalogShowcaseStatus.values, source, <Object>['status']) ??
          (throw ArgumentError('CatalogShowcase.status is required.')),
      #onChanged: source.handler<ValueChanged<bool>>(
              <Object>['onChanged'],
              (trigger) =>
                  (bool value) => trigger(<String, Object?>{'value': value})) ??
          (bool _) {},
      #hero: source.child(<Object>['hero']),
      #details: source.childList(<Object>['details']),
      #footer: source.optionalChild(<Object>['footer']),
      #data: source.isMap(<Object>['data'])
          ? s1.CatalogShowcaseData(
              note: source.v<String>(<Object>['data', 'note']) ??
                  (throw ArgumentError(
                      'CatalogShowcaseData.note is required.')),
              count: source.v<int>(<Object>['data', 'count']) ??
                  (throw ArgumentError(
                      'CatalogShowcaseData.count is required.')))
          : (throw ArgumentError('CatalogShowcase.data is required.')),
    },
  ) as Widget;
}

Widget _buildConstructorFidelityCorpus(
    BuildContext context, DataSource source) {
  final _restagePresenceNullableText = RestageRfwConstructorPresence.read(
    source,
    <Object>['nullableText'],
  );
  final _restagePresenceNullableSeed = RestageRfwConstructorPresence.read(
    source,
    <Object>['nullableSeed'],
  );
  final _restagePresenceEnabled = RestageRfwConstructorPresence.read(
    source,
    <Object>['enabled'],
  );
  final _restagePresenceCount = RestageRfwConstructorPresence.read(
    source,
    <Object>['count'],
  );
  final _restagePresenceMode = RestageRfwConstructorPresence.read(
    source,
    <Object>['mode'],
  );
  final _restagePresenceDirectColor = RestageRfwConstructorPresence.read(
    source,
    <Object>['directColor'],
  );
  final _restagePresencePublicColor = RestageRfwConstructorPresence.read(
    source,
    <Object>['publicColor'],
  );
  final _restagePresenceData = RestageRfwConstructorPresence.read(
    source,
    <Object>['data'],
  );

  return Function.apply(
    s2.ConstructorFidelityCorpus.new,
    <Object?>[],
    <Symbol, Object?>{
      #value: source.v<String>(<Object>['value']) ??
          (throw ArgumentError('ConstructorFidelityCorpus.value is required.')),
      #ordinaryLabel: source.v<String>(<Object>['ordinaryLabel']) ??
          (throw ArgumentError(
              'ConstructorFidelityCorpus.ordinaryLabel is required.')),
      #requiredNamed: source.v<String>(<Object>['requiredNamed']) ??
          (throw ArgumentError(
              'ConstructorFidelityCorpus.requiredNamed is required.')),
      if (_restagePresenceNullableText.supplied)
        #nullableText: source.v<String>(_restagePresenceNullableText.valuePath),
      if (_restagePresenceNullableSeed.supplied)
        #nullableSeed: source.v<String>(_restagePresenceNullableSeed.valuePath),
      if (_restagePresenceEnabled.supplied)
        #enabled: source.v<bool>(_restagePresenceEnabled.valuePath),
      if (_restagePresenceCount.supplied)
        #count: source.v<int>(_restagePresenceCount.valuePath),
      if (_restagePresenceMode.supplied)
        #mode: RestageDecoders.enumByName<s2.ConstructorCorpusMode>(
            s2.ConstructorCorpusMode.values,
            source,
            _restagePresenceMode.valuePath),
      if (_restagePresenceDirectColor.supplied)
        #directColor: ArgumentDecoders.color(
            source, _restagePresenceDirectColor.valuePath),
      if (_restagePresencePublicColor.supplied)
        #publicColor: ArgumentDecoders.color(
            source, _restagePresencePublicColor.valuePath),
      if (_restagePresenceData.supplied)
        #data: _restagePresenceData.hasValue
            ? (source.isMap(<Object>[..._restagePresenceData.valuePath])
                ? s2.ConstructorCorpusData(
                    nested: source.isMap(<Object>[..._restagePresenceData.valuePath, 'nested'])
                        ? s2.ConstructorCorpusNestedData(
                            label: source.v<String>(<Object>[
                                  ..._restagePresenceData.valuePath,
                                  'nested',
                                  'label'
                                ]) ??
                                (throw ArgumentError(
                                    'ConstructorCorpusNestedData.label is required.')))
                        : (throw ArgumentError(
                            'ConstructorCorpusData.nested is required.')),
                    count: source
                            .v<int>(<Object>[..._restagePresenceData.valuePath, 'count']) ??
                        (throw ArgumentError('ConstructorCorpusData.count is required.')))
                : (throw ArgumentError('ConstructorFidelityCorpus.data is required.')))
            : (throw ArgumentError('ConstructorFidelityCorpus.data is required.')),
      #resetProof: source.voidHandler(<Object>['resetProof']) ?? () {},
      #whenEnabledChanges: source.handler<ValueChanged<bool>>(
              <Object>['whenEnabledChanges'],
              (trigger) =>
                  (bool value) => trigger(<String, Object?>{'value': value})) ??
          (bool _) {},
      #reportCount: source.handler<ValueChanged<int>>(
              <Object>['reportCount'],
              (trigger) =>
                  (int value) => trigger(<String, Object?>{'value': value})) ??
          (int _) {},
    },
  ) as Widget;
}

Widget _buildConstructorFidelityProof(BuildContext context, DataSource source) {
  final _restagePresenceEnabled = RestageRfwConstructorPresence.read(
    source,
    <Object>['enabled'],
  );
  final _restagePresenceOptionalText = RestageRfwConstructorPresence.read(
    source,
    <Object>['optionalText'],
  );

  return Function.apply(
    s3.ConstructorFidelityProof.new,
    <Object?>[
      source.v<String>(<Object>['label']) ??
          (throw ArgumentError('ConstructorFidelityProof.label is required.')),
    ],
    <Symbol, Object?>{
      if (_restagePresenceEnabled.supplied)
        #enabled: source.v<bool>(_restagePresenceEnabled.valuePath),
      if (_restagePresenceOptionalText.supplied)
        #optionalText: source.v<String>(_restagePresenceOptionalText.valuePath),
      #onChanged: source.handler<ValueChanged<bool>>(
              <Object>['onChanged'],
              (trigger) =>
                  (bool value) => trigger(<String, Object?>{'value': value})) ??
          (bool _) {},
    },
  ) as Widget;
}

Widget _buildConstructorPositionalCorpus(
    BuildContext context, DataSource source) {
  final _restagePresenceLeading = RestageRfwConstructorPresence.read(
    source,
    <Object>['leading'],
  );
  final _restagePresenceTrailing = RestageRfwConstructorPresence.read(
    source,
    <Object>['trailing'],
  );

  return Function.apply(
    s2.ConstructorPositionalCorpus.new,
    <Object?>[
      source.v<String>(<Object>['requiredLabel']) ??
          (throw ArgumentError(
              'ConstructorPositionalCorpus.requiredLabel is required.')),
      if (_restagePresenceLeading.supplied || _restagePresenceTrailing.supplied)
        _restagePresenceLeading.supplied
            ? (source.v<String>(_restagePresenceLeading.valuePath))
            : 'leading-default',
      if (_restagePresenceTrailing.supplied)
        source.v<String>(_restagePresenceTrailing.valuePath),
    ],
    <Symbol, Object?>{},
  ) as Widget;
}

Widget _buildFeaturePanel(BuildContext context, DataSource source) {
  return s4.FeaturePanel(
    header: source.optionalChild(<Object>['header']),
    children: source.childList(<Object>['children']),
  );
}

Widget _buildFeatureRow(BuildContext context, DataSource source) {
  return s5.FeatureRow(
    title: source.v<String>(<Object>['title']) ?? 'Unlimited projects',
    subtitle:
        source.v<String>(<Object>['subtitle']) ?? 'No caps on what you ship.',
  );
}

Widget _buildPriceBadge(BuildContext context, DataSource source) {
  return s6.PriceBadge(
    price: source.v<String>(<Object>['price']) ?? '\$9.99',
    period: source.v<String>(<Object>['period']) ?? 'mo',
  );
}

Widget _buildRequiredNullableWidgetProof(
    BuildContext context, DataSource source) {
  return s2.RequiredNullableWidgetProof(
    source.optionalChild(<Object>['positionalNullable']),
    source.child(<Object>['positionalControl']),
    namedNullable: source.optionalChild(<Object>['namedNullable']),
    namedControl: source.child(<Object>['namedControl']),
  );
}

Widget _buildStatTile(BuildContext context, DataSource source) {
  return s7.StatTile(
    label: source.v<String>(<Object>['label']) ?? 'Active users',
    value: source.v<String>(<Object>['value']) ?? '1,204',
  );
}
