import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:genui/genui.dart';

import 'generated/interactive_catalog.g.dart';
import 'generated/interactive_fixture.dart';

/// The interactivity proof — the render + drive leg.
///
/// Renders the committed interactive catalog (generated by the production A2UI
/// emitter from the real reflector + the real `@RestageProperty(writeBackValue:)`
/// annotation metadata) against real genui 0.9.2, then DRIVES interaction:
/// tap -> write-back -> re-render (scalar + list), tap -> dispatch (an outward
/// `UserActionEvent` captured), and a multi-control widget round-tripping two
/// DISTINCT data paths (the annotation pairing, no cross-wiring). The write-back
/// pairings are proven with an EXPLICIT producer-supplied `{path}` binding (not
/// the self-scoped fallback, which would mask a mis-pairing).
///
/// A stable [DataContext] + a capturing [DispatchEventCallback] are hoisted out
/// of the builder closure so the data model can be seeded before the pump and
/// inspected after the drive. The `BoundValue` subscribes once; its own
/// `ValueListenableBuilder` re-renders on a data-model change.
Future<void> _pumpInteractive(
  WidgetTester tester, {
  required Catalog catalog,
  required List<CatalogItem> items,
  required String type,
  required Map<String, Object?> data,
  required DataContext dataContext,
  required DispatchEventCallback dispatchEvent,
}) async {
  await tester.pumpWidget(
    MaterialApp(
      home: Builder(
        builder: (context) {
          final itemContext = CatalogItemContext(
            data: data,
            id: 'root',
            type: type,
            buildChild: (childId, [dataContext]) => Text('child-$childId'),
            dispatchEvent: dispatchEvent,
            buildContext: context,
            dataContext: dataContext,
            getComponent: (_) => null,
            getCatalogItem: (t) {
              for (final item in items) {
                if (item.name == t) return item;
              }
              return null;
            },
            surfaceId: 'test-surface',
            reportError: (error, stack) => throw error,
          );
          return catalog.buildWidget(itemContext);
        },
      ),
    ),
  );
}

/// Round-trips [data] through JSON so values arrive in the shape genui delivers
/// from a decoded payload (e.g. a `{path}` binding as `Map<String, dynamic>`).
Map<String, Object?> _asDelivered(Map<String, Object?> data) =>
    jsonDecode(jsonEncode(data)) as Map<String, Object?>;

void main() {
  late List<CatalogItem> items;
  late Catalog catalog;
  late InMemoryDataModel model;
  late DataContext dataContext;
  late List<UiEvent> dispatched;

  setUp(() {
    items = buildRestageCatalogItems();
    catalog = Catalog(items);
    model = InMemoryDataModel();
    dataContext = DataContext(model, DataPath.root);
    dispatched = <UiEvent>[];
  });

  test('the generated interactive catalog exposes the fixture items', () {
    expect(
      items.map((i) => i.name),
      containsAll(<String>[
        'QuickCheck',
        'MultiSelect',
        'ActionButton',
        'Range',
      ]),
    );
  });

  testWidgets('scalar write-back: tap -> write-back -> re-render '
      '(the QuickCheck acceptance bar, explicit {path} binding)', (
    tester,
  ) async {
    // The producer supplies an EXPLICIT `{path}` binding on the value prop —
    // the read+write both target this path, so a mis-pairing cannot pass.
    dataContext.update(DataPath('answer'), 0);
    await _pumpInteractive(
      tester,
      catalog: catalog,
      items: items,
      type: 'QuickCheck',
      data: _asDelivered(const {
        'selected': {'path': 'answer'},
      }),
      dataContext: dataContext,
      dispatchEvent: dispatched.add,
    );
    // The generated catalog constructed the REAL customer widget.
    expect(find.byType(QuickCheckFixture), findsOneWidget);
    expect(find.text('quickcheck-selected:0'), findsOneWidget);

    await tester.tap(find.byKey(const ValueKey('quickcheck-option-2')));
    await tester.pump();

    // The callback wrote 2 back to the bound path -> the BoundNumber re-renders.
    expect(find.text('quickcheck-selected:2'), findsOneWidget);
    expect(dataContext.getValue<num>(DataPath('answer')), 2);
  });

  testWidgets('list write-back: tap -> write-back -> re-render', (
    tester,
  ) async {
    dataContext.update(DataPath('picks'), <String>['a']);
    await _pumpInteractive(
      tester,
      catalog: catalog,
      items: items,
      type: 'MultiSelect',
      data: _asDelivered(const {
        'chosen': {'path': 'picks'},
      }),
      dataContext: dataContext,
      dispatchEvent: dispatched.add,
    );
    expect(find.byType(MultiSelectFixture), findsOneWidget);
    expect(find.text('multiselect-chosen:a'), findsOneWidget);

    await tester.tap(find.byKey(const ValueKey('multiselect-add-b')));
    await tester.pump();

    // The settled list was written back -> the BoundList re-renders.
    expect(find.text('multiselect-chosen:a,b'), findsOneWidget);
    expect(dataContext.getValue<List<Object?>>(DataPath('picks')), <String>[
      'a',
      'b',
    ]);
  });

  testWidgets(
    'dispatch: tap -> a compile-fixed UserActionEvent is dispatched',
    (tester) async {
      await _pumpInteractive(
        tester,
        catalog: catalog,
        items: items,
        type: 'ActionButton',
        data: _asDelivered(const {'label': 'Go'}),
        dataContext: dataContext,
        dispatchEvent: dispatched.add,
      );
      expect(find.byType(ActionButtonFixture), findsOneWidget);
      expect(find.text('actionbutton:Go'), findsOneWidget);
      expect(dispatched, isEmpty);

      await tester.tap(find.byKey(const ValueKey('actionbutton')));
      await tester.pump();

      expect(dispatched, hasLength(1));
      final action = UserActionEvent.fromMap(dispatched.single.toMap());
      // The event name is COMPILE-FIXED from the callback property name (the
      // producer cannot repoint it), with the source component id.
      expect(action.name, 'onPressed');
      expect(action.sourceComponentId, 'root');
    },
  );

  testWidgets('multi-control: each control round-trips its OWN distinct path '
      '(the @RestageProperty annotation pairing, no cross-wiring)', (
    tester,
  ) async {
    dataContext.update(DataPath('lo'), 0);
    dataContext.update(DataPath('hi'), 10);
    await _pumpInteractive(
      tester,
      catalog: catalog,
      items: items,
      type: 'Range',
      data: _asDelivered(const {
        'low': {'path': 'lo'},
        'high': {'path': 'hi'},
      }),
      dataContext: dataContext,
      dispatchEvent: dispatched.add,
    );
    expect(find.byType(RangeFixture), findsOneWidget);
    expect(find.text('range-low:0'), findsOneWidget);
    expect(find.text('range-high:10'), findsOneWidget);

    // Tapping the low control writes ONLY the low path.
    await tester.tap(find.byKey(const ValueKey('range-low-inc')));
    await tester.pump();
    expect(find.text('range-low:1'), findsOneWidget);
    expect(find.text('range-high:10'), findsOneWidget); // unchanged
    expect(dataContext.getValue<num>(DataPath('lo')), 1);
    expect(dataContext.getValue<num>(DataPath('hi')), 10);

    // Tapping the high control writes ONLY the high path.
    await tester.tap(find.byKey(const ValueKey('range-high-inc')));
    await tester.pump();
    expect(find.text('range-low:1'), findsOneWidget); // unchanged
    expect(find.text('range-high:11'), findsOneWidget);
    expect(dataContext.getValue<num>(DataPath('lo')), 1);
    expect(dataContext.getValue<num>(DataPath('hi')), 11);
  });

  testWidgets('the path-field hazard: a value whose content is literally "path" '
      'is DATA at the bound path, not a binding misread', (tester) async {
    // The list value contains the element "path". The read is `{path: P}` (the
    // binding to the SEPARATE data path "picks"); the element "path" is the
    // value AT that path — never confused with the binding (closed by
    // construction: a scalar/list value is read via the path binding, the
    // content is data).
    dataContext.update(DataPath('picks'), <String>['path']);
    await _pumpInteractive(
      tester,
      catalog: catalog,
      items: items,
      type: 'MultiSelect',
      data: _asDelivered(const {
        'chosen': {'path': 'picks'},
      }),
      dataContext: dataContext,
      dispatchEvent: dispatched.add,
    );
    expect(find.text('multiselect-chosen:path'), findsOneWidget);

    await tester.tap(find.byKey(const ValueKey('multiselect-add-b')));
    await tester.pump();
    expect(find.text('multiselect-chosen:path,b'), findsOneWidget);
    expect(dataContext.getValue<List<Object?>>(DataPath('picks')), <String>[
      'path',
      'b',
    ]);
  });
}
