import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:genui/genui.dart';

import 'generated/rich_shape_catalog.g.dart';
import 'generated/rich_shape_fixture.dart';

/// The data-shape fidelity proof — the render leg.
///
/// Renders the committed rich-shape catalog (generated by the production A2UI
/// emitter from the REAL reflector reading the REAL fixture) against real genui
/// 0.9.2, exactly as genui would: a real [CatalogItemContext] + [DataContext]
/// and `Catalog.buildWidget` in a real element tree. It proves the generated
/// reconstruction code RUNS (not merely type-checks) and that the reconstructed
/// customer data shapes — a nested data class, a list-of-objects, a String-
/// keyed map, a named record, nullable fields — arrive at the widget.
Future<void> _pumpCatalogItem(
  WidgetTester tester, {
  required Catalog catalog,
  required List<CatalogItem> items,
  required String type,
  required Map<String, Object?> data,
}) async {
  await tester.pumpWidget(
    MaterialApp(
      home: Builder(
        builder: (context) {
          final itemContext = CatalogItemContext(
            data: data,
            id: 'root',
            type: type,
            buildChild: (childId, [dataContext]) => Text('child-$childId'),
            dispatchEvent: (_) {},
            buildContext: context,
            dataContext: DataContext(InMemoryDataModel(), DataPath.root),
            getComponent: (_) => null,
            getCatalogItem: (t) {
              for (final item in items) {
                if (item.name == t) return item;
              }
              return null;
            },
            surfaceId: 'test-surface',
            reportError: (error, stack) => throw error,
          );
          return catalog.buildWidget(itemContext);
        },
      ),
    ),
  );
}

/// Round-trips [data] through JSON so the values arrive in the shape genui
/// delivers from a decoded payload (e.g. a `List<dynamic>`, not a
/// `List<String>`).
Map<String, Object?> _asDelivered(Map<String, Object?> data) =>
    jsonDecode(jsonEncode(data)) as Map<String, Object?>;

void main() {
  late List<CatalogItem> items;
  late Catalog catalog;

  setUp(() {
    items = buildRestageCatalogItems();
    catalog = Catalog(items);
  });

  test('the generated rich-shape catalog exposes the fixture items', () {
    expect(
      items.map((i) => i.name),
      containsAll(<String>[
        'PlanCard',
        'FeatureGrid',
        'Glossary',
        'MetaBar',
        'LinkCard',
      ]),
    );
  });

  testWidgets('a nested data class reconstructs (with a nullable enum + '
      'nullable string) and renders', (tester) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'PlanCard',
      data: _asDelivered(const {
        'plan': {
          'name': 'Pro',
          'price': 12.5,
          'badge': 'popular',
          'tagline': 'Best for teams',
        },
      }),
    );
    expect(find.byType(PlanCardFixture), findsOneWidget);
    expect(find.text('plan-name:Pro'), findsOneWidget);
    expect(find.text('plan-price:12.5'), findsOneWidget);
    expect(find.text('plan-badge:popular'), findsOneWidget);
    expect(find.text('plan-tagline:Best for teams'), findsOneWidget);
  });

  testWidgets('a nullable enum + nullable string degrade to null when absent', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'PlanCard',
      // badge + tagline omitted → the nullable fields reconstruct to null.
      data: _asDelivered(const {
        'plan': {'name': 'Free', 'price': 0.0},
      }),
    );
    expect(find.text('plan-name:Free'), findsOneWidget);
    expect(find.text('plan-badge:none'), findsOneWidget);
    expect(find.text('plan-tagline:-'), findsOneWidget);
  });

  testWidgets('a list-of-objects reconstructs element-by-element', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'FeatureGrid',
      data: _asDelivered(const {
        'features': [
          {'label': 'SSO', 'included': true},
          {'label': 'Audit log', 'included': false},
        ],
      }),
    );
    expect(find.byType(FeatureGridFixture), findsOneWidget);
    expect(find.text('feature:SSO:true'), findsOneWidget);
    expect(find.text('feature:Audit log:false'), findsOneWidget);
  });

  testWidgets('a String-keyed map reconstructs — including a key named "path"', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'Glossary',
      // A map key literally named "path" — the binding-sentinel hazard for the
      // map case; direct reconstruction reads it as data, not a binding.
      data: _asDelivered(const {
        'terms': {'path': 'a route', 'api': 'an interface'},
      }),
    );
    expect(find.byType(GlossaryFixture), findsOneWidget);
    expect(find.text('term:api=an interface'), findsOneWidget);
    expect(find.text('term:path=a route'), findsOneWidget);
  });

  testWidgets('a named record reconstructs', (tester) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'MetaBar',
      data: _asDelivered(const {
        'meta': {'title': 'Q3', 'count': 42},
      }),
    );
    expect(find.text('meta:Q3:42'), findsOneWidget);
  });

  testWidgets('an object whose field is named "path" reconstructs correctly '
      '(the BoundObject binding-sentinel hazard, closed by construction)', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'LinkCard',
      data: _asDelivered(const {
        'link': {'path': '/settings', 'label': 'Settings'},
      }),
    );
    // BoundObject would have read `{path: '/settings', ...}` as a path BINDING
    // and mis-rendered; direct reconstruction reads the field by name.
    expect(find.byType(LinkCardFixture), findsOneWidget);
    expect(find.text('link:Settings:/settings'), findsOneWidget);
  });

  testWidgets('a self-recursive nested object reconstructs depth-first and '
      'renders (\$ref-rooted schema + depth-bounded helper)', (tester) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'CommentThread',
      data: _asDelivered(const {
        'root': {
          'text': 'top',
          'reply': {'text': 'nested'},
        },
      }),
    );
    expect(find.byType(CommentThreadFixture), findsOneWidget);
    expect(find.text('comment:top'), findsOneWidget);
    expect(find.text('reply:nested'), findsOneWidget);
  });

  testWidgets('a REQUIRED rich arg fails the widget safe on malformed data', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'PlanCard',
      // `plan` is required + non-null but the payload is not an object → the
      // reconstruction is null → SizedBox.shrink, never a force-unwrap crash.
      data: _asDelivered(const {'plan': 'not-an-object'}),
    );
    expect(find.byType(PlanCardFixture), findsNothing);
    expect(find.byType(SizedBox), findsWidgets);
  });

  testWidgets('a REQUIRED nested-object field missing fails the widget safe', (
    tester,
  ) async {
    await _pumpCatalogItem(
      tester,
      catalog: catalog,
      items: items,
      type: 'PlanCard',
      // `name` is required inside PlanTier; absent → the object reconstructs
      // null → the widget fails safe (never a fabricated required value).
      data: _asDelivered(const {
        'plan': {'price': 1.0},
      }),
    );
    expect(find.byType(PlanCardFixture), findsNothing);
  });
}
