// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
//
// Per-widget LocalWidgetBuilder map for the 'restage.material' library.
// To change this map: edit lib/registry_curation.dart, then
// re-run build_runner (it regenerates the registry, the
// catalog, and this file).

import 'package:flutter/material.dart';
import 'package:restage_material/src/widgets/express_checkout_button.dart';
import 'package:restage_material/src/widgets/package.dart';
import 'package:restage_material/src/widgets/restage_draggable_sheet.dart';
import 'package:restage_material/src/widgets/restage_dropdown.dart';
import 'package:restage_material/src/widgets/restage_modal_sheet.dart';
import 'package:restage_material/src/widgets/restage_pager.dart';
import 'package:restage_material/src/widgets/restage_radio_group.dart';
import 'package:restage_material/src/widgets/restage_segmented_button.dart';
import 'package:restage_material/src/widgets/restage_toggle_buttons.dart';
import 'package:restage_core/restage_core.dart';
import 'package:rfw/rfw.dart' hide Switch;

/// One [LocalWidgetBuilder] per widget entry in `lib/registry.dart`,
/// keyed by widget name.
const Map<String, LocalWidgetBuilder> kMaterialLibraryFactories =
    <String, LocalWidgetBuilder>{
  'ActionChip': _buildActionChip,
  'AppBar': _buildAppBar,
  'Badge': _buildBadge,
  'Card': _buildCard,
  'CardFilled': _buildCardFilled,
  'CardOutlined': _buildCardOutlined,
  'Checkbox': _buildCheckbox,
  'CheckboxListTile': _buildCheckboxListTile,
  'Chip': _buildChip,
  'ChoiceChip': _buildChoiceChip,
  'CircularProgressIndicator': _buildCircularProgressIndicator,
  'Divider': _buildDivider,
  'ElevatedButton': _buildElevatedButton,
  'ExpansionTile': _buildExpansionTile,
  'ExpressCheckoutButton': _buildExpressCheckoutButton,
  'FilledButton': _buildFilledButton,
  'FilledButtonTonal': _buildFilledButtonTonal,
  'FilterChip': _buildFilterChip,
  'FloatingActionButton': _buildFloatingActionButton,
  'Icon': _buildIcon,
  'IconButton': _buildIconButton,
  'InkWell': _buildInkWell,
  'LinearProgressIndicator': _buildLinearProgressIndicator,
  'ListTile': _buildListTile,
  'MaterialApp': _buildMaterialApp,
  'RestageModalSheet': _buildRestageModalSheet,
  'RestagePager': _buildRestagePager,
  'RestageRadioGroupString': _buildRestageRadioGroupString,
  'RestageDropdownString': _buildRestageDropdownString,
  'RestageToggleButtons': _buildRestageToggleButtons,
  'RestageSegmentedButtonString': _buildRestageSegmentedButtonString,
  'RestageDraggableSheet': _buildRestageDraggableSheet,
  'OutlinedButton': _buildOutlinedButton,
  'OutlinedButtonIcon': _buildOutlinedButtonIcon,
  'Package': _buildPackage,
  'Scaffold': _buildScaffold,
  'Scrollbar': _buildScrollbar,
  'Slider': _buildSlider,
  'Switch': _buildSwitch,
  'SwitchListTile': _buildSwitchListTile,
  'TextButton': _buildTextButton,
  'TextButtonIcon': _buildTextButtonIcon,
  'Tab': _buildTab,
  'TextField': _buildTextField,
  'Tooltip': _buildTooltip,
};

Widget _buildActionChip(BuildContext context, DataSource source) {
  return ActionChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
  );
}

Widget _buildAppBar(BuildContext context, DataSource source) {
  return AppBar(
    title: source.optionalChild(<Object>['title']),
    elevation: source.v<double>(<Object>['elevation']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    foregroundColor:
        ArgumentDecoders.color(source, <Object>['foregroundColor']),
    centerTitle: source.v<bool>(<Object>['centerTitle']) ?? true,
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
  );
}

Widget _buildBadge(BuildContext context, DataSource source) {
  return Badge(
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    textColor: ArgumentDecoders.color(source, <Object>['textColor']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    alignment: ArgumentDecoders.alignment(source, <Object>['alignment']),
    offset: RestageDecoders.offset(source, <Object>['offset']),
    label: source.optionalChild(<Object>['label']),
    isLabelVisible: source.v<bool>(<Object>['isLabelVisible']) ?? true,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildCard(BuildContext context, DataSource source) {
  return Card(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 1.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildCardFilled(BuildContext context, DataSource source) {
  return Card.filled(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildCardOutlined(BuildContext context, DataSource source) {
  return Card.outlined(
    color: ArgumentDecoders.color(source, <Object>['color']),
    elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildCheckbox(BuildContext context, DataSource source) {
  return Checkbox(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('Checkbox.value is required.')),
    onChanged: source.handler<ValueChanged<bool?>>(
            <Object>['onChanged'],
            (HandlerTrigger trigger) =>
                (bool? value) => trigger(<String, Object?>{'value': value})) ??
        (bool? _) {},
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
  );
}

Widget _buildCheckboxListTile(BuildContext context, DataSource source) {
  return CheckboxListTile(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('CheckboxListTile.value is required.')),
    onChanged: source.handler<ValueChanged<bool?>>(
            <Object>['onChanged'],
            (HandlerTrigger trigger) =>
                (bool? value) => trigger(<String, Object?>{'value': value})) ??
        (bool? _) {},
    activeColor: ArgumentDecoders.color(source, <Object>['activeColor']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    secondary: source.optionalChild(<Object>['secondary']),
    selected: source.v<bool>(<Object>['selected']) ?? false,
  );
}

Widget _buildChip(BuildContext context, DataSource source) {
  return Chip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
  );
}

Widget _buildChoiceChip(BuildContext context, DataSource source) {
  return ChoiceChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    onSelected: source.handler<ValueChanged<bool>>(
        <Object>['onSelected'],
        (HandlerTrigger trigger) =>
            (bool value) => trigger(<String, Object?>{'value': value})),
    selected: source.v<bool>(<Object>['selected']) ??
        (throw ArgumentError('ChoiceChip.selected is required.')),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    avatarBorder:
        RestageDecoders.shapeBorder(source, <Object>['avatarBorder']) ??
            const CircleBorder(),
  );
}

Widget _buildCircularProgressIndicator(
    BuildContext context, DataSource source) {
  return CircularProgressIndicator(
    value: source.v<double>(<Object>['value']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    strokeWidth: source.v<double>(<Object>['strokeWidth']) ?? 4.0,
  );
}

Widget _buildDivider(BuildContext context, DataSource source) {
  return Divider(
    height: source.v<double>(<Object>['height']) ?? 16.0,
    thickness: source.v<double>(<Object>['thickness']) ?? 1.0,
    color: ArgumentDecoders.color(source, <Object>['color']),
  );
}

Widget _buildElevatedButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return ElevatedButton(
    style: ElevatedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        elevation: source.v<double>(<Object>['elevation']) ?? 1.0,
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildExpansionTile(BuildContext context, DataSource source) {
  return ExpansionTile(
    leading: source.optionalChild(<Object>['leading']),
    title: source.child(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    onExpansionChanged: source.handler<ValueChanged<bool>>(
        <Object>['onExpansionChanged'],
        (HandlerTrigger trigger) =>
            (bool value) => trigger(<String, Object?>{'value': value})),
    trailing: source.optionalChild(<Object>['trailing']),
    initiallyExpanded: source.v<bool>(<Object>['initiallyExpanded']) ?? false,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    collapsedShape:
        RestageDecoders.shapeBorder(source, <Object>['collapsedShape']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    children: source.childList(<Object>['children']),
  );
}

Widget _buildExpressCheckoutButton(BuildContext context, DataSource source) {
  return ExpressCheckoutButton(
    onPressed: source.voidHandler(<Object>['onPressed']),
    paymentMethod: ArgumentDecoders.enumValue<ExpressPaymentMethod>(
            ExpressPaymentMethod.values, source, <Object>['paymentMethod']) ??
        ExpressPaymentMethod.auto,
    label: source.v<String>(<Object>['label']),
  );
}

Widget _buildFilledButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return FilledButton(
    style: FilledButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        elevation: source.v<double>(<Object>['elevation']) ?? 0.0,
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.child(<Object>['child']),
  );
}

Widget _buildFilledButtonTonal(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return FilledButton.tonal(
    style: FilledButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        backgroundColor:
            ArgumentDecoders.color(source, <Object>['backgroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.child(<Object>['child']),
  );
}

Widget _buildFilterChip(BuildContext context, DataSource source) {
  return FilterChip(
    avatar: source.optionalChild(<Object>['avatar']),
    label: source.child(<Object>['label']),
    selected: source.v<bool>(<Object>['selected']) ?? false,
    onSelected: source.handler<ValueChanged<bool>>(
        <Object>['onSelected'],
        (HandlerTrigger trigger) =>
            (bool value) => trigger(<String, Object?>{'value': value})),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    avatarBorder:
        RestageDecoders.shapeBorder(source, <Object>['avatarBorder']) ??
            const CircleBorder(),
  );
}

Widget _buildFloatingActionButton(BuildContext context, DataSource source) {
  return FloatingActionButton(
    tooltip: source.v<String>(<Object>['tooltip']),
    foregroundColor:
        ArgumentDecoders.color(source, <Object>['foregroundColor']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    elevation: source.v<double>(<Object>['elevation']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    mini: source.v<bool>(<Object>['mini']) ?? false,
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildIcon(BuildContext context, DataSource source) {
  return Icon(
    IconData(
        source.v<int>(<Object>['iconCodepoint']) ??
            (throw ArgumentError('Icon.iconCodepoint is required.')),
        fontFamily: 'MaterialIcons'),
    size: source.v<double>(<Object>['size']) ??
        resolveThemeBinding(context, path: 'iconTheme.size') as double?,
    color: ArgumentDecoders.color(source, <Object>['color']) ??
        resolveThemeBinding(context, path: 'iconTheme.color') as Color?,
  );
}

Widget _buildIconButton(BuildContext context, DataSource source) {
  return IconButton(
    iconSize: source.v<double>(<Object>['iconSize']) ?? 24.0,
    color: ArgumentDecoders.color(source, <Object>['color']),
    onPressed: source.voidHandler(<Object>['onPressed']),
    tooltip: source.v<String>(<Object>['tooltip']),
    icon: source.child(<Object>['icon']),
  );
}

Widget _buildInkWell(BuildContext context, DataSource source) {
  return InkWell(
    onTap: source.voidHandler(<Object>['onTap']),
    customBorder: RestageDecoders.shapeBorder(source, <Object>['customBorder']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildLinearProgressIndicator(BuildContext context, DataSource source) {
  return LinearProgressIndicator(
    value: source.v<double>(<Object>['value']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    color: ArgumentDecoders.color(source, <Object>['color']),
    minHeight: source.v<double>(<Object>['minHeight']),
  );
}

Widget _buildListTile(BuildContext context, DataSource source) {
  return ListTile(
    leading: source.optionalChild(<Object>['leading']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    trailing: source.optionalChild(<Object>['trailing']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    onTap: source.voidHandler(<Object>['onTap']),
  );
}

Widget _buildMaterialApp(BuildContext context, DataSource source) {
  return MaterialApp(
    home: source.optionalChild(<Object>['home']),
    title: source.v<String>(<Object>['title']) ?? '',
  );
}

Widget _buildRestageModalSheet(BuildContext context, DataSource source) {
  return RestageModalSheet(
    open: source.v<bool>(<Object>['open']) ??
        (throw ArgumentError('RestageModalSheet.open is required.')),
    isDismissible: source.v<bool>(<Object>['isDismissible']) ?? true,
    enableDrag: source.v<bool>(<Object>['enableDrag']) ?? true,
    showDragHandle: source.v<bool>(<Object>['showDragHandle']),
    dragHandleColor:
        ArgumentDecoders.color(source, <Object>['dragHandleColor']),
    isScrollControlled: source.v<bool>(<Object>['isScrollControlled']) ?? false,
    scrollControlDisabledMaxHeightRatio:
        source.v<double>(<Object>['scrollControlDisabledMaxHeightRatio']) ??
            0.5625,
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
    elevation: source.v<double>(<Object>['elevation']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    useSafeArea: source.v<bool>(<Object>['useSafeArea']) ?? false,
    barrierColor: ArgumentDecoders.color(source, <Object>['barrierColor']),
    barrierLabel: source.v<String>(<Object>['barrierLabel']),
    anchorPoint: RestageDecoders.offset(source, <Object>['anchorPoint']),
    enterDuration: RestageDecoders.duration(source, <Object>['enterDuration']),
    exitDuration: RestageDecoders.duration(source, <Object>['exitDuration']),
    enterCurve: RestageDecoders.curve(source, <Object>['enterCurve']),
    exitCurve: RestageDecoders.curve(source, <Object>['exitCurve']),
    presentation: ArgumentDecoders.enumValue<RestageSheetPresentation>(
            RestageSheetPresentation.values,
            source,
            <Object>['presentation']) ??
        RestageSheetPresentation.adaptive,
    underlay: source.optionalChild(<Object>['underlay']),
    onSheetDismissed: source.voidHandler(<Object>['onSheetDismissed']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildRestagePager(BuildContext context, DataSource source) {
  return RestagePager(
    initialPage: source.v<int>(<Object>['initialPage']) ?? 0,
    viewportFraction: source.v<double>(<Object>['viewportFraction']) ?? 1.0,
    scrollDirection: ArgumentDecoders.enumValue<Axis>(
            Axis.values, source, <Object>['scrollDirection']) ??
        Axis.horizontal,
    pageSnapping: source.v<bool>(<Object>['pageSnapping']) ?? true,
    onPageChanged: source.handler<ValueChanged<int>>(
        <Object>['onPageChanged'],
        (HandlerTrigger trigger) =>
            (int value) => trigger(<String, Object?>{'value': value})),
    children: source.childList(<Object>['children']),
  );
}

Widget _buildRestageRadioGroupString(BuildContext context, DataSource source) {
  return RestageRadioGroup<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError('RestageRadioGroupString.items is required.')),
    selected: source.v<String>(<Object>['selected']),
    onChanged: source.handler<ValueChanged<String?>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (String? value) => trigger(<String, Object?>{'value': value})),
  );
}

Widget _buildRestageDropdownString(BuildContext context, DataSource source) {
  return RestageDropdown<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError('RestageDropdownString.items is required.')),
    selected: source.v<String>(<Object>['selected']),
    onChanged: source.handler<ValueChanged<String?>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (String? value) => trigger(<String, Object?>{'value': value})),
  );
}

Widget _buildRestageToggleButtons(BuildContext context, DataSource source) {
  return RestageToggleButtons(
    isSelected: RestageDecoders.booleanList(source, <Object>['isSelected']) ??
        (throw ArgumentError('RestageToggleButtons.isSelected is required.')),
    onPressed: source.handler<ValueChanged<int>>(
        <Object>['onPressed'],
        (HandlerTrigger trigger) =>
            (int value) => trigger(<String, Object?>{'value': value})),
    children: source.childList(<Object>['children']),
  );
}

Widget _buildRestageSegmentedButtonString(
    BuildContext context, DataSource source) {
  return RestageSegmentedButton<String>(
    items: RestageDecoders.selectionOptionList(source, <Object>['items']) ??
        (throw ArgumentError(
            'RestageSegmentedButtonString.items is required.')),
    selected: RestageDecoders.stringList(source, <Object>['selected']),
    onChanged: source.handler<ValueChanged<List<String>>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (List<String> value) => trigger(<String, Object?>{'value': value})),
    multiSelectionEnabled:
        source.v<bool>(<Object>['multiSelectionEnabled']) ?? false,
    emptySelectionAllowed:
        source.v<bool>(<Object>['emptySelectionAllowed']) ?? false,
    showSelectedIcon: source.v<bool>(<Object>['showSelectedIcon']) ?? true,
  );
}

Widget _buildRestageDraggableSheet(BuildContext context, DataSource source) {
  return RestageDraggableSheet(
    initialChildSize: source.v<double>(<Object>['initialChildSize']) ?? 0.5,
    minChildSize: source.v<double>(<Object>['minChildSize']) ?? 0.25,
    maxChildSize: source.v<double>(<Object>['maxChildSize']) ?? 1.0,
    expand: source.v<bool>(<Object>['expand']) ?? true,
    snap: source.v<bool>(<Object>['snap']) ?? false,
    snapAnimationDuration:
        RestageDecoders.duration(source, <Object>['snapAnimationDuration']),
    expanded: source.v<bool>(<Object>['expanded']) ?? false,
    expandDuration:
        RestageDecoders.duration(source, <Object>['expandDuration']),
    expandCurve: RestageDecoders.curve(source, <Object>['expandCurve']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildOutlinedButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return OutlinedButton(
    style: OutlinedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildOutlinedButtonIcon(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return OutlinedButton.icon(
    style: OutlinedButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    icon: source.child(<Object>['icon']),
    label: source.child(<Object>['label']),
  );
}

Widget _buildPackage(BuildContext context, DataSource source) {
  return Package(
    slot: source.v<String>(<Object>['slot']) ??
        (throw ArgumentError('Package.slot is required.')),
    child: source.child(<Object>['child']),
  );
}

Widget _buildScaffold(BuildContext context, DataSource source) {
  return Scaffold(
    body: source.optionalChild(<Object>['body']),
    backgroundColor:
        ArgumentDecoders.color(source, <Object>['backgroundColor']),
  );
}

Widget _buildScrollbar(BuildContext context, DataSource source) {
  return Scrollbar(
    thumbVisibility: source.v<bool>(<Object>['thumbVisibility']),
    trackVisibility: source.v<bool>(<Object>['trackVisibility']),
    thickness: source.v<double>(<Object>['thickness']),
    interactive: source.v<bool>(<Object>['interactive']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildSlider(BuildContext context, DataSource source) {
  return Slider(
    value: source.v<double>(<Object>['value']) ??
        (throw ArgumentError('Slider.value is required.')),
    secondaryTrackValue: source.v<double>(<Object>['secondaryTrackValue']),
    onChanged: source.handler<ValueChanged<double>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (double value) => trigger(<String, Object?>{'value': value})),
    min: source.v<double>(<Object>['min']) ?? 0.0,
    max: source.v<double>(<Object>['max']) ?? 1.0,
    divisions: source.v<int>(<Object>['divisions']),
    label: source.v<String>(<Object>['label']),
  );
}

Widget _buildSwitch(BuildContext context, DataSource source) {
  return Switch(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('Switch.value is required.')),
    onChanged: source.handler<ValueChanged<bool>>(
            <Object>['onChanged'],
            (HandlerTrigger trigger) =>
                (bool value) => trigger(<String, Object?>{'value': value})) ??
        (bool _) {},
    activeThumbColor:
        ArgumentDecoders.color(source, <Object>['activeThumbColor']),
  );
}

Widget _buildSwitchListTile(BuildContext context, DataSource source) {
  return SwitchListTile(
    value: source.v<bool>(<Object>['value']) ??
        (throw ArgumentError('SwitchListTile.value is required.')),
    onChanged: source.handler<ValueChanged<bool>>(
            <Object>['onChanged'],
            (HandlerTrigger trigger) =>
                (bool value) => trigger(<String, Object?>{'value': value})) ??
        (bool _) {},
    activeThumbColor:
        ArgumentDecoders.color(source, <Object>['activeThumbColor']),
    title: source.optionalChild(<Object>['title']),
    subtitle: source.optionalChild(<Object>['subtitle']),
    secondary: source.optionalChild(<Object>['secondary']),
    shape: RestageDecoders.shapeBorder(source, <Object>['shape']),
  );
}

Widget _buildTextButton(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return TextButton(
    style: TextButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
        Clip.values, source, <Object>['clipBehavior']),
    child: source.child(<Object>['child']),
  );
}

Widget _buildTextButtonIcon(BuildContext context, DataSource source) {
  final disabled = source.v<bool>(<Object>['disabled']) ?? false;

  return TextButton.icon(
    style: TextButton.styleFrom(
        foregroundColor:
            ArgumentDecoders.color(source, <Object>['foregroundColor']),
        textStyle: RestageDecoders.textStyle(source, <Object>['textStyle']),
        padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']) ??
            const EdgeInsets.fromLTRB(24.0, 12.0, 24.0, 12.0),
        minimumSize: RestageDecoders.size(source, <Object>['minimumSize']),
        fixedSize: RestageDecoders.size(source, <Object>['fixedSize']),
        side: RestageDecoders.borderSide(source, <Object>['side']),
        shape: (RestageDecoders.shapeBorder(source, <Object>['shape'])
            as OutlinedBorder?)),
    onPressed: disabled ? null : source.voidHandler(<Object>['onPressed']),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.none,
    icon: source.child(<Object>['icon']),
    label: source.child(<Object>['label']),
  );
}

Widget _buildTab(BuildContext context, DataSource source) {
  return Tab(
    text: source.v<String>(<Object>['text']),
    icon: source.optionalChild(<Object>['icon']),
    iconMargin: ArgumentDecoders.edgeInsets(source, <Object>['iconMargin']),
    height: source.v<double>(<Object>['height']),
    child: source.optionalChild(<Object>['child']),
  );
}

Widget _buildTextField(BuildContext context, DataSource source) {
  return TextField(
    obscureText: source.v<bool>(<Object>['obscureText']) ?? false,
    maxLines: source.v<int>(<Object>['maxLines']) ?? 1,
    maxLength: source.v<int>(<Object>['maxLength']),
    onChanged: source.handler<ValueChanged<String>>(
        <Object>['onChanged'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    onSubmitted: source.handler<ValueChanged<String>>(
        <Object>['onSubmitted'],
        (HandlerTrigger trigger) =>
            (String value) => trigger(<String, Object?>{'value': value})),
    clipBehavior: ArgumentDecoders.enumValue<Clip>(
            Clip.values, source, <Object>['clipBehavior']) ??
        Clip.hardEdge,
  );
}

Widget _buildTooltip(BuildContext context, DataSource source) {
  return Tooltip(
    message: source.v<String>(<Object>['message']) ??
        (throw ArgumentError('Tooltip.message is required.')),
    padding: ArgumentDecoders.edgeInsets(source, <Object>['padding']),
    margin: ArgumentDecoders.edgeInsets(source, <Object>['margin']),
    preferBelow: source.v<bool>(<Object>['preferBelow']),
    child: source.optionalChild(<Object>['child']),
  );
}
