import 'dart:io';

import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;
import 'package:restage_cli/src/credentials/credential.dart';
import 'package:yaml/yaml.dart';

/// Default filename for the per-project config consumed by every
/// command that needs project / app / environment defaults.
const _configFileName = 'restage_config.yaml';

/// Per-project defaults for `restage_cli` commands.
///
/// The config file is generated by `restage init` and committed to the
/// host project's repository so every team member shares the same
/// defaults. Flags on individual commands override the values here.
@immutable
class RestageConfig {
  /// Construct a config with the given fields.
  const RestageConfig({
    required this.project,
    required this.app,
    this.defaultEnvironment,
    this.organization,
    this.endpoint,
  });

  /// Project slug the host repository belongs to.
  final String project;

  /// App slug under [project].
  final String app;

  /// Default environment slug for the publish flow. Optional — when
  /// unset, commands prompt (in interactive mode) or require `--env`.
  final String? defaultEnvironment;

  /// Organization slug for this project. Optional for configs written by
  /// older CLI versions.
  final String? organization;

  /// Backend endpoint expected by this project. Optional for configs written
  /// by older CLI versions.
  final String? endpoint;

  /// Decode from a YAML string. Throws [RestageConfigFormatException] when
  /// required keys are missing or have the wrong shape.
  factory RestageConfig.fromYaml(String yamlSrc) {
    final dynamic doc;
    try {
      doc = loadYaml(yamlSrc);
    } on YamlException catch (e) {
      throw RestageConfigFormatException('Could not parse the config file: $e');
    }
    if (doc is! YamlMap && doc is! Map) {
      throw const RestageConfigFormatException(
        'Expected a mapping at the top level of the config file.',
      );
    }
    final map = doc as Map;
    final project = _requireString(map, 'project');
    final app = _requireString(map, 'app');
    final defaultEnvironment = _optionalString(map, 'defaultEnvironment');
    final organization = _optionalString(map, 'organization');
    final endpoint = _optionalString(map, 'endpoint');
    return RestageConfig(
      project: project,
      app: app,
      defaultEnvironment: defaultEnvironment,
      organization: organization,
      endpoint: endpoint,
    );
  }

  /// Render as YAML for [writeRestageConfig].
  String toYaml() {
    final buffer = StringBuffer()
      ..writeln('# Restage project config — generated by `restage init`.')
      ..writeln('# Edit as needed; commit alongside pubspec.yaml.')
      ..writeln('project: $project')
      ..writeln('app: $app');
    if (defaultEnvironment != null) {
      buffer.writeln('defaultEnvironment: $defaultEnvironment');
    }
    if (organization != null) {
      buffer.writeln('organization: $organization');
    }
    if (endpoint != null) {
      buffer.writeln('endpoint: $endpoint');
    }
    return buffer.toString();
  }
}

/// Thrown when [RestageConfig.fromYaml] cannot make sense of the input.
class RestageConfigFormatException implements Exception {
  /// Construct with a human-readable [message].
  const RestageConfigFormatException(this.message);

  /// Human-readable description of the problem.
  final String message;

  @override
  String toString() => message;
}

/// Thrown when a project config expects a different backend than the
/// stored credential was issued for.
abstract interface class EndpointConfigurationException implements Exception {}

/// Thrown when an endpoint string cannot be used as a backend origin.
class EndpointFormatException implements EndpointConfigurationException {
  /// Construct with a human-readable [message].
  const EndpointFormatException(this.message);

  /// Human-readable description of the problem.
  final String message;

  @override
  String toString() => message;
}

/// Thrown when a project config expects a different backend than the
/// stored credential was issued for.
class EndpointMismatchException implements EndpointConfigurationException {
  /// Construct with the normalized endpoints involved in the mismatch.
  const EndpointMismatchException({
    required this.configEndpoint,
    required this.credentialEndpoint,
  });

  /// Backend endpoint requested by the project config.
  final Uri configEndpoint;

  /// Backend endpoint the stored credential belongs to.
  final Uri credentialEndpoint;

  @override
  String toString() =>
      'restage_config.yaml expects $configEndpoint, but the stored '
      'credential belongs to $credentialEndpoint. Run `restage login '
      '--endpoint $configEndpoint` to sign in for this project.';
}

/// Resolve the backend endpoint to use for an API client.
///
/// A project config may name the expected backend, but a stored credential
/// may only be sent to the endpoint it belongs to. Missing config endpoint
/// falls back to the credential endpoint; a mismatched config endpoint fails
/// before an API client can send credentials.
Uri resolveApiEndpoint({
  required RestageConfig? config,
  required Credential credential,
}) {
  final credentialEndpoint = _parseEndpoint(
    credential.endpoint,
    source: _EndpointSource.credential,
  );
  final configValue = config?.endpoint?.trim();
  if (configValue == null || configValue.isEmpty) {
    return credentialEndpoint;
  }
  final configEndpoint = _parseEndpoint(
    configValue,
    source: _EndpointSource.config,
  );
  if (configEndpoint == credentialEndpoint) return configEndpoint;
  throw EndpointMismatchException(
    configEndpoint: configEndpoint,
    credentialEndpoint: credentialEndpoint,
  );
}

/// Walks up from [from] (defaulting to `Directory.current`) looking for
/// `restage_config.yaml`. Returns the parsed config plus the source file
/// when found; returns null when no config exists above [from].
///
/// Stops at the filesystem root.
Future<({RestageConfig config, File source})?> loadRestageConfig({
  Directory? from,
}) async {
  final start = from ?? Directory.current;
  var current = start.absolute;
  while (true) {
    final candidate = File(p.join(current.path, _configFileName));
    if (candidate.existsSync()) {
      final src = await candidate.readAsString();
      return (config: RestageConfig.fromYaml(src), source: candidate);
    }
    final parent = current.parent;
    if (parent.path == current.path) return null;
    current = parent;
  }
}

/// Write [config] to [target] as YAML. Creates parent directories on
/// demand. Overwrites any existing file at [target].
Future<void> writeRestageConfig(File target, RestageConfig config) async {
  await target.parent.create(recursive: true);
  await target.writeAsString(config.toYaml());
}

String _requireString(Map<dynamic, dynamic> map, String key) {
  final value = map[key];
  if (value == null) {
    throw RestageConfigFormatException('Missing required key: `$key`.');
  }
  if (value is! String) {
    throw RestageConfigFormatException(
      'Expected `$key` to be a string, got ${value.runtimeType}.',
    );
  }
  return value;
}

String? _optionalString(Map<dynamic, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is! String) {
    throw RestageConfigFormatException(
      'Expected `$key` to be a string, got ${value.runtimeType}.',
    );
  }
  return value;
}

enum _EndpointSource { config, credential }

Uri _parseEndpoint(String value, {required _EndpointSource source}) {
  final Uri endpoint;
  try {
    endpoint = Uri.parse(value);
  } on FormatException {
    throw _endpointFormatException(value, source: source);
  }
  if (!endpoint.hasScheme || endpoint.host.isEmpty) {
    throw _endpointFormatException(value, source: source);
  }
  return _normalizeEndpoint(endpoint);
}

EndpointFormatException _endpointFormatException(
  String value, {
  required _EndpointSource source,
}) {
  return switch (source) {
    _EndpointSource.config => EndpointFormatException(
      'Invalid endpoint in restage_config.yaml: `$value`. Set it to an '
      'absolute backend URL and run `restage login --endpoint <url>`.',
    ),
    _EndpointSource.credential => EndpointFormatException(
      'The stored credential has an invalid endpoint. Run `restage login` '
      'to refresh it.',
    ),
  };
}

Uri _normalizeEndpoint(Uri endpoint) {
  final path = endpoint.path;
  if (path.isEmpty) return endpoint.replace(path: '/');
  if (path.endsWith('/')) return endpoint;
  return endpoint.replace(path: '$path/');
}
