import 'dart:io';

import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Default filename for the per-project config consumed by every
/// command that needs project / app / environment defaults.
const _configFileName = 'restage_config.yaml';

/// Per-project defaults for `restage_cli` commands.
///
/// The config file is generated by `restage init` and committed to the
/// host project's repository so every team member shares the same
/// defaults. Flags on individual commands override the values here.
@immutable
class RestageConfig {
  /// Construct a config with the given fields.
  const RestageConfig({
    required this.project,
    required this.app,
    this.defaultEnvironment,
  });

  /// Project slug the host repository belongs to.
  final String project;

  /// App slug under [project].
  final String app;

  /// Default environment slug for the publish flow. Optional — when
  /// unset, commands prompt (in interactive mode) or require `--env`.
  final String? defaultEnvironment;

  /// Decode from a YAML string. Throws [RestageConfigFormatException] when
  /// required keys are missing or have the wrong shape.
  factory RestageConfig.fromYaml(String yamlSrc) {
    final dynamic doc;
    try {
      doc = loadYaml(yamlSrc);
    } on YamlException catch (e) {
      throw RestageConfigFormatException('Could not parse the config file: $e');
    }
    if (doc is! YamlMap && doc is! Map) {
      throw const RestageConfigFormatException(
        'Expected a mapping at the top level of the config file.',
      );
    }
    final map = doc as Map;
    final project = _requireString(map, 'project');
    final app = _requireString(map, 'app');
    final defaultEnvironment = _optionalString(map, 'defaultEnvironment');
    return RestageConfig(
      project: project,
      app: app,
      defaultEnvironment: defaultEnvironment,
    );
  }

  /// Render as YAML for [writeRestageConfig].
  String toYaml() {
    final buffer = StringBuffer()
      ..writeln('# Restage project config — generated by `restage init`.')
      ..writeln('# Edit as needed; commit alongside pubspec.yaml.')
      ..writeln('project: $project')
      ..writeln('app: $app');
    if (defaultEnvironment != null) {
      buffer.writeln('defaultEnvironment: $defaultEnvironment');
    }
    return buffer.toString();
  }
}

/// Thrown when [RestageConfig.fromYaml] cannot make sense of the input.
class RestageConfigFormatException implements Exception {
  /// Construct with a human-readable [message].
  const RestageConfigFormatException(this.message);

  /// Human-readable description of the problem.
  final String message;

  @override
  String toString() => message;
}

/// Walks up from [from] (defaulting to `Directory.current`) looking for
/// `restage_config.yaml`. Returns the parsed config plus the source file
/// when found; returns null when no config exists above [from].
///
/// Stops at the filesystem root.
Future<({RestageConfig config, File source})?> loadRestageConfig({
  Directory? from,
}) async {
  final start = from ?? Directory.current;
  var current = start.absolute;
  while (true) {
    final candidate = File(p.join(current.path, _configFileName));
    if (candidate.existsSync()) {
      final src = await candidate.readAsString();
      return (config: RestageConfig.fromYaml(src), source: candidate);
    }
    final parent = current.parent;
    if (parent.path == current.path) return null;
    current = parent;
  }
}

/// Write [config] to [target] as YAML. Creates parent directories on
/// demand. Overwrites any existing file at [target].
Future<void> writeRestageConfig(File target, RestageConfig config) async {
  await target.parent.create(recursive: true);
  await target.writeAsString(config.toYaml());
}

String _requireString(Map<dynamic, dynamic> map, String key) {
  final value = map[key];
  if (value == null) {
    throw RestageConfigFormatException('Missing required key: `$key`.');
  }
  if (value is! String) {
    throw RestageConfigFormatException(
      'Expected `$key` to be a string, got ${value.runtimeType}.',
    );
  }
  return value;
}

String? _optionalString(Map<dynamic, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is! String) {
    throw RestageConfigFormatException(
      'Expected `$key` to be a string, got ${value.runtimeType}.',
    );
  }
  return value;
}
