// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by restage_codegen.
// ignore_for_file: type=lint
import 'package:restage_codegen/src/translator_recipe.dart';

/// Translator recipes keyed by their (library, type, variant) triple.
const Map<String, TranslatorRecipe> kTranslatorRecipes = {
  '#Offset': TranslatorRecipe(
      typeName: 'Offset',
      validations: [
        RecipeValidation(
            check: ArityExact(2),
            issueCode: 'unrecognizedMethodCall',
            message: 'Offset() requires two positional arguments (x, y).')
      ],
      emit: EmitFragmentMap([
        EmitMapEntry(
            'x', EmitFragmentArg(ArgRef.positional(0), asLength: true)),
        EmitMapEntry('y', EmitFragmentArg(ArgRef.positional(1), asLength: true))
      ]),
      failureDsl: '{x: 0.0, y: 0.0}'),
  '#Size': TranslatorRecipe(
      typeName: 'Size',
      validations: [
        RecipeValidation(
            check: ArityExact(2),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Size() requires two positional arguments (width, height).')
      ],
      emit: EmitFragmentMap([
        EmitMapEntry(
            'width', EmitFragmentArg(ArgRef.positional(0), asLength: true)),
        EmitMapEntry(
            'height', EmitFragmentArg(ArgRef.positional(1), asLength: true))
      ]),
      failureDsl: '{width: 0.0, height: 0.0}'),
  '#TextStyle': TranslatorRecipe(
      typeName: 'TextStyle',
      emit: EmitFragmentMap([
        EmitMapEntry('inherit', EmitFragmentArg(ArgRef.named('inherit')),
            omitWhenArgUnset: true),
        EmitMapEntry('color', EmitFragmentArg(ArgRef.named('color')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'backgroundColor', EmitFragmentArg(ArgRef.named('backgroundColor')),
            omitWhenArgUnset: true),
        EmitMapEntry('fontSize',
            EmitFragmentArg(ArgRef.named('fontSize'), asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry('fontWeight', EmitFragmentArg(ArgRef.named('fontWeight')),
            omitWhenArgUnset: true),
        EmitMapEntry('fontStyle', EmitFragmentArg(ArgRef.named('fontStyle')),
            omitWhenArgUnset: true),
        EmitMapEntry('letterSpacing',
            EmitFragmentArg(ArgRef.named('letterSpacing'), asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry('wordSpacing',
            EmitFragmentArg(ArgRef.named('wordSpacing'), asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'textBaseline', EmitFragmentArg(ArgRef.named('textBaseline')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'height', EmitFragmentArg(ArgRef.named('height'), asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry('leadingDistribution',
            EmitFragmentArg(ArgRef.named('leadingDistribution')),
            omitWhenArgUnset: true),
        EmitMapEntry('locale', EmitFragmentArg(ArgRef.named('locale')),
            omitWhenArgUnset: true),
        EmitMapEntry('foreground', EmitFragmentArg(ArgRef.named('foreground')),
            omitWhenArgUnset: true),
        EmitMapEntry('background', EmitFragmentArg(ArgRef.named('background')),
            omitWhenArgUnset: true),
        EmitMapEntry('shadows', EmitFragmentArg(ArgRef.named('shadows')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'fontFeatures', EmitFragmentArg(ArgRef.named('fontFeatures')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'fontVariations', EmitFragmentArg(ArgRef.named('fontVariations')),
            omitWhenArgUnset: true),
        EmitMapEntry('decoration', EmitFragmentArg(ArgRef.named('decoration')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'decorationColor', EmitFragmentArg(ArgRef.named('decorationColor')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'decorationStyle', EmitFragmentArg(ArgRef.named('decorationStyle')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'decorationThickness',
            EmitFragmentArg(ArgRef.named('decorationThickness'),
                asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry('debugLabel', EmitFragmentArg(ArgRef.named('debugLabel')),
            omitWhenArgUnset: true),
        EmitMapEntry('fontFamily', EmitFragmentArg(ArgRef.named('fontFamily')),
            omitWhenArgUnset: true),
        EmitMapEntry('fontFamilyFallback',
            EmitFragmentArg(ArgRef.named('fontFamilyFallback')),
            omitWhenArgUnset: true),
        EmitMapEntry('fontPackage', EmitFragmentArg(ArgRef.named('package')),
            omitWhenArgUnset: true),
        EmitMapEntry('overflow', EmitFragmentArg(ArgRef.named('overflow')),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{}'),
  '#Color': TranslatorRecipe(
      typeName: 'Color',
      validations: [
        RecipeValidation(
            check: ArityExact(1),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color() requires a single integer literal argument. For non-literal channel values use Color.fromARGB.'),
        RecipeValidation(
            check: PositionalsAreIntLiterals(0, 1),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color() requires a single integer literal argument. For non-literal channel values use Color.fromARGB.'),
        RecipeValidation(
            check: PositionalIntsHaveValue(0, 1),
            issueCode: 'integerLiteralOverflow',
            message: 'Color() integer literal overflows int64.')
      ],
      emit: EmitFragmentKernel(TranslatorKernel.formatColorHex,
          [EmitValueArg(ArgRef.positional(0))]),
      failureDsl: ''),
  '#Color.fromARGB': TranslatorRecipe(
      typeName: 'Color',
      variant: 'fromARGB',
      validations: [
        RecipeValidation(
            check: ArityExact(4),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromARGB() requires four positional integer arguments (alpha, red, green, blue).'),
        RecipeValidation(
            check: PositionalsAreIntLiterals(0, 4),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromARGB() arguments must be integer literals. Use Color(0xAARRGGBB) for compile-time-known colors derived from runtime values.'),
        RecipeValidation(
            check: PositionalIntsHaveValue(0, 4),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromARGB() arguments must be integer literals. Use Color(0xAARRGGBB) for compile-time-known colors derived from runtime values.'),
        RecipeValidation(
            check: PositionalIntsInRange(0, 4, 0, 255),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromARGB() channel value {value} is out of the 0..255 range.')
      ],
      emit: EmitFragmentKernel(TranslatorKernel.formatColorHex, [
        EmitValueKernel(TranslatorKernel.packArgb, [
          EmitValueArg(ArgRef.positional(0)),
          EmitValueArg(ArgRef.positional(1)),
          EmitValueArg(ArgRef.positional(2)),
          EmitValueArg(ArgRef.positional(3))
        ])
      ]),
      failureDsl: ''),
  '#Color.fromRGBO': TranslatorRecipe(
      typeName: 'Color',
      variant: 'fromRGBO',
      validations: [
        RecipeValidation(
            check: ArityExact(4),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromRGBO() requires four positional arguments (red, green, blue, opacity).'),
        RecipeValidation(
            check: PositionalsAreIntLiterals(0, 3),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromRGBO() red/green/blue must be integer literals.'),
        RecipeValidation(
            check: PositionalIntsHaveValue(0, 3),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromRGBO() red/green/blue must be integer literals.'),
        RecipeValidation(
            check: PositionalIntsInRange(0, 3, 0, 255),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromRGBO() channel value {value} is out of the 0..255 range.'),
        RecipeValidation(
            check: PositionalNumLiteralInRange(3, 0.0, 1.0),
            issueCode: 'unrecognizedMethodCall',
            message:
                'Color.fromRGBO() opacity must be a numeric literal in 0.0..1.0.')
      ],
      emit: EmitFragmentKernel(TranslatorKernel.formatColorHex, [
        EmitValueKernel(TranslatorKernel.packArgb, [
          EmitValueKernel(TranslatorKernel.quantizeUnitToByte,
              [EmitValueArg(ArgRef.positional(3))]),
          EmitValueArg(ArgRef.positional(0)),
          EmitValueArg(ArgRef.positional(1)),
          EmitValueArg(ArgRef.positional(2))
        ])
      ]),
      failureDsl: ''),
  '#Alignment': TranslatorRecipe(
      typeName: 'Alignment',
      validations: [
        RecipeValidation(
            check: ArityExact(2),
            issueCode: 'unrecognizedMethodCall',
            message: 'Alignment() requires two positional arguments (x, y).')
      ],
      emit: EmitFragmentMap([
        EmitMapEntry(
            'x', EmitFragmentArg(ArgRef.positional(0), asLength: true)),
        EmitMapEntry('y', EmitFragmentArg(ArgRef.positional(1), asLength: true))
      ]),
      failureDsl: '{x: 0.0, y: 0.0}'),
  '#RadialGradient': TranslatorRecipe(
      typeName: 'RadialGradient',
      emit: EmitFragmentMap([
        EmitMapEntry('type', EmitFragmentLiteral('"radial"')),
        EmitMapEntry('colors', EmitFragmentArg(ArgRef.named('colors')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'stops', EmitFragmentArg(ArgRef.named('stops'), asDoubleList: true),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'center',
            EmitFragmentMemberTable(
                ArgRef.named('center'),
                {
                  'topLeft': EmitFragmentLiteral('{x: -1.0, y: -1.0}'),
                  'topCenter': EmitFragmentLiteral('{x: 0.0, y: -1.0}'),
                  'topRight': EmitFragmentLiteral('{x: 1.0, y: -1.0}'),
                  'centerLeft': EmitFragmentLiteral('{x: -1.0, y: 0.0}'),
                  'center': EmitFragmentLiteral('{x: 0.0, y: 0.0}'),
                  'centerRight': EmitFragmentLiteral('{x: 1.0, y: 0.0}'),
                  'bottomLeft': EmitFragmentLiteral('{x: -1.0, y: 1.0}'),
                  'bottomCenter': EmitFragmentLiteral('{x: 0.0, y: 1.0}'),
                  'bottomRight': EmitFragmentLiteral('{x: 1.0, y: 1.0}')
                },
                fallback: EmitFragmentArg(ArgRef.named('center'))),
            omitWhenArgUnset: true),
        EmitMapEntry('radius', EmitFragmentArg(ArgRef.named('radius')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'focal',
            EmitFragmentMemberTable(
                ArgRef.named('focal'),
                {
                  'topLeft': EmitFragmentLiteral('{x: -1.0, y: -1.0}'),
                  'topCenter': EmitFragmentLiteral('{x: 0.0, y: -1.0}'),
                  'topRight': EmitFragmentLiteral('{x: 1.0, y: -1.0}'),
                  'centerLeft': EmitFragmentLiteral('{x: -1.0, y: 0.0}'),
                  'center': EmitFragmentLiteral('{x: 0.0, y: 0.0}'),
                  'centerRight': EmitFragmentLiteral('{x: 1.0, y: 0.0}'),
                  'bottomLeft': EmitFragmentLiteral('{x: -1.0, y: 1.0}'),
                  'bottomCenter': EmitFragmentLiteral('{x: 0.0, y: 1.0}'),
                  'bottomRight': EmitFragmentLiteral('{x: 1.0, y: 1.0}')
                },
                fallback: EmitFragmentArg(ArgRef.named('focal'))),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'focalRadius', EmitFragmentArg(ArgRef.named('focalRadius')),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{type: "radial"}'),
  '#SweepGradient': TranslatorRecipe(
      typeName: 'SweepGradient',
      emit: EmitFragmentMap([
        EmitMapEntry('type', EmitFragmentLiteral('"sweep"')),
        EmitMapEntry('colors', EmitFragmentArg(ArgRef.named('colors')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'stops', EmitFragmentArg(ArgRef.named('stops'), asDoubleList: true),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'center',
            EmitFragmentMemberTable(
                ArgRef.named('center'),
                {
                  'topLeft': EmitFragmentLiteral('{x: -1.0, y: -1.0}'),
                  'topCenter': EmitFragmentLiteral('{x: 0.0, y: -1.0}'),
                  'topRight': EmitFragmentLiteral('{x: 1.0, y: -1.0}'),
                  'centerLeft': EmitFragmentLiteral('{x: -1.0, y: 0.0}'),
                  'center': EmitFragmentLiteral('{x: 0.0, y: 0.0}'),
                  'centerRight': EmitFragmentLiteral('{x: 1.0, y: 0.0}'),
                  'bottomLeft': EmitFragmentLiteral('{x: -1.0, y: 1.0}'),
                  'bottomCenter': EmitFragmentLiteral('{x: 0.0, y: 1.0}'),
                  'bottomRight': EmitFragmentLiteral('{x: 1.0, y: 1.0}')
                },
                fallback: EmitFragmentArg(ArgRef.named('center'))),
            omitWhenArgUnset: true),
        EmitMapEntry('startAngle', EmitFragmentArg(ArgRef.named('startAngle')),
            omitWhenArgUnset: true),
        EmitMapEntry('endAngle', EmitFragmentArg(ArgRef.named('endAngle')),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{type: "sweep"}'),
  '#NetworkImage': TranslatorRecipe(
      typeName: 'NetworkImage',
      validations: [
        RecipeValidation(
            check: ArityExact(1),
            issueCode: 'unrecognizedMethodCall',
            message:
                'NetworkImage() requires a single positional URL argument.')
      ],
      deferredNamedArgs: {'headers', 'webHtmlElementStrategy'},
      emit: EmitFragmentMap([
        EmitMapEntry('kind', EmitFragmentLiteral('"network"')),
        EmitMapEntry('src', EmitFragmentArg(ArgRef.positional(0))),
        EmitMapEntry(
            'scale', EmitFragmentArg(ArgRef.named('scale'), asLength: true),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{}'),
  '#AssetImage': TranslatorRecipe(
      typeName: 'AssetImage',
      validations: [
        RecipeValidation(
            check: ArityExact(1),
            issueCode: 'unrecognizedMethodCall',
            message:
                'AssetImage() requires a single positional asset-name argument.')
      ],
      deferredNamedArgs: {'bundle'},
      emit: EmitFragmentMap([
        EmitMapEntry('kind', EmitFragmentLiteral('"asset"')),
        EmitMapEntry('src', EmitFragmentArg(ArgRef.positional(0))),
        EmitMapEntry('package', EmitFragmentArg(ArgRef.named('package')),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{}'),
  '#DecorationImage': TranslatorRecipe(
      typeName: 'DecorationImage',
      deferredNamedArgs: {
        'colorFilter',
        'centerSlice',
        'matchTextDirection',
        'filterQuality',
        'invertColors',
        'isAntiAlias'
      },
      emit: EmitFragmentMap([
        EmitMapEntry('image', EmitFragmentArg(ArgRef.named('image')),
            omitWhenArgUnset: true),
        EmitMapEntry('fit', EmitFragmentArg(ArgRef.named('fit')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'alignment',
            EmitFragmentMemberTable(
                ArgRef.named('alignment'),
                {
                  'topLeft': EmitFragmentLiteral('{x: -1.0, y: -1.0}'),
                  'topCenter': EmitFragmentLiteral('{x: 0.0, y: -1.0}'),
                  'topRight': EmitFragmentLiteral('{x: 1.0, y: -1.0}'),
                  'centerLeft': EmitFragmentLiteral('{x: -1.0, y: 0.0}'),
                  'center': EmitFragmentLiteral('{x: 0.0, y: 0.0}'),
                  'centerRight': EmitFragmentLiteral('{x: 1.0, y: 0.0}'),
                  'bottomLeft': EmitFragmentLiteral('{x: -1.0, y: 1.0}'),
                  'bottomCenter': EmitFragmentLiteral('{x: 0.0, y: 1.0}'),
                  'bottomRight': EmitFragmentLiteral('{x: 1.0, y: 1.0}')
                },
                fallback: EmitFragmentArg(ArgRef.named('alignment'))),
            omitWhenArgUnset: true),
        EmitMapEntry('repeat', EmitFragmentArg(ArgRef.named('repeat')),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'opacity', EmitFragmentArg(ArgRef.named('opacity'), asLength: true),
            omitWhenArgUnset: true),
        EmitMapEntry(
            'scale', EmitFragmentArg(ArgRef.named('scale'), asLength: true),
            omitWhenArgUnset: true)
      ]),
      failureDsl: '{}'),
};
