// The build system deletes an output before re-running the step that owns it,
// so a step that refuses would leave the package without the file it wrote
// last time. The prior bytes are captured while they are still on disk, and
// each materializing builder writes its own back unchanged.

import 'dart:io';
import 'dart:isolate';

import 'package:build/build.dart';
import 'package:path/path.dart' as p;
import 'package:restage_codegen/src/surface_publication/output_placement.dart';

/// Reads a package's previously generated outputs, keyed by package-relative
/// path.
typedef PriorGeneratedOutputReader = Future<Map<String, List<int>>> Function(
  String package,
  RestageOutputPlacementPlan plan,
);

/// The prior outputs captured by this build, shared by every builder in it.
final Resource<RestagePreservedOutputs> restagePreservedOutputsResource =
    Resource<RestagePreservedOutputs>(RestagePreservedOutputs.new);

/// The generated bytes a refused build must leave unchanged.
final class RestagePreservedOutputs {
  final Map<String, Map<String, List<int>>> _byPackage = {};

  /// Records [outputs] as the bytes [package] carried before this build.
  void capture(String package, Map<String, List<int>> outputs) =>
      _byPackage[package] = outputs;

  /// The prior bytes at [path], or `null` when none were captured.
  List<int>? bytesFor(String package, String path) =>
      _byPackage[package]?[path];
}

/// Writes the captured prior bytes for [path] back, when this build has them.
Future<void> restorePreservedOutput(BuildStep buildStep, String path) async {
  final preserved = await buildStep.fetchResource(
    restagePreservedOutputsResource,
  );
  final bytes = preserved.bytesFor(buildStep.inputId.package, path);
  if (bytes == null) return;
  await buildStep.writeAsBytes(
    AssetId(buildStep.inputId.package, path),
    bytes,
  );
}

/// Suffixes of the per-library generated files, across every placement.
const List<String> _kPreservedSuffixes = <String>[
  '.restage.g.dart',
  '.rsbundle',
  '.restage.md',
];

/// Reads the package's previously generated outputs from its own directory,
/// which the build system leaves in place until each owning step re-runs.
Future<Map<String, List<int>>> readPriorGeneratedOutputs(
  String package,
  RestageOutputPlacementPlan plan,
) async {
  final packageLib = await Isolate.resolvePackageUri(
    Uri.parse('package:$package/'),
  );
  if (packageLib == null || packageLib.scheme != 'file') return const {};
  final root = Directory.fromUri(packageLib.resolve('../'));
  return readPriorGeneratedOutputsFromDirectory(root, plan);
}

/// Captures the previous valid files under the selected package directory.
Map<String, List<int>> readPriorGeneratedOutputsFromDirectory(
  Directory root,
  RestageOutputPlacementPlan plan,
) {
  if (!root.existsSync()) return const {};
  final outputs = <String, List<int>>{};
  for (final path in <String>[
    plan.publicationManifestPath,
    plan.outputIndexPath,
    plan.measurementOutputIndexPath,
    plan.analyticsIdMetadataPath,
    plan.customCatalogPath,
  ]) {
    final file = File(p.join(root.path, path));
    if (file.existsSync()) outputs[path] = file.readAsBytesSync();
  }
  _collectGeneratedFiles(root, root: root.path, outputs: outputs);
  final portable = Directory(p.join(root.path, plan.outputRoot!));
  if (portable.existsSync()) {
    _collectGeneratedFiles(portable,
        root: root.path, outputs: outputs, includeHidden: true);
  }
  return outputs;
}

void _collectGeneratedFiles(
  Directory directory, {
  required String root,
  required Map<String, List<int>> outputs,
  bool includeHidden = false,
}) {
  for (final entity in directory.listSync(followLinks: false)) {
    final name = p.basename(entity.path);
    if (!includeHidden && (name.startsWith('.') || name == 'build')) continue;
    if (entity is Directory) {
      _collectGeneratedFiles(entity,
          root: root, outputs: outputs, includeHidden: includeHidden);
      continue;
    }
    if (entity is! File) continue;
    if (!_kPreservedSuffixes.any(name.endsWith)) continue;
    final relative = p.posix.joinAll(
      p.split(p.relative(entity.path, from: root)),
    );
    outputs[relative] = entity.readAsBytesSync();
  }
}
