// GENERATED CODE - DO NOT MODIFY BY HAND
// GENERATED BY RESTAGE WIDGETBOOK STORY BUILDER
// ignore_for_file: library_private_types_in_public_api, unused_import

import 'package:widgetbook/widgetbook.dart' as widgetbook;
import 'package:widgetbook/widgetbook.dart';
import 'package:restage/restage.dart' as restage_runtime;
import 'package:restage_widgetbook_example/onboarding/screens/opaque_screen_proof.dart'
    as restage_source;
import 'package:restage_widgetbook_example/onboarding/screens/opaque_screen_proof.dart'
    show OpaqueScreenProof;
import 'package:restage_widgetbook_example/onboarding/screens/opaque_screen_proof.dart'
    show OpaqueScreenProofTone;

part 'opaque_screen_proof.stories.g.dart';

enum _RestageChoice2 { value0, value1 }

enum _RestageChoice6 { value0, value1 }

class OpaqueScreenProofStoryInput {
  const OpaqueScreenProofStoryInput({
    this.restageMetadataDescription =
        "Native screen used to verify opaque A2UI and Widgetbook integration.\n\nOne authored class feeds RFW, A2UI, and Widgetbook in the normal build.",
    this.restageMetadataUsage =
        "Use for the final action in a native onboarding flow.",
    this.title = "",
    this.enabled = true,
    this.tone = _RestageChoice2.value0,
    this.data = "Customer data",
    this.context = "Customer context",
    this.itemContext = "Customer item context",
    this.restageA2uiStatus = _RestageChoice6.value0,
    this.description = "Customer description",
    this.usage = "Customer usage",
  });

  final String restageMetadataDescription;
  final String restageMetadataUsage;
  final String title;
  final bool enabled;
  final _RestageChoice2 tone;
  final String data;
  final String context;
  final String itemContext;
  final _RestageChoice6 restageA2uiStatus;
  final String description;
  final String usage;
}

const meta = widgetbook.Meta(
  restage_source.OpaqueScreenProof.new,
  argsType: OpaqueScreenProofStoryInput.new,
);

const component = widgetbook.ComponentMeta(
  name: "opaque_screen_proof",
  path: 'Screens',
);

final previewEvents = <({String id, Object? value})>[];

final defaults = _Defaults(
  setup: (context, child, args) => restage_runtime.RestageEventDispatcher(
    onEvent: (eventId, value) => previewEvents.add((id: eventId, value: value)),
    child: child,
  ),
  builder: (context, args) => restage_source.OpaqueScreenProof(
    title: args.title,
    enabled: args.enabled,
    tone: switch (args.tone) {
      _RestageChoice2.value0 => restage_source.OpaqueScreenProofTone.calm,
      _RestageChoice2.value1 => restage_source.OpaqueScreenProofTone.urgent,
    },
    data: args.data,
    context: args.context,
    itemContext: args.itemContext,
    restageA2uiStatus: switch (args.restageA2uiStatus) {
      _RestageChoice6.value0 => restage_source.OpaqueScreenProofTone.calm,
      _RestageChoice6.value1 => restage_source.OpaqueScreenProofTone.urgent,
    },
    description: args.description,
    usage: args.usage,
  ),
);

final $RestageCatalog = _Story(
  args: _Args(
    restageMetadataDescription: _RestageMetadataArg(
      "Native screen used to verify opaque A2UI and Widgetbook integration.\n\nOne authored class feeds RFW, A2UI, and Widgetbook in the normal build.",
      name: 'Restage description',
    ),
    restageMetadataUsage: _RestageMetadataArg(
      "Use for the final action in a native onboarding flow.",
      name: 'Restage usage',
    ),
    title: _RestageStringArg(
      "",
      description: "Constructor-bound title retained by native targets.",
    ),
    enabled: _RestageBoolArg(
      true,
      description:
          "Constructor-bound state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    tone: _RestageEnumArg<_RestageChoice2>(
      _RestageChoice2.value0,
      values: _RestageChoice2.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice2.value0 => "calm",
        _RestageChoice2.value1 => "urgent",
      },
      description:
          "Typed preview state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    data: _RestageStringArg(
      "Customer data",
      description:
          "Customer data retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    context: _RestageStringArg(
      "Customer context",
      description:
          "Customer context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    itemContext: _RestageStringArg(
      "Customer item context",
      description:
          "Customer item context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    restageA2uiStatus: _RestageEnumArg<_RestageChoice6>(
      _RestageChoice6.value0,
      values: _RestageChoice6.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice6.value0 => "calm",
        _RestageChoice6.value1 => "urgent",
      },
      description:
          "Customer enum retained despite matching a generated-local prefix. Default: the widget constructor's Dart default.",
    ),
    description: _RestageStringArg(
      "Customer description",
      description:
          "Editable customer description shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
    usage: _RestageStringArg(
      "Customer usage",
      description:
          "Editable customer usage shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
  ),
);

final $EnabledFalse = _Story(
  args: _Args(
    restageMetadataDescription: _RestageMetadataArg(
      "Native screen used to verify opaque A2UI and Widgetbook integration.\n\nOne authored class feeds RFW, A2UI, and Widgetbook in the normal build.",
      name: 'Restage description',
    ),
    restageMetadataUsage: _RestageMetadataArg(
      "Use for the final action in a native onboarding flow.",
      name: 'Restage usage',
    ),
    title: _RestageStringArg(
      "",
      description: "Constructor-bound title retained by native targets.",
    ),
    enabled: _RestageBoolArg(
      false,
      description:
          "Constructor-bound state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    tone: _RestageEnumArg<_RestageChoice2>(
      _RestageChoice2.value0,
      values: _RestageChoice2.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice2.value0 => "calm",
        _RestageChoice2.value1 => "urgent",
      },
      description:
          "Typed preview state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    data: _RestageStringArg(
      "Customer data",
      description:
          "Customer data retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    context: _RestageStringArg(
      "Customer context",
      description:
          "Customer context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    itemContext: _RestageStringArg(
      "Customer item context",
      description:
          "Customer item context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    restageA2uiStatus: _RestageEnumArg<_RestageChoice6>(
      _RestageChoice6.value0,
      values: _RestageChoice6.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice6.value0 => "calm",
        _RestageChoice6.value1 => "urgent",
      },
      description:
          "Customer enum retained despite matching a generated-local prefix. Default: the widget constructor's Dart default.",
    ),
    description: _RestageStringArg(
      "Customer description",
      description:
          "Editable customer description shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
    usage: _RestageStringArg(
      "Customer usage",
      description:
          "Editable customer usage shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
  ),
);

final $ToneUrgent = _Story(
  args: _Args(
    restageMetadataDescription: _RestageMetadataArg(
      "Native screen used to verify opaque A2UI and Widgetbook integration.\n\nOne authored class feeds RFW, A2UI, and Widgetbook in the normal build.",
      name: 'Restage description',
    ),
    restageMetadataUsage: _RestageMetadataArg(
      "Use for the final action in a native onboarding flow.",
      name: 'Restage usage',
    ),
    title: _RestageStringArg(
      "",
      description: "Constructor-bound title retained by native targets.",
    ),
    enabled: _RestageBoolArg(
      true,
      description:
          "Constructor-bound state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    tone: _RestageEnumArg<_RestageChoice2>(
      _RestageChoice2.value1,
      values: _RestageChoice2.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice2.value0 => "calm",
        _RestageChoice2.value1 => "urgent",
      },
      description:
          "Typed preview state retained by native targets. Default: the widget constructor's Dart default.",
    ),
    data: _RestageStringArg(
      "Customer data",
      description:
          "Customer data retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    context: _RestageStringArg(
      "Customer context",
      description:
          "Customer context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    itemContext: _RestageStringArg(
      "Customer item context",
      description:
          "Customer item context retained under its exact Dart name. Default: the widget constructor's Dart default.",
    ),
    restageA2uiStatus: _RestageEnumArg<_RestageChoice6>(
      _RestageChoice6.value0,
      values: _RestageChoice6.values,
      labelBuilder: (value) => switch (value) {
        _RestageChoice6.value0 => "calm",
        _RestageChoice6.value1 => "urgent",
      },
      description:
          "Customer enum retained despite matching a generated-local prefix. Default: the widget constructor's Dart default.",
    ),
    description: _RestageStringArg(
      "Customer description",
      description:
          "Editable customer description shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
    usage: _RestageStringArg(
      "Customer usage",
      description:
          "Editable customer usage shown beside Restage metadata. Default: the widget constructor's Dart default.",
    ),
  ),
);

mixin _RestageArgDescription<T> on widgetbook.Arg<T> {
  String get restageDescription;

  @override
  String? get description => restageDescription;
}

final class _RestageMetadataArg extends widgetbook.Arg<String>
    with widgetbook.NoFields<String> {
  _RestageMetadataArg(super.value, {required super.name});

  @override
  String get description => value;
}

final class _RestageStringArg extends widgetbook.StringArg
    with _RestageArgDescription<String> {
  _RestageStringArg(super.value, {required String description})
    : restageDescription = description;

  @override
  final String restageDescription;
}

final class _RestageBoolArg extends widgetbook.BoolArg
    with _RestageArgDescription<bool> {
  _RestageBoolArg(super.value, {required String description})
    : restageDescription = description;

  @override
  final String restageDescription;
}

final class _RestageEnumArg<T extends Enum> extends widgetbook.EnumArg<T>
    with _RestageArgDescription<T> {
  _RestageEnumArg(
    super.value, {
    required super.values,
    required super.labelBuilder,
    required String description,
  }) : restageDescription = description;

  @override
  final String restageDescription;
}
